Enhancement Probes
ExtremeFLOW/neko pull request #1004
Opened 2023-10-16 22:47 UTC by MartinKarp

Start of reworking probes into a simulation component and where we limiti redundancy across ranks as far as possible. The redist I think can be made nicer and more efficient with some clever alltoallv as to avoid looping over all the ranks.

IN hindsight I should have started with moving the original probes file directly to a sim comp and then modified it after. Now I have  instead changed it first and will move it to sim comp last. 

Do not merge, but if you need the local interpolation Niclas, here is some sketch for it.

Will push more changes tomorrow.

2023-10-17 15:15 UTC, timofeymukha commented on src/simulation_components/probes.F90
> +  !! @coef Xh Function space.
Seems incorrect.

2023-10-18 01:35 UTC, njansson requested changes
Very nice!

As pointed out by @timofeymukha, would be great if this can be documented as well, e.g. list Probes in the list of provided simulations components (in the manual)

2023-10-18 01:35 UTC, njansson commented on src/sem/local_interpolation.f90
> +!> Routines to obtain interpolated values on a set of points with known rst coordinates in elements local to this process
```suggestion
!> Routines to obtain interpolated values on a set of points with known 
!! rst coordinates in elements local to this process.
```

2023-10-18 08:13 UTC, vbaconnet commented on src/sem/local_interpolation.f90
> +     procedure, pass(this) :: evaluate => local_interpolator_evaluate_values
How about this?
```suggestion
     procedure, pass(this) :: evaluate => local_interpolator_evaluate
```

2023-10-18 08:49 UTC, MartinKarp commented on src/sem/local_interpolation.f90
> +     procedure, pass(this) :: evaluate => local_interpolator_evaluate_values
I changed it now, but I anticipate we will have many evaluates with different number of fields etc. in the future.

2023-10-18 08:49 UTC, MartinKarp commented
> Very nice. So probes are just a simcomp wrapping together IO and the global interpolation, right? And the global interpolation does the work, using under the hood local_interpolation?
> 
> Could you elaborate a bit more on the local_interpolation vs point_interpolator? When is one to use which? It may be worth adding this info to the type docstring of both types, since anyone who would go looking for the functionality will wonder about the 2 similar types.

Regarding local_interpolator vs point_interpolator, they provide very similar functionality. IMO using local_interpolation is the way to go unless one has a bunch of type(point_t) points. I am updating it so that point_interpolator only works with the typ(point_t) type while local_interpolation only handles arrays. point_interpolator also provides functionality to directly get the jacobian and such, so I did not want to remove it.

2023-10-18 09:21 UTC, vbaconnet commented
Curious about the behaviour of probes as simcomp now, does this mean that one could add two probes simcomps with different input files? Like this for example:

```json
{
   "type": "probes",
   "compute_control": "simulationtime",
   "compute_value"    : 1,
   "points_file":  "probes1.csv",
   "output_file":  "output1.csv",
   "fields": ["w","s"]
 }
 {
   "type": "probes",
   "compute_control": "simulationtime",
   "compute_value"    : 1,
   "points_file":  "probes2.csv",
   "output_file":  "output2.csv",
   "fields": ["u","p"]
 }
```

2023-10-18 09:37 UTC, vbaconnet commented
This kind of makes me question the need for `point_interpolator`. If I understood correctly it is not being used at all right now correct? The idea behind it when I implemented it was to write some functions (with the Jacobian etc) to be used for replacing gslib in the local mapping inside elements, but maybe this can now go into `local interpolation`. Might be out of the scope of this PR but noteworthy I think!

2023-10-18 09:40 UTC, vbaconnet approved these changes
I think it's really nice to have everything properly organized into global and local interpolation. Really like it! And the simcomps stuff opens up a lot of possibilities.

2023-10-18 10:30 UTC, timofeymukha commented on doc/pages/simcomps.md
> + Computes Lambda2 for the velocity field and stores it in the normal output files as the first unused field.
```suggestion
 Computes \f$ \lambda_2 \f$ for the velocity field and stores it in the normal output files as the first unused field.
```

2023-10-18 10:30 UTC, timofeymukha commented on doc/pages/simcomps.md
> + This means that lambda2 can be found in the temeprature field in then fld files if running without a scalar
```suggestion
 This means that \f$ \lambda_2 \f$ can be found in the temeprature field in then fld files if running without a scalar
```

2023-10-18 10:30 UTC, timofeymukha commented on doc/pages/simcomps.md
> + Probes the fluid field in the points given by an input file. Example usage:
```suggestion
 Probes selected solution fields at the points given inside an input file. Example usage:
```

2023-10-18 14:05 UTC, njansson approved these changes

2023-10-18 14:19 UTC, timofeymukha approved these changes

2023-10-18 15:23 UTC, merged