Fix privacy and imports in krylov solvers
ExtremeFLOW/neko pull request #1011
Opened 2023-10-18 14:34 UTC by timofeymukha

This mostly fixed use statements in Krylov solver types, making the use `only`. Also adds `private` at module scope in some places. A little bit of docstrings. No functionality is changed.

2023-10-25 13:22 UTC, MartinKarp approved these changes
Looks very good. Big improvements over before.

2023-10-26 00:37 UTC, njansson reviewed
I would like to try this with recent version of CCE before merging.

2023-10-26 00:41 UTC, njansson requested changes

2023-10-26 00:41 UTC, njansson commented on src/math/ax_helm_fctry.f90
> +  !! @param Ax The matrix-vector product type to be allocated.
```suggestion
  !> Factory routine for the a Helmholtz problem matrix-vector product.
  !! The selection is based on the compute backend.
  !! @param Ax The matrix-vector product type to be allocated.
```

2023-10-26 00:41 UTC, njansson commented on src/math/bcknd/cpu/ax_helm.f90
> +  !> CPU matrix-vector product for a Helmholz problem.
```suggestion
  !> CPU matrix-vector product for a Helmholtz problem.
```

2023-10-26 00:41 UTC, njansson commented on src/math/bcknd/cpu/ax_helm.f90
> +  !> Generic CPU kernel for the Helmholz matrix-vector product.
```suggestion
  !> Generic CPU kernel for the Helmholtz matrix-vector product.
```

2023-10-26 00:41 UTC, njansson commented on src/math/ax_helm_fctry.f90
> +  !! @param Ax The matrix-vector product type to be allocated.
```suggestion
  !> Factory routine for the a Helmholtz problem matrix-vector product.
  !! The selection is based on the compute backend.
  !! @param Ax The matrix-vector product type to be allocated.
```

2023-11-07 08:52 UTC, njansson approved these changes

2023-11-07 09:10 UTC, merged