Lift and drag and 1D GLL point mapping
ExtremeFLOW/neko pull request #1014
Opened 2023-10-25 13:16 UTC by MartinKarp

In this PR I add some functionality to calculate the drag and torque around an object and functionality to map a dofmap to a 1D grid.

As I was interested of lift as a function of y I added map_1d.f90 which takes a dofmap and creates a mapping (i,j,k,e) -> (idx) where idx is the global index in a 1D-GLL point grid in some specified direction. Essentially it is mapping to a certain plane in the mesh. This is quite useful when one wants to for example do averaging or similar. 

This map_1d is quite powerful and should perhaps have had its own PR.

This is work in progress, but I would like your feedback on a map_1d in particular as I think it might be used quite a lot for averaging and mapping points to a global grid. I would also appreciate @adampep input on whether how I find the number of elements and map the points is a reasonable way of going about it.

TODO: Clean up lift_torque, the new contrib script and map_1d.

2024-01-18 08:32 UTC, njansson requested changes

2024-01-18 08:32 UTC, njansson commented on src/qoi/drag_torque.f90
> +      !call gop(torqvz,w1,'+  ',2)
```suggestion
```

2024-01-18 08:33 UTC, njansson approved these changes

2024-01-22 11:00 UTC, timofeymukha commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +!! Computes both the toal drag/lift and outputs in stdout as well as the drag lift along a specified direction (x,y,z)
I am confused here a bit. So it is both drag and lift, not just lift as it says in the 1st row? Also, a bit confused by the direction thing. I guess lift and drag are just force projections on some two axis, right? Drag for the streamwise and lift for the one normal to that. So I don't quite understand what is meant by line 3.

2024-01-22 11:26 UTC, timofeymukha commented on src/sem/map_1d.f90
> +       el_dim(2,:) = abs(this%msh%elements(i)%e%pts(1)%p%x-this%msh%elements(i)%e%pts(3)%p%x)
```suggestion
       el_dim(2,:) = abs(this%msh%elements(i)%e%pts(1)%p%x - this%msh%elements(i)%e%pts(3)%p%x)
```

2024-01-22 11:26 UTC, timofeymukha commented on src/sem/map_1d.f90
> +       el_dim(3,:) = abs(this%msh%elements(i)%e%pts(1)%p%x-this%msh%elements(i)%e%pts(5)%p%x)
```suggestion
       el_dim(3,:) = abs(this%msh%elements(i)%e%pts(1)%p%x - this%msh%elements(i)%e%pts(5)%p%x)
```

2024-01-22 11:27 UTC, timofeymukha commented on src/sem/map_1d.f90
> +       if (relcmp(el_min,glb_min,this%tol)) then
```suggestion
       if (relcmp(el_min, glb_min, this%tol)) then
```

2024-01-22 11:30 UTC, timofeymukha commented on src/sem/map_1d.f90
> +    do e = 1, nelv
Martin, we have basically 3 do loops here. Maybe just a short comment line above each, telling what is done inside?

2024-01-22 15:58 UTC, MartinKarp commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +!! Computes both the toal drag/lift and outputs in stdout as well as the drag lift along a specified direction (x,y,z)
This computes the "drag" in each direction x,y,z. Whether this is a lifting force or not is kind of up to the user to interpret based on what is the spanwise, streamwise etc direction in their case.

2024-01-22 16:00 UTC, MartinKarp commented on src/qoi/drag_torque.f90
> +    SKPDAT(6,6)=1
Yes, but this si more or less exaclt yhow it is done in Nek5000 in many places. I guess @njansson might have some opinion here too. IN most places where we do things like this we check what face something is on instead (*look at for example calcuating the normals in coef.f90), but this is quite nice in that one can then do a simple double loop.

2024-01-22 16:19 UTC, MartinKarp commented on src/sem/map_1d.f90
> +    do e = 1, nelv
I added some doc

2024-01-22 16:28 UTC, MartinKarp commented
Another note is the license, I think this is quite similar to the Nek5000 code and should perhaps have the Argonne thing in it right?

2024-01-23 05:17 UTC, timofeymukha commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +!! Martin Karp 17/01-24
```suggestion
!> Program to calculate the force acting on a single boundary zone.
!! Can also calculate the torque around a point if one changes the value of center (defaults to 0,0,0).
!! Computes and outputs both the total force as well as its projection on a specified direction (x,y,z),
!! which can be used to compute lift or drag.
!! Martin Karp 17/01-24
```

2024-01-23 06:39 UTC, timofeymukha commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +     call neko_error('homogenous direction not supported')
```suggestion
     call neko_error('The homogeneous direction should be "x", "y"or "z"')
```

2024-01-23 06:39 UTC, timofeymukha commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +             & torqpz, torqvx, torqvy, torqvz')
```suggestion
  if (pe_rank .eq. 0) call output_file%set_header('time, coord, forcepx, forcepy, &
             & forcepz, forcevx, forcevy, forcevz, torqpx, torqpy, &
             & torqpz, torqvx, torqvy, torqvz')
```

2024-01-23 06:39 UTC, timofeymukha commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +        write(*,*) 'Computes the lift at each level in the mesh at coord y'
```suggestion
        write(*,*) 'Outputs the total force and torque on zone 5 using velocity values from fieldblabla.fld'
        write(*,*)  'as well as writes the distribution of the force and torque across y to output.csv'
```

2024-01-23 06:39 UTC, timofeymukha commented on contrib/calc_lift_from_field/calc_lift_from_field.f90
> +!! Computes both the toal drag/lift and outputs in stdout as well as the drag lift along a specified direction (x,y,z)
OK, but then I would not call this drag or lift, but simply force? The way it is now, the utility name and the first line of the description are very specific that it is lift, so I think that will confuse more people than myself :-). I added a suggestion for a revised docstring. I realize now that the "drag" routines we lifted from nek here are also just forces and not necessarily drag, but maybe we can live with that, at least for now.

I would suggest maybe renaming the utility itself to something like "calc_zone_forces" or similar. 

Sorry about being picky with this! I think this utility will be used a lot so I wanted to polish the use experience a bit :-)!

2024-02-16 07:26 UTC, njansson commented
> Another note is the license, I think this is quite similar to the Nek5000 code and should perhaps have the Argonne thing in it right? The drag_torque.f90 that is.

Agree

2024-03-05 06:56 UTC, timofeymukha commented on src/qoi/drag_torque.f90
> +    SKPDAT(6,6)=1
Pinging @njansson

2024-03-05 12:12 UTC, MartinKarp commented
I have mostly worked on the thesis, so I have not had it very high on my priority list. I might work on it this week though as I have a somewhat reasonable draft for the thesis.

2024-03-05 14:35 UTC, timofeymukha approved these changes

2024-03-06 05:29 UTC, merged