Moved general sorting related functions to math
ExtremeFLOW/neko pull request #1021
Opened 2023-11-02 10:08 UTC by adampep

Sorting related functions moved to math for consistency and integer variants added. Will be used in mesh connectivity

2023-11-02 13:08 UTC, MartinKarp commented on src/math/math.f90
> +  !> Heap Sort for single integer arrays  (p 231 Num. Rec., 1st Ed.)
Perhaps we can add a bit more description on the arguments now that we move things as well. Otherwise, I think it looks good and is a welcome change

2023-11-02 15:34 UTC, adampep commented on src/math/math.f90
> +  !> Heap Sort for single integer arrays  (p 231 Num. Rec., 1st Ed.)
Does the next commit give what yu expected?

2023-11-03 07:18 UTC, njansson requested changes

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +    return
```suggestion
```

2023-11-03 07:18 UTC, njansson commented on src/math/math.f90
> +  end interface flipv
To keep the structure of the file, I rather see this move before the public block, after the existing interface definitions

2023-11-15 10:20 UTC, adperezm commented
As a comment to this. I have a bunch of sorting routines per element for GPUs in the compression branch. So before implementing any of that in Cuda or Rocm, check there first. 

I hope that I merge all that before this year is over, but just letting you know.

2023-11-28 14:14 UTC, timofeymukha commented
Are we happy? :-)

2024-05-30 12:22 UTC, timfelle commented
Is this still alive or have it been superseeded by other PR's?

2024-07-02 06:27 UTC, njansson commented
> 

Should still be alive! 

I've fixed the merge conflicts. No problem from my side to get this in

2024-07-02 06:27 UTC, njansson approved these changes

2024-07-02 08:12 UTC, timfelle approved these changes
I think the sorting algorithms are a prime example of something we could move to a submodule.
That should improve compilation efficiency.
But that should probably be a sepparate PR.

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +  subroutine sortdp(a,ind,n)
Should probably call this `sortrp` or actually change the type to be `dp`.

In general we should probably have one for `dp` and `sp`
```suggestion
  subroutine sortrp(a, ind, n)
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +          l=l-1
```suggestion
          l = l - 1
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +          ir=ir-1
```suggestion
          ir = ir - 1
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +             if ( a(j).lt.a(j+1) ) j=j+1
```suggestion
             if ( a(j) .lt. a(j + 1) ) j = j + 1
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +             i=j
```suggestion
             i = j
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +             j=j+j
```suggestion
             j = j + j
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +             j=ir+1
```suggestion
             j = ir + 1
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +          endif
```suggestion
          end if
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +          endif
```suggestion
          end if
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +          if (ir.eq.1) then
```suggestion
          if (ir .eq. 1) then
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +       j=l+l
```suggestion
       j = l + l
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +       i=l
```suggestion
       i = l
```

2024-07-02 08:12 UTC, timfelle commented on src/math/math.f90
> +    if (n.le.1) return
```suggestion
    if (n .le. 1) return
```

2024-07-02 08:12 UTC, timfelle commented on src/sem/cpr.f90
> +    integer, intent(in) :: kut
No reason to add new whitespaces here.
```suggestion
  !> create filter transfer function
  subroutine build_filter_tf(fx, fy, fz, kut, lx)
    integer, intent(in) :: lx
    integer, intent(in) :: kut
```

2024-07-02 08:12 UTC, timfelle commented on src/sem/cpr.f90
> +    real(kind=rp) :: fz(cpr%Xh%lx, cpr%Xh%lx)
```suggestion
    real(kind=rp) :: errvec(cpr%Xh%lx, cpr%Xh%lx, cpr%Xh%lx)
    real(kind=rp) :: fx(cpr%Xh%lx, cpr%Xh%lx)
    real(kind=rp) :: fy(cpr%Xh%lx, cpr%Xh%lx)
    real(kind=rp) :: fz(cpr%Xh%lx, cpr%Xh%lx)
```

2024-07-02 08:12 UTC, timfelle commented on src/sem/cpr.f90
> +    character(len=LOG_SIZE) :: log_buf
```suggestion
    character(len=LOG_SIZE) :: log_buf
```

2024-07-02 08:15 UTC, njansson commented
> I think the sorting algorithms are a prime example of something we could move to a submodule. That should improve compilation efficiency. But that should probably be a sepparate PR.

Agree, would be good to have generic sorting routines (good ones) in a separate module

2024-07-02 08:17 UTC, timfelle commented on src/math/math.f90
> +     module procedure sortdp, sorti4
```suggestion
     module procedure sortrp, sorti4
```

2024-07-02 08:17 UTC, timfelle commented on src/math/math.f90
> +     module procedure sortdp, sorti4
renaming wasn't done correctly by my suggestion 😰

2024-07-02 08:22 UTC, timfelle commented on src/math/math.f90
> +
One more
```suggestion
  end subroutine sortrp
```

2024-07-02 08:23 UTC, timfelle commented on src/math/math.f90
> +  end subroutine sortdp
```suggestion
  end subroutine sortrp
```

2024-07-02 08:41 UTC, merged