Feature/metadata in fldfile
ExtremeFLOW/neko pull request #1098
Opened 2024-01-03 14:26 UTC by adperezm

Metadata mentioned by @siavash has been included into the files. It seems to work fine although I have not tested if it fixed the visualization problems yet.

2024-01-03 14:27 UTC, adperezm commented
I also fixed the rbc example. I should have created a new request but that was inconvenient. I hope that is okay.

2024-01-03 14:31 UTC, njansson approved these changes
Nice! Hope this resolves the issues with large files

2024-01-08 09:41 UTC, MartinKarp requested changes
Looks good! This will be really good I think. The only thing is to double-check the offset for the scalar metadata and move vlmin and vlmax. Also, if you have had time to check if it helps with the slicing that would be great :)

2024-01-08 09:41 UTC, MartinKarp commented on src/io/fld_file.f90
> +                       int(MPI_REAL_SIZE, i8)
This is not correct I think, there will be a gap after the first metadata for the scalar. Look at how we do for the fields, there we save one temp_offset before the loop.

2024-01-08 09:41 UTC, MartinKarp commented on src/io/fld_file.f90
> +    real(kind=rp) :: vecmin
vlmin and vlmax should probably be moved to math.

2024-01-09 13:54 UTC, adperezm commented
Hej! I corrected the suggestions. When you have time check again.

2024-01-09 14:28 UTC, MartinKarp approved these changes
Looks good!

2024-01-09 14:28 UTC, merged