Add rotating cone example
ExtremeFLOW/neko pull request #1110
Opened 2024-01-21 06:03 UTC by timofeymukha

This is an example used both P. Fischer and by the Nektar++ folks to demonstrate the benefit of high order. A cone is placed in a vortex and advected a single revolution. At the end, we look at the form of the cone and see if it is preserved.

2024-01-21 09:49 UTC, njansson requested changes

2024-01-21 09:49 UTC, njansson commented on examples/rotating_cone/rotating_cone.f90
> +       .or. (NEKO_BCKND_OPENCL .eq. 1)) then
```suggestion
    if (NEKO_BCKND_DEVICE .eq. 1) then
```
Device covers CUDA/hip and opencl

2024-01-21 09:49 UTC, njansson commented on examples/rotating_cone/rotating_cone.f90
> +       .or. (NEKO_BCKND_OPENCL .eq. 1)) then
```suggestion
    if (NEKO_BCKND_DEVICE .eq. 1) then
```
Device covers all cases

2024-01-21 10:16 UTC, pschlatt1 commented
Excellent example! We could use this nicely in teaching! One simple comment: shoukdnt we call it convecting cone?

2024-01-21 10:22 UTC, timofeymukha commented
> Excellent example! We could use this nicely in teaching! One simple comment: shoukdnt we call it convecting cone?

Thanks, Philipp! Maybe `advected_cone` since we call it advection in the code?

2024-01-21 10:41 UTC, pschlatt1 commented
yes. advecting (or advected) is in principle better. Gottlieb and Orszag (1977) where the problem originated, called it convecting cone. So perhaps then advecting cone? Knowing that advected would be better.

2024-01-22 06:35 UTC, timofeymukha commented
> yes. advecting (or advected) is in principle better. Gottlieb and Orszag (1977) where the problem originated, called it convecting cone. So perhaps then advecting cone? Knowing that advected would be better.

Changed to advecting cone!

2024-01-24 07:51 UTC, njansson approved these changes

2024-01-30 12:57 UTC, merged