Add "only" to file module
ExtremeFLOW/neko pull request #1114
Opened 2024-01-22 10:55 UTC by timofeymukha

Just a small improvement according to our guidelines.

2024-01-22 13:51 UTC, njansson requested changes
See comments

2024-01-22 14:21 UTC, timofeymukha commented on src/io/file.f90
> +  !! subroutine, like for most other polymorphic types.
Isn't the `init` for `file_t` essentially a factory for `generic_file_t`? That *could* just be a standalone subroutine like for the solver, simcomps, etc., no?

2024-01-23 13:57 UTC, njansson commented on src/io/file.f90
> +  !! subroutine, like for most other polymorphic types.
Yes kind of, but separation here allows us to avoid circular dependencies

2024-01-23 14:01 UTC, timofeymukha commented
I accidently pushed something else to this branch :-). I will reopen with the @remark removed.

2024-01-23 14:01 UTC, closed without merging