Generic fld_output, global output_control and simcomp file output
ExtremeFLOW/neko pull request #1117
Opened 2024-01-23 14:09 UTC by timofeymukha

This PR introduces:

- `output_control: "global"` for simcomps, which syncs `output_control` and `output_value` with the fluid. Useful to control output of multiple thing by a single set of parameters.
- `fld_output_t`, which is much luck `fluid_output` but does not add the fluid fields to the output. Can be used to output any number of arrays to a new fld.
- Working on outputing simcomp fields to files. What I have now is that if you don't specify `output_filename`, the field (e.g. vorticity) gets added to the `fluid_output` in the case. Otherwise, a new fld file is created. Opinions welcome.
- A small refactor to the `output_t` constructor, so that one can use `init` in descendents as is now standard.

When working on this I realized that e.g. the probes simcom just manages its own output, without adding an `output` to the `sampler`. I'm not sure what is best and how things will go forwards, so here I focused on making it easier to use the `sampler` by adding `fld_output_t`.

2024-01-23 14:10 UTC, timofeymukha commented
TODO: handle precision, add the same to lambda2.

2024-01-24 08:14 UTC, njansson approved these changes

2024-01-24 08:15 UTC, njansson commented
🍻

2024-02-01 14:09 UTC, timofeymukha commented
@MartinKarp Whenever you have time :-).

2024-02-05 08:24 UTC, MartinKarp requested changes
Looks good I think, good that it is now easier to add things to the "sampler" (which we should not forget to rename at some point). I do not really see the reason for why we have som many output types after this change though, from my side, I think as much as possible should then use fld_(list)_output unless one does some special operation before.

2024-02-05 08:24 UTC, MartinKarp commented on src/io/fld_output.f90
> +!> Implements `fld_output_t`.
fld_list_output? Sorry for nitpick, but thought it might be easy to confuse fluid_output and fld_output.

2024-02-05 08:34 UTC, timofeymukha commented on src/io/fld_output.f90
> +!> Implements `fld_output_t`.
Yes, I think, in particular the fluid_output could be quite easily removed, which would incidentally address your second comment :-). Here by `fld` I meant the .fld file suffix, not an abbreviation of field or so. Maybe `fld_file_foutput_t` then?

2024-02-05 08:35 UTC, MartinKarp commented on src/io/fld_output.f90
> +!> Implements `fld_output_t`.
Sounds good!

2024-02-05 09:29 UTC, timofeymukha commented on src/io/fld_output.f90
> +!> Implements `fld_output_t`.
Done

2024-02-05 09:33 UTC, MartinKarp approved these changes

2024-02-05 10:06 UTC, merged