Docstrings, and "only" for operators
ExtremeFLOW/neko pull request #1139
Opened 2024-02-14 08:36 UTC by timofeymukha

* Adds `only` to imports in operators.f90
* Adds docstrings to the operators. I am unsure about one parameter in the `ortho`, please help :-).
* Renamed `c_Xh` to `coef` in `curl`, because all the other operators use `coef`.

2024-02-14 08:45 UTC, njansson reviewed
I think that with dropping `Xh` we also dropped the connection/indication that the given coefficient is related to a certain function space

2024-02-14 08:50 UTC, timofeymukha commented
> I think that with dropping `Xh` we also dropped the connection/indication that the given coefficient is related to a certain function space

I know you like the `Xh`, but here there was just 1 operator that used this notation, so I decided to homogenize.

2024-02-14 09:41 UTC, njansson commented
> > I think that with dropping `Xh` we also dropped the connection/indication that the given coefficient is related to a certain function space
> 
> I know you like the `Xh`, but here there was just 1 operator that used this notation, so I decided to homogenize.

fair enough, also given that what `Xh` means in this context is unclear

2024-02-14 09:41 UTC, njansson approved these changes

2024-02-14 10:56 UTC, MartinKarp requested changes
Looks good!

2024-02-14 10:56 UTC, MartinKarp commented on src/math/operators.f90
> +  !! @param glb_n ?
```suggestion
  !! @param glb_n The global number of elements of 'x' across all MPI ranks. Be careful with overflow!
```

2024-02-18 14:00 UTC, timofeymukha commented
@MartinKarp You forgot to approve :-)

2024-02-19 12:48 UTC, merged