Feature/brinkman
ExtremeFLOW/neko pull request #1142
Opened 2024-02-16 07:51 UTC by timfelle

Introduction of a Brinkman forcing term.

The idea of this is to enforce regions of low permeability to block flow in certain regions.
Included is an example with a Stanford bunny placed in a square duct as a block of resistance.

Still some todo points, but wanted to open it up so I could start to get some feedback

- [ ] Documentation of the example and the source term in general, including an image or two.
- [ ] Expand to utilize point zones.

2024-02-16 14:52 UTC, timfelle commented
Do you have any preference on code structure? 

- I currently have implementation details in the source_terms/brinkman folder but i can move it to source_terms/bcknd if that makes it clearer.
- The AABB tree and could be moved to the mesh folder where the Octree also lives.

2024-02-20 10:47 UTC, njansson commented
Is this ready for review now?

2024-02-20 16:17 UTC, timfelle commented
Lets get it out there. Ill do seperate PR's for the other extensions to it as they are ready. This way others can get to experiment with it.

2024-02-23 06:40 UTC, timfelle commented
Ups, wrong branch

2024-02-25 12:39 UTC, timofeymukha requested changes

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/bcknd/cpu/brinkman_source_term_cpu.f90
> +  !> Computs the constant source term on the cpu.
```suggestion
  !> Computes the Brinkman source term on the cpu.
```

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/bcknd/device/brinkman_source_term_device.f90
> +  !> Computs the constant source term on the cpu.
```suggestion
  !> Computes the Brinkman source term on the device.
```

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/bcknd/cpu/filters_cpu.f90
> +    real(kind=rp), intent(in) :: x
@njansson Are `elemental` ok? I remember you mentioning compiler issues.

2024-02-25 12:39 UTC, timofeymukha commented on examples/immersed_bunny/readme.md
> +immersed boundary. A Stanford Buny model is placed in side a square duct and
```suggestion
immersed boundary. A Stanford Bunny model is placed in side a square duct and
```

2024-02-25 12:39 UTC, timofeymukha commented on examples/immersed_bunny/readme.md
> +changing the `distance_transform.value`, the value specify the width of the
```suggestion
changing the `distance_transform.value`, the value specifies the width of the
```

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/brinkman_source_term.f90
> +  !! array, with a value for each component of the source.
Copy-pasted :-)

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/brinkman_source_term.f90
> +  end subroutine brinkman_source_term_free
Nullify the brinkman pointer.

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/brinkman/aabb.f90
> +
Could you please copy-paste the "brief" part of the docstrings here as well?

2024-02-25 12:39 UTC, timofeymukha commented on src/source_terms/brinkman/aabb_tree.f90
> +    type(aabb_t) :: newRightaabb
A little unorthodox with camelCase names in Neko.

2024-02-25 12:42 UTC, timofeymukha commented
Not gonna lie, I did not check any of the algorithms in the tree and distance stuff. I guess in an ideal world, it would be nice to add unit tests for the aabb, the tree and the distance. Would double as a demonstrator for how these things work :). But perhaps in a later PR then, in case someone feels inspired.

Question, should the aabb go to "common"? Seems like a larger scope than just this source term, e.g. already discussed in context of probes.

2024-02-25 18:12 UTC, timfelle commented
> Not gonna lie, I did not check any of the algorithms in the tree and distance stuff. I guess in an ideal world, it would be nice to add unit tests for the aabb, the tree and the distance. Would double as a demonstrator for how these things work :). But perhaps in a later PR then, in case someone feels inspired.
> 
> Question, should the aabb go to "common"? Seems like a larger scope than just this source term, e.g. already discussed in context of probes.

Yes, i would like to write some tests for it. However, i have had some issues setting up my environment with the test library. But i am almost there, i think..

And sure, lets move the general stuff somewhere else. I think the signed distance stuff could go to math and the aabb_tree could go to mesh, since thats where the octree also lives.

2024-02-26 07:12 UTC, timfelle commented on src/source_terms/brinkman/aabb_tree.f90
> +    type(aabb_t) :: newRightaabb
Yea, not on purpose. It was a leftover from the original source code that i
overlooked when changing the others.

2024-02-26 08:08 UTC, timfelle commented
@njansson Any idea why the MacOS one fails here?
It seem that when I re-ran it different tests from the pfunit thing fails.

Additionally the runner seem upset about some MacOS version stuff:
 was built for newer 'macOS' version (13.6) than being linked (13.0)

2024-02-26 08:14 UTC, njansson commented on src/source_terms/bcknd/cpu/filters_cpu.f90
> +    real(kind=rp), intent(in) :: x
It's fine, but performance is a bit uncertain (if the compiler is bad...), so in short OK for this limited use

2024-02-26 08:16 UTC, njansson commented
> @njansson Any idea why the MacOS one fails here? It seem that when I re-ran it different tests from the pfunit thing fails.
> 
> Additionally the runner seem upset about some MacOS version stuff: was built for newer 'macOS' version (13.6) than being linked (13.0)

There seems to be some issue with the runner, it fails when trying to create some temp storage (according to the failed test logs)

2024-02-26 13:33 UTC, timofeymukha approved these changes

2024-02-26 13:33 UTC, merged