Feature/variable dt
ExtremeFLOW/neko pull request #1148
Opened 2024-02-20 14:54 UTC by Shiyu-Sandy-Du

This PR is re-issued following PR #1013. The branch in PR #1013 is too old and full of conflicts. This branch is built on most up-to-date develop-branch. In this branch, two things are modified:

1. variable time stepping uses a running average instead of an arithmetic average (to cope with sudden explosion of the cfl number)
2. lag fields are promoted to _scheme type (not just for pnpn)

Special acknowledge to @adperezm for setting up the architecture in PR#1013.

2024-02-22 15:34 UTC, Shiyu-Sandy-Du commented
restart is plausible but turns out to be wrong here. Work on time step info in chkp file is on-going.

2024-02-26 12:09 UTC, njansson requested changes

2024-02-26 12:09 UTC, njansson commented on src/simulation.f90
> +  !! @param dt current time step
```suggestion
  !> Set new dt based on cfl if requested
  !! @param dt current time step
```

2024-02-26 12:09 UTC, njansson commented on src/simulation.f90
> +       !! u for the last time step
```suggestion
```

2024-02-26 12:09 UTC, njansson commented on src/simulation.f90
> +
```suggestion

```

2024-02-26 12:09 UTC, njansson commented on src/simulation.f90
> +       write(log_buf,'(A, E15.7)') 'cfl :  ', set_cfl
```suggestion
       write(log_buf,'(A, E15.7)') 'CFL :  ', set_cfl
```

2024-02-26 12:09 UTC, njansson commented on src/simulation.f90
> +
```suggestion
    call profiler_start
    cfl = C%fluid%compute_cfl(C%dt)
    start_time_org = MPI_WTIME()

    do while (t .lt. C%end_time .and. (.not. jobctrl_time_limit()))
       call profiler_start_region('Time-Step')
       tstep = tstep + 1
       start_time = MPI_WTIME()
       if (dt_last_change .eq. 0) then
          cfl_avrg = cfl
       end
       call simulation_setdt(C%dt, C%params, cfl, cfl_avrg, dt_last_change, tstep)
       !calculate the cfl after the possibly varied dt
       cfl = C%fluid%compute_cfl(C%dt)

```

2024-02-26 12:45 UTC, njansson approved these changes

2024-02-26 13:48 UTC, timofeymukha commented
Please update case-file.md with the new options.

2024-02-26 14:03 UTC, timofeymukha requested changes

2024-02-26 14:03 UTC, timofeymukha commented on src/simulation.f90
> +                                    min_update_frequency, 1)
I'm perhaps confused, but isn't this the maximum frequency? This is expressed in the number of timesteps, right? So if I put to, it will update at a max once per 2 timesteps and not with a higher frequency.

2024-02-26 14:12 UTC, Shiyu-Sandy-Du commented on src/simulation.f90
> +                                    min_update_frequency, 1)
You point out the problem here. So it should be named "min_update_time_steps" instead

2024-02-26 14:16 UTC, Shiyu-Sandy-Du commented on src/simulation.f90
> +                                    min_update_frequency, 1)
would be a good idea

2024-02-26 14:17 UTC, Shiyu-Sandy-Du commented on src/simulation.f90
> +                                    min_update_frequency, 1)
shall I issue it in this PR?

2024-02-26 14:17 UTC, timofeymukha commented on src/simulation.f90
> +                                    min_update_frequency, 1)
yes, just update the branch and the PR will use the latest commit automatically.

2024-02-26 14:40 UTC, timofeymukha commented on src/simulation.f90
> +                                    min_update_frequency, 1)
These are always a horror to name. I guess one can contract time_steps to tsteps, because we use that for "output_control" as well.

2024-02-28 07:40 UTC, timfelle commented
It seems you are missing an update to the .depends, which is why the tests are failing.

2024-02-28 08:00 UTC, Shiyu-Sandy-Du commented
> It seems you are missing an update to the .depends, which is why the tests are failing.

Yes it's the issue. now it's fixed.

2024-02-28 09:04 UTC, Shiyu-Sandy-Du commented
> Please update case-file.md with the new options.

Done

2024-03-04 09:47 UTC, timofeymukha approved these changes

2024-03-04 09:47 UTC, merged