TS wave test examples
ExtremeFLOW/neko pull request #1159
Opened 2024-02-28 12:46 UTC by Shiyu-Sandy-Du

This case is used as an example case for variable dt. Please merge it after feature/variable_dt is merged.

2024-02-28 14:20 UTC, njansson commented on examples/TS_channel/README.md
> +#Tollmien-Schlichting (TS) wave test in channel flow.
```suggestion
## Tollmien-Schlichting (TS) wave test in channel flow.
```

2024-02-28 14:20 UTC, njansson approved these changes

2024-03-01 14:54 UTC, MartinKarp requested changes
Really nice! Check for indentation and also I think it might be good with a few comments in the code.

2024-03-04 09:12 UTC, timofeymukha commented on examples/TS_channel/TS_channel.f90
> +  function inArray(y,y_list) result(isIn)
use _ in names instead of camelCase

2024-03-06 13:15 UTC, MartinKarp commented
@Shiyu-Sandy-Du do you think you will get a review for @pschlatt1? Otherwise I think we can merge it in.

2024-03-06 13:19 UTC, njansson commented
> @Shiyu-Sandy-Du do you think you will get a review from @pschlatt1? Otherwise I think we can merge it in.

We have discussed thus offline, so I think we can merge

2024-03-06 13:19 UTC, merged