Add support for hex objects
ExtremeFLOW/neko pull request #1163
Opened 2024-03-02 18:08 UTC by njansson

2024-03-02 20:08 UTC, timofeymukha commented on src/mesh/search_tree/aabb.f90
> +  !! avoid numerical issues when the hexahedron itself it axis
```suggestion
  !! avoid numerical issues when the hexahedron itself is axis
```

2024-03-04 07:58 UTC, timfelle requested changes

2024-03-04 07:58 UTC, timfelle commented on src/mesh/search_tree/aabb.f90
> +  !! aligned.
Padding was moved to the get_aabb subroutine. The comment lingered it seems. Probably should also remove it from the triangle type.
```suggestion
  !! @details This function calculates the aabb of a hexahedron.
```

2024-03-04 07:58 UTC, timfelle commented on src/mesh/search_tree/aabb.f90
> +
Formatting
```suggestion
       box = get_aabb_triangle(object)
      type is (hex_t)
       box = get_aabb_hexahedron(object)

```

2024-03-04 07:58 UTC, timfelle reviewed
Could this be implemented for the generic element_t instead to avoid having to implement it for all variants?

2024-03-04 08:02 UTC, njansson commented
> Could this be implemented for the generic element_t instead to avoid having to implement it for all variants?

Not sure, max can't handle array ranges afaik, which could make it difficult for generic element

2024-03-04 08:06 UTC, timfelle reviewed
> > Could this be implemented for the generic element_t instead to avoid having to implement it for all variants?

> Not sure, max can't handle array ranges afaik, which could make it difficult for generic element  

Right, but how would it be different? would it not just be doable in a loop through the entries of element_t%pts like we both did with tri_t and hex_t? Except we both hardcoded the loops, and used the trick that max does accept abitrary numbers of inputs and does the looping for you.

2024-03-04 08:44 UTC, njansson commented
> > > Could this be implemented for the generic element_t instead to avoid having to implement it for all variants?
> 
> > Not sure, max can't handle array ranges afaik, which could make it difficult for generic element
> 
> Right, but how would it be different? would it not just be doable in a loop through the entries of element_t%pts like we both did with tri_t and hex_t? Except we both hardcoded the loops, and used the trick that max does accept abitrary numbers of inputs and does the looping for you.

True, we could probably do a loop, over the pts array, and do several max/min checks

2024-03-04 08:46 UTC, timfelle commented
> > > > Could this be implemented for the generic element_t instead to avoid having to implement it for all variants?
> > 
> > 
> > > Not sure, max can't handle array ranges afaik, which could make it difficult for generic element
> > 
> > 
> > Right, but how would it be different? would it not just be doable in a loop through the entries of element_t%pts like we both did with tri_t and hex_t? Except we both hardcoded the loops, and used the trick that max does accept abitrary numbers of inputs and does the looping for you.
> 
> True, we could probably do a loop, over the pts array, and do several max/min checks

I am not exactly sure how the overload resolution would function in fortran in that case though. Would tri_t and hex_t trigger the element_t function since they are extending it or how would that work?

2024-03-04 08:52 UTC, njansson commented
> > > > > Could this be implemented for the generic element_t instead to avoid having to implement it for all variants?
> > > 
> > > 
> > > > Not sure, max can't handle array ranges afaik, which could make it difficult for generic element
> > > 
> > > 
> > > Right, but how would it be different? would it not just be doable in a loop through the entries of element_t%pts like we both did with tri_t and hex_t? Except we both hardcoded the loops, and used the trick that max does accept abitrary numbers of inputs and does the looping for you.
> > 
> > 
> > True, we could probably do a loop, over the pts array, and do several max/min checks
> 
> I am not exactly sure how the overload resolution would function in fortran in that case though. Would tri_t and hex_t trigger the element_t function since they are extending it or how would that work?

Yes, as long as you access parts define din the base type it works without a select block

2024-03-18 09:29 UTC, timfelle commented
So, the point_t is based on strictly double precision while the aabb_t uses the rp type to define the precision. I guess I need to be more considerate when setting up the precision of stuff. Do we intend to only use the rp one to define fields and phycis but in general keeping goemetric objects on full double precision?

2024-03-18 10:21 UTC, timofeymukha commented
> So, the point_t is based on strictly double precision while the aabb_t uses the rp type to define the precision. I guess I need to be more considerate when setting up the precision of stuff. Do we intend to only use the rp one to define fields and phycis but in general keeping goemetric objects on full double precision?

Could be wrong, but I think that was the idea.

2024-03-19 09:33 UTC, njansson commented
> > So, the point_t is based on strictly double precision while the aabb_t uses the rp type to define the precision. I guess I need to be more considerate when setting up the precision of stuff. Do we intend to only use the rp one to define fields and phycis but in general keeping goemetric objects on full double precision?
> 
> Could be wrong, but I think that was the idea.

The original idea was to make sure that the mesh is always in double, hence point being double. 

For the aabb tree, don't we need the higher precision as well?

2024-03-19 10:37 UTC, timfelle commented
> > > So, the point_t is based on strictly double precision while the aabb_t uses the rp type to define the precision. I guess I need to be more considerate when setting up the precision of stuff. Do we intend to only use the rp one to define fields and phycis but in general keeping goemetric objects on full double precision?
> > 
> > 
> > Could be wrong, but I think that was the idea.
> 
> The original idea was to make sure that the mesh is always in double, hence point being double.
> 
> For the aabb tree, don't we need the higher precision as well?

Yes we do. I had just been lazy and set everything to kind=rp, since locally i always run in double precision. I will make sure to think more about it going forward.

2024-03-20 06:53 UTC, timfelle approved these changes

2024-03-20 07:03 UTC, timofeymukha commented on src/common/json_utils.f90
> +  !! @value value The variable to be populated with the retrieved parameter.
is `@value` something that exists, or did I accidentally introduce it, and now it proliferates by copy-paste :-)?

2024-03-20 07:05 UTC, timfelle commented on src/common/json_utils.f90
> +  !! @value value The variable to be populated with the retrieved parameter.
It does not. Ill fix it

2024-03-20 08:37 UTC, merged