Refactor pc_jacobi (CPU) to allow for vectorisation
ExtremeFLOW/neko pull request #1171
Opened 2024-03-10 08:32 UTC by njansson

2024-03-20 09:30 UTC, MartinKarp commented
Nice with vectorization. However, this function call is not necessary unless G has changed from the previous time step. 

Hence I guess adding a check for that instead would probably be good.

2024-03-20 09:31 UTC, MartinKarp requested changes

2024-03-20 09:31 UTC, MartinKarp commented on src/krylov/bcknd/cpu/pc_jacobi.f90
>    subroutine jacobi_update(this)
Does not update anything unless G has changed.

2024-03-20 09:33 UTC, njansson commented
> Nice with vectorization. However, this function call is not necessary unless G has changed from the previous time step.
> 
> Hence I guess adding a check for that instead would probably be good.

True, but should we have this check here, or somewhere else? I guess we can have a flag in `coef` to flag if `G` has been updated, and do a quick return if the flag is `.false.`

2024-03-20 09:34 UTC, njansson commented on src/krylov/bcknd/cpu/pc_jacobi.f90
> +  !> Update Jacobi preconditioner
```suggestion
  !> Update Jacobi preconditioner if the geometry G has changed
```

2024-03-20 09:35 UTC, MartinKarp commented
Pehaps, another option would b eto point %update to some do_nothing function and only call this one upon init (if we wanna assume that G does not change).

2024-03-20 09:42 UTC, njansson commented
> Pehaps, another option would b eto point %update to some do_nothing function and only call this one upon init (if we wanna assume that G does not change).


If the geometry is changing between stationary and moving, I think the best option would be an if statement instead of swapping function pointers all the time?

2024-03-20 11:08 UTC, timofeymukha approved these changes

2024-03-20 11:09 UTC, timofeymukha commented
I'll let you guys decide on the logic. The refactor per se is perfectly fine I guess.

2024-03-22 08:11 UTC, njansson commented
My suggestion is to merge this, and work out the other points in another pr, I've some ideas how it can be done

2024-04-04 12:31 UTC, MartinKarp approved these changes

2024-04-04 12:31 UTC, merged