Feature/implicit forcing
ExtremeFLOW/neko pull request #1177
Opened 2024-03-15 16:54 UTC by gloopydoop

Sorry, first pull request, please point out where documentation should go.

For some applications (immersed boundary methods, sponge regions, generation of FST etc) it is common to have a forcing term that is linearly proportional to the velocity, we denote this as f = \chi * u, where \chi is a scalar field.

Imposing this in user_f results in an explicit formulation where f = \chi * u^(n) that can lead to stability issues for large \chi.

Here we impose an implicit formulation f = \chi * u^(n+1) 

Predicted problems:
 - I'm 99% sure if \chi is defined on the boundary, we'll have to adjust the pressure boundary conditions.
 - Nothing has been tested on GPU's etc yet
 - not a lot of testing has gone into this, I'm only pull requesting so that it can be discussed

2024-03-15 17:25 UTC, timofeymukha commented on src/common/user_intf.f90
> +
This should throw an error, as all the other dummies.

2024-03-17 14:48 UTC, MartinKarp commented on src/common/user_intf.f90
> +
Not all dummies I guess, some are "do nothing" but will not return an error. Like dummy_user_check

2024-03-17 15:07 UTC, MartinKarp requested changes
I think this is a good feature. One thing I guess as Tim also mentioned is how we want to treat the brinkman term when there is none. Right now it calls a do-nothing routine, but technically we add a vector of zero each time. If we moved out setting h1,h2 outside of computing the residual for the velocity this might be possible to do more elegantly.

2024-03-17 15:07 UTC, MartinKarp commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +       c_Xh%h2(i,1,1,1) = rho * (bd / dt) + chi%x(i,1,1,1)
This is nice and will work I think, but maybe we should also consider moving h1, h2 to the Ax_helm type @njansson @timofeymukha . They do not really belong in coef, but are directly linked to the Helmholtz equation. Maybe something we could issue another PR for?

2024-03-17 15:07 UTC, MartinKarp commented on src/fluid/fluid_pnpn.f90
> +    ! type(field_t), intent(inout) :: chi_fam
Should this be commented or?

2024-03-17 15:07 UTC, MartinKarp commented on src/fluid/fluid_pnpn.f90
> +      call this%userbrinkman%compute(t)
I guess it does not need to be user, I forsee a lot could be captured by typical forcings in the json file. Similar to constant forcing.

2024-03-17 15:07 UTC, MartinKarp commented on src/fluid/fluid_pnpn.f90
> +      call this%userbrinkman%compute(t)
This is just a naming suggestion

2024-03-17 15:15 UTC, timofeymukha commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +       c_Xh%h2(i,1,1,1) = rho * (bd / dt) + chi%x(i,1,1,1)
I think the idea of using a global h1 and h2 that sits somewhere and gets overwritten with right values just prior to a call to an axhelm is unnecessary. I would say we can just pass h1 and h2 to axhelm's compute routine as arguments, or is there some reason not to do that? But I agree that if we should dedicate a components for this in a type, it should be axhelm, and not coef.

2024-03-17 15:18 UTC, MartinKarp commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +       c_Xh%h2(i,1,1,1) = rho * (bd / dt) + chi%x(i,1,1,1)
If we do that the idea of passing something that computes a linear operator Ax to the ksp solvers will kind of not work as different matrices will have different inputs. Because of that I was leaning a bit towards putting it directly in Ax.

2024-03-18 05:07 UTC, njansson commented on src/fluid/fluid_pnpn.f90
> +      call this%userbrinkman%compute(t)
Agree, can't this be put in the forcing? Same with chi, would be nice to hide these case specific variables under some object/abstraction

2024-03-18 07:22 UTC, timofeymukha commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +       c_Xh%h2(i,1,1,1) = rho * (bd / dt) + chi%x(i,1,1,1)
I see, that makes sense.

2024-03-18 10:27 UTC, gloopydoop commented on YOFAM/README.md
> +If one wants to change the mesh and play around, please do so, by generating a new mesh with genmeshbox.
none of this example should be in the main code, it was just the case I was using to test the implicit Brinkman term.
I would envision that the immersed_bunny or something similar would be extended as an example.

2024-03-21 10:04 UTC, timfelle requested changes
Any chance you could go through and cleanup the places where stuff is no longer changed? 
It is kinda difficult to know what is still needed and what is not. Are you still using the changes in user_intf.f90 for instance?

2026-07-08 15:34 UTC, closed without merging