Explicitly list all types in factories for friendly error messages
ExtremeFLOW/neko pull request #1204
Opened 2024-03-26 10:13 UTC by timofeymukha

This is a suggestion to enhance all our json-based factories with a KNOWN_TYPES list with the names of all the types the factory can create. We can then output this list when an unknown type is provided by the user in the case file.

This has proven to be a nice way of exploring what is available in the code in e.g. OpenFOAM. One intentionally puts a jibberish string in the "type" just to see the options. The minus is a bit of extra burden on the developers, but I think it is tolerable.

So far "don't merge" as I will extend it to all factories upon approval.

Question: is the string concatenation routine ok? Will it just reallocate the result to the necessary size as we are concating in new items to it?

2024-03-26 19:29 UTC, njansson commented on src/simulation_components/simulation_component_factory.f90
> +
Is the extra `[character...` necessary?

In other cases it works without, for example:  https://gitlab.com/ExtremeFLOW/neko_opr/-/blob/master/driver.f90?ref_type=heads#L19

```suggestion
  character(len=20) :: KNOWN_TYPES(5) = [&
     "vorticity", &
     "lambda2", &
     "probes", &
     "les_model", &
     "field_writer"]

```

2024-03-26 21:08 UTC, timofeymukha commented on src/simulation_components/simulation_component_factory.f90
> +
Interesting, in my case it would crash saying the strings are of different lengths. Can it be that the example you link to works because you pad all the stings to the same length with spaces?

2024-03-27 16:12 UTC, timofeymukha commented
Besides for the `character` thing, are we in agreement for extending this to other types?

2024-04-02 08:12 UTC, timfelle reviewed
> Besides for the `character` thing, are we in agreement for extending this to other types? 

It quite a good idea to have this. One think I thougfht of was, what is the maximal string length and could that be an issue?

2024-06-17 10:48 UTC, timofeymukha commented
@njansson @timfelle @MartinKarp The PR is now open for review. In addtion to adding the KNOWN_TYPES, in indroduced the following name convention:
- The name of the variable for the object being allocated is `object`
- The name of the variable for the name of the type, (extracted from the json or passed to the factory) is `type_name`

2024-06-17 10:50 UTC, njansson commented
There's several changes in the BSD license text, probably from some refactoring, which needs to be reverted

2024-06-17 10:52 UTC, njansson requested changes
BSD license text shall not be altered

2024-06-17 10:57 UTC, timofeymukha commented
> BSD license text shall not be altered

I knew using %s/ will bite me in the butt :-)

2024-06-17 11:06 UTC, timfelle commented on src/krylov/krylov_fctry.f90
Why are we not just calling `obejct%free()`

2024-06-17 11:09 UTC, timfelle commented on src/krylov/krylov_fctry.f90
>      end if
Is there any good reason we do this massive init case stuff. Can't we just do
init, without selecting the type? The type is detected through the allocation
stuff above.

2024-06-17 11:09 UTC, timofeymukha commented on src/krylov/krylov_fctry.f90
@njansson ?

2024-06-17 11:11 UTC, timfelle commented on src/krylov/precon_fctry.f90
Maybe move this to the else statement, since we dont use it before then

2024-06-17 11:11 UTC, timofeymukha commented on src/krylov/precon_fctry.f90
True

2024-06-17 11:18 UTC, timfelle commented on src/krylov/krylov_fctry.f90
We do it in stuff like the simcomps

2024-06-17 11:21 UTC, timfelle commented on src/les/les_model_fctry.f90
> +!   * Neither the type_name of the authors nor the names of its
```suggestion
!   * Neither the name of the authors nor the names of its
```

2024-06-17 12:09 UTC, njansson commented on src/krylov/krylov_fctry.f90
Should work, but we had issues with compilers in the past

2024-06-17 12:09 UTC, njansson commented on src/krylov/krylov_fctry.f90
>      end if
Same here, should work, but we had issues with compilers in the past.

2024-06-17 12:11 UTC, timfelle commented on src/krylov/krylov_fctry.f90
Interesting, which compilers did you try out, and did you find out what went wrong? From what i understand it should be functional in terms of the Fortran language. So is it just missing features in some of the compilers?

2024-06-17 12:12 UTC, njansson commented on src/krylov/krylov_fctry.f90
>      end if
Fully agree, but given the experience, not too keen on introducing these PITA compiler issues at this time

2024-06-17 12:14 UTC, timofeymukha commented
@njansson NB: ifx just got fixed by commenting out the `private` statements I added to the precon and ksp factory modules. I think we should try to clean up the `use` statements with respect to these types, there seems to be a lot of implicit propagation going on via just `using` the factory module.

2024-06-17 12:16 UTC, timofeymukha commented on src/krylov/krylov_fctry.f90
>      end if
Let us at this point add a comment for why it is there, and that we should at some point see if we can get away with removing this stuff.

2024-06-17 12:17 UTC, njansson commented
> @njansson NB: ifx just got fixed by commenting out the `private` statements I added to the precon and ksp factory modules. I think we should try to clean up the `use` statements with respect to these types, there seems to be a lot of implicit propagation going on via just `using` the factory module.

Great, but what a mess (sigh). I through that we had cleaned these in the past.

2024-06-17 12:21 UTC, timfelle commented on src/krylov/krylov_fctry.f90
>      end if
Sure, I fully support attempting that kind of change in a separate PR with rigorous testing if we already know there might be issues. Its not relevant for the scope of this PR anyway. 

Maybe we should add an issue to track this?

2024-06-17 12:21 UTC, timfelle commented on src/krylov/krylov_fctry.f90
> I think more like bugs than missing features :-)

Oh the joy 😹

2024-06-17 12:22 UTC, timofeymukha commented
> > @njansson NB: ifx just got fixed by commenting out the `private` statements I added to the precon and ksp factory modules. I think we should try to clean up the `use` statements with respect to these types, there seems to be a lot of implicit propagation going on via just `using` the factory module.
> 
> Great, but what a mess (sigh). I through that we had cleaned these in the past.

We did to some extent, but not thoroughly enough perhaps :-). Although, for individual ksp types the `use` seems to be pretty damn clean, almost everything behind `only.`

2024-06-17 12:25 UTC, timofeymukha commented on src/krylov/krylov_fctry.f90
I mean the death of ifx here is a good example :-). Myabe something on our side, but then why don't all the other compilers complain. And anyway, ifx just segfaulted instead of complaining about the code ^^

2024-06-17 12:32 UTC, timofeymukha commented on src/krylov/krylov_fctry.f90
>      end if
Done

2024-06-18 14:20 UTC, timfelle approved these changes

2024-06-18 14:20 UTC, timfelle commented on src/.depends
I updated it

2024-06-18 18:38 UTC, njansson approved these changes

2024-06-18 18:38 UTC, merged