Feature/stress formulation, smagorinsky model
ExtremeFLOW/neko pull request #1250
Opened 2024-04-23 08:45 UTC by Shiyu-Sandy-Du

Classical Smagorinsky model is added.

2024-04-23 09:17 UTC, timofeymukha requested changes

2024-04-23 09:17 UTC, timofeymukha commented on src/wall_models/wall_model_fctry.f90
>    use json_module, only : json_file
This file should not be modified for this. I guess it's contents are wrong now, as it is a copy for the les factory, instead of a wall model factory. I probably forgot to push an update for it, sorry.

2024-04-23 09:17 UTC, timofeymukha commented on src/les/bcknd/cpu/smagorinsky_cpu.f90
> +    call dudxyz (a33%x, w%x, coef%drdz, coef%dsdz, coef%dtdz, coef)
I think we can use the operator for computing the strain rate in operators.f90?

2024-04-23 09:17 UTC, timofeymukha commented on src/les/bcknd/cpu/vreman_cpu.f90
>         end do
Yeah, I see it now again, looking at the paper, good catch!

2024-04-23 09:28 UTC, Shiyu-Sandy-Du commented on src/les/bcknd/cpu/smagorinsky_cpu.f90
> +    call dudxyz (a33%x, w%x, coef%drdz, coef%dsdz, coef%dtdz, coef)
Yes maybe better. The code would look concise and we only need to allocate 6 fields instead of 9

2024-04-23 09:46 UTC, Shiyu-Sandy-Du commented on src/wall_models/wall_model_fctry.f90
>    use json_module, only : json_file
Oh yes exactly. Then how should I deal with this wrong file here?

2024-04-23 09:54 UTC, timofeymukha commented on src/wall_models/wall_model_fctry.f90
>    use json_module, only : json_file
Just undo all changes to it so it is no longer in the PR.

2024-04-24 09:07 UTC, Shiyu-Sandy-Du commented on src/les/bcknd/cpu/smagorinsky_cpu.f90
> +    real(kind=rp) :: s_abs
the value is double of the tensor here, so s11 etc. might be a bit confusing.

2024-04-24 09:13 UTC, timofeymukha commented on src/les/bcknd/cpu/smagorinsky_cpu.f90
> +    real(kind=rp) :: s_abs
Oh, I see what you mean, that's a bit tricky. We are not missing an extra 0.5 in the calculation of s_abs (since we are squaring the s_ij componenta), are we?

2024-04-24 09:18 UTC, Shiyu-Sandy-Du commented on src/les/bcknd/cpu/smagorinsky_cpu.f90
> +    real(kind=rp) :: s_abs
I make the compensation when calculating s_abs, so it's correct now.

2024-04-24 09:20 UTC, timofeymukha commented on src/les/bcknd/cpu/smagorinsky_cpu.f90
> +    real(kind=rp) :: s_abs
Alright I trust you :D

2024-04-24 09:20 UTC, merged