Expand ax_helm to allow a coupled compute
ExtremeFLOW/neko pull request #1252
Opened 2024-04-24 09:47 UTC by timofeymukha

So here is an initial proposition for adding an interface to ax, which works on 3 vectors in a coupled manner. After our discussions, this follows the easiest path, which does not directly generalize to a different number of vectors, but perhaps this is OK for no to get the stress formulation in. The ax_helm factory now takes a parameter "formulation", which can be either "simple", meaning the simplified stress tensor, for "full", for the full tensor. Naturally, the existing fluid scheme only uses the simple one. 

The idea with this PR is mainly to settling on how to introduce the coupled ax_helm, so that we can start putting in GPU kernels into develop.

2024-04-24 14:50 UTC, timofeymukha commented
Is it possible to figure out what flint is complaining about?

2024-04-24 16:52 UTC, njansson commented on src/math/ax.f90
> +     procedure(ax_compute3), pass(this), deferred :: compute3
How about adding a generic compute here, such that we can keep it consistent within solvers etc?

2024-05-03 17:23 UTC, timofeymukha commented on src/math/ax.f90
> +     procedure(ax_compute3), pass(this), deferred :: compute3
@njansson There is an issue. We can have a generic interface, but generic resolution relies on the shape of the arrays of the dummy arguments. So, we cannot do the usual trick of sending a 1D array to a dummy argument which is 4D. The compiler will say that there is no implementation of the generic found for the type of arguments passed.

2024-05-03 17:23 UTC, timofeymukha commented on src/math/ax.f90
> +     procedure(ax_compute3), pass(this), deferred :: compute3
(and the solver types do use the trick)

2024-05-21 12:33 UTC, njansson reviewed
Nice, but can we find a better name instead of `simple` ?

2024-05-27 15:32 UTC, njansson commented on src/math/ax.f90
> +  end interface
I would suggest we call this `_vector` to be consistent with similar interface in Neko

2024-05-28 12:39 UTC, njansson commented on src/math/bcknd/cpu/ax_helm_cpu.f90
> +! Copyright (c) 2024, The Neko Authors
```suggestion
! Copyright (c) 2021-2024, The Neko Authors
```
There isn't enough changes I would say that warrant to see the file as new

2024-05-28 12:39 UTC, njansson commented on src/math/ax_helm_full.f90
If this is the file from the stress branch, it's a bit bad to loose the commit history for it by trying to reinvent it here.

2024-05-28 12:39 UTC, njansson commented on flinter_rc.yml
> -    - ','
I  would argue that we still want to check ',' as a ponctuation

2024-05-28 12:39 UTC, njansson commented on src/math/ax_helm_fctry.f90
> +      allocate(ax_helm_full_cpu_t::Ax)
Were need to thrown an error here unless we're on a backend that can use the CPU part

2024-05-28 12:44 UTC, timofeymukha commented on flinter_rc.yml
> -    - ','
We can do that, but then we need to go through the codebase and make changes to comply with that, mainly in array indexing. I can start with the stuff in axhelm_full here, but it is the tip of an iceberg.

2024-05-28 12:46 UTC, timofeymukha commented on src/math/ax_helm_full.f90
Yeah, it is. I'm not sure if there is a way to make git see the connection, though. Do you know how one would do that?

2024-05-28 12:58 UTC, timofeymukha commented on flinter_rc.yml
> -    - ','
Not entirely convinced spaces actually help readability. Somehow, I find it clearer to see the mathematical expression when the stuff the math operators work on is condensed to a list of symbols with no spaces. But could be expression-dependent @timfelle what do you reckon?

```fortran
          u1 = wur(i, 1, 1) * drdx(i, 1, 1, e) + wus(i, 1, 1) * dsdx(i, 1, 1, e) &
                                               + wut(i, 1, 1) * dtdx(i, 1, 1, e)
          u2 = wur(i, 1, 1) * drdy(i, 1, 1, e) + wus(i, 1, 1) * dsdy(i, 1, 1, e) &
                                               + wut(i, 1, 1) * dtdy(i, 1, 1, e)
          u3 = wur(i, 1, 1) * drdz(i, 1, 1, e) + wus(i, 1, 1) * dsdz(i, 1, 1, e) &
                                               + wut(i, 1, 1) * dtdz(i, 1, 1, e)
```
contra
```fortran
          w1 = wwr(i,1,1) * drdx(i,1,1,e) + wws(i,1,1) * dsdx(i,1,1,e) &
                                          + wwt(i,1,1) * dtdx(i,1,1,e)
          w2 = wwr(i,1,1) * drdy(i,1,1,e) + wws(i,1,1) * dsdy(i,1,1,e) &
                                          + wwt(i,1,1) * dtdy(i,1,1,e)
          w3 = wwr(i,1,1) * drdz(i,1,1,e) + wws(i,1,1) * dsdz(i,1,1,e) &
                                          + wwt(i,1,1) * dtdz(i,1,1,e)
```

2024-05-28 13:39 UTC, njansson commented on flinter_rc.yml
> -    - ','
True, I tend to agree (and not be consistent my self) with having it condense for these kind of operations, and have it "fluffy" for function calls and other definitions.

2024-05-28 13:46 UTC, timofeymukha commented on flinter_rc.yml
> -    - ','
Can we tweak the flint rule to ignore the specific case of array indexing?

2024-05-28 16:17 UTC, dauptaia commented on flinter_rc.yml
> -    - ','
I am afraid It will be difficult within Flint current implementation, (not aware of the array indexing) sorry.

I will keep this feature in mind for our current project (tucan) which will replace flinter in the long. term and is able to contextualize the analysis.

2024-05-28 16:19 UTC, timofeymukha commented on flinter_rc.yml
> -    - ','
Thank you for the prompt reply!

2024-05-29 06:13 UTC, timfelle commented on flinter_rc.yml
> -    - ','
Yes it is really a tough one. In my opinion its not great either way. 4 way indexing is never pretty and as dauptaia mentioned, there is no distinction between function calls and array indexing. And i am still not a fan of using the indexing directly to flatten the arrays, but that have got performance implications so its important.

So yes as @njansson mention, there are no good solution, so I only plan on being consistent.

2024-05-29 06:14 UTC, njansson commented on src/math/ax_helm_full.f90
git will not see the connection since it's a new file. Either we just have a place holder in this pr, merge the stress branch and move that formulation here (`git mv`) to preserve history

2024-05-29 06:18 UTC, timfelle commented on src/math/ax_helm_full.f90
One solution could be to start a branch on the stress branch, and revert all the changes not related to axhelm and then merge that branch into the branch of this PR. that way the history is preserved. 

But you have a commit reverting a lot of changes. The PR should sort that out as it looks for files with differences between the base and the PR not the accumulated files changes by the commits.

2024-05-29 06:21 UTC, njansson commented on flinter_rc.yml
> -    - ','
I think that will break flint?

2024-05-29 06:35 UTC, timfelle requested changes
In general looks good.

A general notes:
- Update the copyright now that we are touching these files.

2024-05-29 06:35 UTC, timfelle commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +
```suggestion
```

2024-05-29 06:35 UTC, timfelle commented on src/fluid/fluid_pnpn.f90
> +    call ax_helm_factory(this%ax, full_formulation=.false.)
```suggestion
    call ax_helm_factory(this%ax, full_formulation = .false.)
```

2024-05-29 06:35 UTC, timfelle commented on src/krylov/pc_hsmg.f90
> +    call ax_helm_factory(this%ax, full_formulation=.false.)
```suggestion
    call ax_helm_factory(this%ax, full_formulation = .false.)
```

2024-05-29 06:35 UTC, timfelle commented on src/math/ax.f90
> +  !! @param Xh Function space \f$ X_h \f$.
We are missing some parameter descriptions here.

2024-05-29 06:35 UTC, timfelle commented on flinter_rc.yml
> -    - ','
It should be fine, its just a list of regex rules being checked through python. I'll try it out and make a PR if it works.

2024-05-29 06:35 UTC, timfelle commented on src/math/ax_helm.f90
> +  subroutine ax_helm_compute_vector(this, au, av, aw, u, v, w, coef, msh, Xh)
Add doxygen string

2024-05-29 06:35 UTC, timfelle commented on src/scalar/scalar_pnpn.f90
> +    call ax_helm_factory(this%ax, full_formulation=.false.)
```suggestion
    call ax_helm_factory(this%ax, full_formulation = .false.)
```

2024-05-29 07:30 UTC, timfelle commented on flinter_rc.yml
> -    - ','
I have found a way to make flint happy about ,1 alone and not other things

2024-05-29 07:32 UTC, njansson commented on flinter_rc.yml
> -    - ','
> I have found a way to make flint happy about ,1 alone and not other things

Spill the beans!

2024-05-29 07:34 UTC, timfelle commented on flinter_rc.yml
> -    - ','
> > I have found a way to make flint happy about ,1 alone and not other things
> 
> Spill the beans!

Do the white-space manually `(\w)` expands to `([a-zA-Z0-1_])` so we can just tell it to match against `([a-zA-Z02-9_])` instead 😅

2024-05-29 07:37 UTC, njansson commented on flinter_rc.yml
> -    - ','
But that would still give poor scoring for `(i,1,1,1)` due to `i` right?

2024-05-29 07:39 UTC, timfelle commented on flinter_rc.yml
> -    - ','
No, i is before the `,` not after. it would degrade scores of `(i,1,1,e)` based on the `e`.

2024-05-29 07:49 UTC, dauptaia commented on flinter_rc.yml
> -    - ','
OMG, I created monsters...😅

2024-05-29 07:54 UTC, timfelle commented on flinter_rc.yml
> -    - ','
> OMG, I created monsters...😅

Yep 🤣 

Even better!!! `(,)(\w){2,}`
Allows `,` trailed by a single non word character. But disallows multi character words!!

2024-05-29 07:54 UTC, njansson commented on flinter_rc.yml
> -    - ','
> No, i is before the `,` not after. it would degrade scores of `(i,1,1,e)` based on the `e`.
> 
> Also any number starting with 1 such as 10 and 11 😅

Should be fine (^-^)v, since we only use 1, for indexing, unless we have a loop variable

2024-05-29 07:54 UTC, njansson commented on flinter_rc.yml
> -    - ','
> > OMG, I created monsters...😅
> 
> Yep 🤣
> 
> Even better!!! `(,)(\w){2,}` Allows `,` trailed by a single non word character. But disallows multi character words!!

🍻

2024-05-29 10:59 UTC, timofeymukha commented on src/math/ax_helm_full.f90
OK, let's go for the placeholder options, undoing stuff seems complicated. :-)

2024-05-29 11:13 UTC, njansson commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +
Should this comment be removed?

2024-05-29 11:52 UTC, njansson approved these changes
Let's get it in and such that we can iron out any issues together with the merge of the stress branch

2024-05-29 12:19 UTC, njansson commented on src/fluid/bcknd/cpu/pnpn_res_cpu.f90
> +
Ok, let's fix that later once the stress branch is in

2024-05-29 13:11 UTC, merged