README with json fortran
ExtremeFLOW/neko pull request #1254
Opened 2024-04-25 20:45 UTC by MartinKarp

To make life easier, removed some more advanced options from the readme and added how to compile json-fortran. 

Easier than looking into https://github.com/ExtremeFLOW/neko/blob/develop/.github/workflows/develop.yml for how to compile as I am doing now.

Not perfect, but I think this would be a significant improvement.

2024-04-25 21:44 UTC, timofeymukha commented on README.md
> +Documentation for Neko is available at https://neko.cfd and most things related to the code, cases, and different features are described there. The documentation is always improving, in large part du
Maybe "discusson" instead of issues, since this is what we would like, right? Could make it a clickable link as well.

2024-04-25 21:45 UTC, timofeymukha commented
very nice!

2024-04-26 06:03 UTC, MartinKarp commented on README.md
> +Documentation for Neko is available at https://neko.cfd and most things related to the code, cases, and different features are described there. The documentation is always improving, in large part du
Yeah, thats better, also maybe I should write Pull requests instead of PRs since its for those new to the code.

2024-04-26 06:06 UTC, timfelle requested changes

2024-04-26 06:06 UTC, timfelle commented on README.md
> +make -j4 && make install && cd ../../
```suggestion
cmake -S json-fortran -B json-fortran/build -DCMAKE_INSTALL_PREFIX=${JSON_INSTALL} -DUSE_GNU_INSTALL_CONVENTION=ON ..
cmake --parallel --build json-fortran/build
cmake --install json-fortran/build
```
We might aswell suggest people to use modern syntax for cmake instead of the
legacy one.

2024-04-26 06:12 UTC, MartinKarp commented on README.md
> +make -j4 && make install && cd ../../
Thats a good idea, ill make a few fixes when I get to the office.

2024-04-26 06:58 UTC, njansson reviewed
Looks good! We should not forget to backport this to 0.8 before tagging a release.

One thing to consider is how to deal with autotools and regen.sh . These are only needed if the source has been cloned from the repo.

2024-04-26 06:58 UTC, njansson commented on README.md
> +To build the project you will need: A Fortran compiler supporting the Fortran-08 standard, a working MPI installation, JSON-Fortran, and BLAS/lapack. Optional dependencies are gslib and ParMETIS. We
```suggestion
To build the project you will need: A Fortran compiler supporting the Fortran-08 standard, a working MPI installation, JSON-Fortran, and BLAS/lapack. Optional dependencies are gslib and ParMETIS. We use autotools to build the project. These instructions should work in general, but as the project is quickly developing, things might change. While we assume MPI and BLAS are installed, if JSON-Fortran is not already available it can be cloned, installed, and the correct paths set with the following commands (Skip this step if you already have an installation of JSON-Fortran).
```

2024-04-26 09:13 UTC, MartinKarp commented
Updated a little bit

2024-04-26 11:24 UTC, MartinKarp commented
@timfelle The new lines with more modern cmake command do not work for me it seems, when I do the conventional `make && make install` it works.

2024-04-26 11:35 UTC, MartinKarp commented
Seems it something do to with --parallel, now it works

2024-04-26 12:04 UTC, timfelle commented
I think i might have swapped them arround, parallel should apparently be after the other one.

2024-04-30 13:22 UTC, njansson approved these changes

2024-04-30 13:26 UTC, timfelle approved these changes

2024-04-30 13:38 UTC, merged