Warn for ranks with 0 elements
ExtremeFLOW/neko pull request #1266
Opened 2024-05-02 10:10 UTC by timofeymukha

2024-05-02 11:04 UTC, MartinKarp requested changes

2024-05-02 11:04 UTC, MartinKarp commented on src/mesh/mesh.f90
> +       call neko_warning("One of the MPI ranks has 0 mesh elements!")
Could we perhaps also print the number of the rank?

2024-05-02 15:13 UTC, njansson commented on src/mesh/mesh.f90
> +    end if
```suggestion
    if (this%nelv < 1) then
       call neko_warning("Rank " // pe_rank // " ranks has zero mesh elements!")
    end if
```

@MartinKarp How about something like this?

2024-05-02 18:33 UTC, timofeymukha commented on src/mesh/mesh.f90
> +    end if
I didnt know you could concat numbers into a string like that!

2024-05-03 07:39 UTC, adperezm commented
Quick question, In which case could this happen? I only see this happening if nelv < mpiranks, or?


Am I missing something?

2024-05-03 15:48 UTC, timofeymukha commented
> Quick question, In which case could this happen? I only see this happening if global_nelv < mpiranks, or?
> 
> Am I missing something?

Yes, like if you run the RB example on >25 ranks. So, in principle, only you attempt to run a small problem on a huge number of ranks.

2024-05-06 16:04 UTC, timofeymukha commented on src/mesh/mesh.f90
> +    end if
@njansson OK, it seems one actiually cannot :-)

2024-05-06 17:18 UTC, MartinKarp approved these changes

2024-05-06 17:19 UTC, timofeymukha commented
Wait, some rogue files got in.. let me fix that :D

2024-05-06 17:20 UTC, timofeymukha commented
There we go. I think VS auto-commits all changes when I push some button..

2024-05-07 12:04 UTC, njansson approved these changes

2024-05-07 12:04 UTC, merged