The OIFS Scheme
ExtremeFLOW/neko pull request #1306
Opened 2024-06-11 18:55 UTC by Kamyarmvn

Added the OIFS time scheme functionality.

2024-06-12 08:20 UTC, njansson reviewed
Looks good,

A guess a question for a wider audience e.g. @timfelle @timofeymukha @MartinKarp is if we would like to have a new fluid_pnpn for oifs or a if statement?

2024-06-12 08:20 UTC, njansson commented on examples/tgv/tgv.case
> +  "timestep": 1e-1,
```suggestion
  "timestep": 1e-2,
```

2024-06-12 08:20 UTC, njansson commented on examples/tgv/tgv.case
> +    "oifs": true
```suggestion
    "dealias": true,
```

2024-06-12 08:20 UTC, njansson commented on examples/tgv/tgv.case
> +    "oifs": true
I would suggest that we add a new OIFS example instead of adding it to the current TGV example

2024-06-12 08:20 UTC, njansson commented on src/common/bcknd/device/cuda/makeoifs_kernel.h
> + Copyright (c) 2022, The Neko Authors
```suggestion
 Copyright (c) 2024, The Neko Authors
```

2024-06-12 08:20 UTC, njansson commented on src/common/bcknd/device/hip/makeoifs_kernel.h
> + Copyright (c) 2022, The Neko Authors
```suggestion
 Copyright (c) 2024, The Neko Authors
```

2024-06-12 08:32 UTC, njansson commented
@timfelle Any ideas why the CICD fails, despite this having a fresh sync with `develop`

2024-06-12 08:34 UTC, timfelle commented
> @timfelle Any ideas why the CICD fails, despite this having a fresh sync with `develop`

The error message indicate that two if statements are present in the same step. I think there might have been an issue with the automatic merger. Stand by.

2024-06-12 08:59 UTC, njansson commented
@Kamyarmvn can you please merge with the latest develop such that CI tests will run properly

2024-06-12 09:02 UTC, Kamyarmvn commented
> @Kamyarmvn can you please merge with the latest develop such that CI tests will run properly

I will try again.

For the issue of if statement in the fluid_pnpn step subroutine, one solution seems to be using a wrapper for the advection and make_rhs derived types, initilized based on the method and then called in the step subroutine.

2024-06-12 09:32 UTC, timfelle commented
Device codes are failing since the `.depends_device` file was not updated with the new header dependencies.

2024-06-12 09:56 UTC, Kamyarmvn commented
I'm sorry for the inconvenience. the .depends_device is updated now with the new dependencies.

2024-06-12 12:00 UTC, timfelle commented
please add the device kernel headers to the `extra_dist` list in the `Makefile.am`
That might help the compilers to find the new kernels.

2024-06-12 12:33 UTC, Kamyarmvn reviewed
Kernel headers added.

2024-06-12 12:39 UTC, Kamyarmvn reviewed
Taylor-Green vortex case is revised.

2024-06-12 16:02 UTC, njansson commented
> please add the device kernel headers to the `extra_dist` list in the `Makefile.am` That might help the compilers to find the new kernels.
> 
> PS. I know its a lot of manual management of the build system 🙈

Reminds me that I should write the device part of the contribution guide :(

2024-06-13 06:39 UTC, Kamyarmvn reviewed
I removed the codes related to the device. Once again, sorry for the trouble.

2024-06-13 06:42 UTC, timfelle commented
>>> please add the device kernel headers to the `extra_dist` list in the `Makefile.am` That might help the compilers to find the new kernels.
>> 
>> PS. I know its a lot of manual management of the build system 🙈

> Reminds me that I should write the device part of the contribution guide :( 

Sorry for the reminder 😅

2024-06-13 06:43 UTC, timfelle commented on examples/tgv/tgv.case
> +    "dealias": true,
```suggestion
    "dealias": true
```
Might aswell not include the file if we only add a , in the json

2024-06-13 06:45 UTC, timfelle commented on src/common/bcknd/sx/rhs_maker_sx.f90
> +       bfz(i) = bfz(i) + phiz(i) * (rho / dt)
```suggestion
       bfx(i) = bfx(i) + phix(i) * (rho / dt)
       bfy(i) = bfy(i) + phiy(i) * (rho / dt)
       bfz(i) = bfz(i) + phiz(i) * (rho / dt)
```
Trailing whitespace

2024-06-13 06:47 UTC, timfelle commented on src/common/time_interpolator.f90
> +  subroutine time_interpolator_velocity(this, t, c_t, c, ct, n)
It might be useful to use slightly more distinct names rather than everything
being called `c` with some modifier.

2024-06-13 06:50 UTC, timfelle commented on src/fluid/bcknd/advection/adv_oifs.f90
> +  !> Type encapsulating operator-integration-factor splitting advection routines with no dealiasing applied
```suggestion
  !! Type encapsulating operator-integration-factor splitting advection routines
  !! with no dealiasing applied
```
80 character length and `!!` on docstring continuations.

2024-06-13 07:32 UTC, timfelle commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
Please consider if the name `new` will be useful in 5 years. 
You might be able to use a more descriptive name.

2024-06-13 07:32 UTC, timfelle commented on src/math/operators.f90
> +  !> Compute one step of Runge Kutta time interpolatio for OIFS scheme.
```suggestion
  !> Compute one step of Runge Kutta time interpolation for OIFS scheme.
```
just a typo

2024-06-13 07:34 UTC, timfelle commented on src/math/bcknd/sx/sx_conv_fst_3d.f90
> +    !real(kind=rp), dimension(lx,lx,lx,nelv), intent(in) :: cr, cs, ct
seem you forgot to remove an unused line

2024-06-13 07:35 UTC, timfelle commented
@njansson I am not sure what goes wrong in the Reframe tests. Could you have a look?

2024-06-13 07:40 UTC, Kamyarmvn commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
I will change the name. I chose the name (and some variables) similar to NEK5000 because I thought it may be easier to track for someone familiar with nek5000.

2024-06-13 07:42 UTC, timfelle commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
Sure, the rationale makes sense. Maybe you could add a reference to the Nek5000 code in the docstring then? That might also help people following the tracks.

2024-06-13 08:00 UTC, Kamyarmvn commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
I added a note in the last line of the docstring. The new in this case was meant to say that the new convective velocity is set.

2024-06-13 09:16 UTC, njansson commented
> @njansson I am not sure what goes wrong in the Reframe tests. Could you have a look?

Reframe seems to be behaving as expected. Seems like the scalar interface is missing arguments.

I clone the branched and gave the RBC case try (similar to the case that fails)

```shell
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x13d93f925ec0)
    frame #0: 0x000000010014fb48 neko`__scalar_pnpn_MOD_scalar_pnpn_init at scalar_pnpn.f90:227:83
   224
   225 	    call advection_factory(this%adv, params, this%c_Xh, &
   226 	                           this%chkp%ulag, this%chkp%vlag, this%chkp%wlag, &
-> 227 	                           this%chkp%dtlag, this%chkp%tlag, time_scheme, this%slag)
   228 	  end subroutine scalar_pnpn_init
   229
   230 	  !> I envision the arguments to this func might need to be expanded
Target 0: (neko) stopped.
warning: This version of LLDB has no plugin for the language "fortran90". Inspection of frame variables will be limited.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x13d93f925ec0)
  * frame #0: 0x000000010014fb48 neko`__scalar_pnpn_MOD_scalar_pnpn_init at scalar_pnpn.f90:227:83
    frame #1: 0x00000001000f9d5c neko`__case_MOD_case_init_common at case.f90:255:59
    frame #2: 0x00000001000fb88c neko`__case_MOD_case_init_from_file at case.f90:121:28
    frame #3: 0x0000000100161fb4 neko`__neko_MOD_neko_init at neko.f90:261:35
    frame #4: 0x0000000100003670 neko`MAIN__ at usr_driver.f90:7:19
    frame #5: 0x0000000100164030 neko`main at usr_driver.f90:2:6
    frame #6: 0x0000000191303f28 dyld`start + 2236
(lldb)
```

2024-06-13 13:40 UTC, timofeymukha commented
No need for a new PR, or? You can just update this one? Then we presereve all the comments. If you just push to the same branch, the code in the PR is update, @Kamyarmvn

2024-06-13 13:41 UTC, timofeymukha commented
Thanks for this contribution! I will try to have a good look next week. What I would like to ask already now is to think about what can be added to the documentation.

2024-06-13 14:15 UTC, Kamyarmvn commented
> Thanks for this contribution! I will try to have a good look next week. What I would like to ask already now is to think about what can be added to the documentation.

Thank you! I will look forward to your feedback. I will take a look at the current documentation and share my thoughts about what can be added.

2024-06-24 14:51 UTC, timofeymukha requested changes

2024-06-24 14:51 UTC, timofeymukha commented on src/math/operators.f90
> +    type(space_t), intent(in) :: Xh_GLL
Would a good name here be `convect_scalar` ? We can keep the nek5000 name in the note as you did, but no need to propagate it here. Perhaps some info on how this different from `conv1` would be good (which, should also be renamed at some point...)

2024-06-25 11:54 UTC, Kamyarmvn commented on src/common/rhs_maker_fctry.f90
> +  subroutine rhs_maker_oifs_fctry(makeoifs)
I will fix this issue.

2024-06-25 11:57 UTC, Kamyarmvn commented on src/fluid/bcknd/advection/adv_oifs.f90
> +  !! routines with dealiasing applied
I will add the link to the literature as a note.

2024-06-25 11:58 UTC, Kamyarmvn commented on src/fluid/bcknd/advection/adv_oifs.f90
> +     procedure, pass(this) :: free => free_oifs
No problem. I will revise the names.

2024-06-25 11:59 UTC, Kamyarmvn commented on src/fluid/bcknd/advection/adv_oifs.f90
> +
I will fix the issue. Sorry.

2024-06-25 12:02 UTC, Kamyarmvn commented on src/case.f90
> +    call C%fluid%init(C%msh, lx, C%params, C%usr, C%material_properties, C%ext_bdf)
If I move it below the fluid%Init, I will have an error in runtime. This is because I use the checkpoints tlag and ctlag as a pointer for the adv_oifs which itself is initilized in fluid.

2024-06-25 12:06 UTC, Kamyarmvn commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
To be honest, I used this format because it was used in other subroutines such as conv1 and opgrad. My first implementation was nested loops just like the mentioned subroutines. However, I went with this version because it was faster, at least in my computer.  If this format is not required, I can get rid of this file and just add it in the op_cpu file.

2024-06-25 12:12 UTC, Kamyarmvn commented on src/math/operators.f90
> +    type(space_t), intent(in) :: Xh_GLL
Sure, I will change the name to convect_scalar and can add a description of what is the difference. this subroutine is specifically used for the dealiased case and oifs time scheme.

2024-06-25 12:15 UTC, Kamyarmvn commented
Thank you for all the feedback from everyone! I will revise the code based on the comments until next week.

2024-06-25 12:54 UTC, Kamyarmvn commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
For SX vector processors, this subroutine is similar to opgrad (they both calculate the local gradient). For cpu, the local gradients are calculated using mxm and no nested loops were used. So I guess in this case there is no need for the code to be in the current format. I have the fear of mxm being library dependent though. However it was faster than the nested loop implementation for cpu. I look forward to any recommendation and comments in this case.

2024-06-25 13:00 UTC, adperezm commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Jaha! that's good to know!. Thanks

2024-06-25 13:08 UTC, Kamyarmvn commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Thank you for the the review!

2024-06-25 17:04 UTC, njansson commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Indeed, as mentioned earlier, declaring `lx` as a constant (`parameter`) allow the compiler to vectorise much better (more information to work with). To see the difference, look at a compiler listing (e.g. from Cray Fortran) for e.g the generic `ax_helm_lx`:

```fortran
  146.  + 1----------------<     do e = 1, n
  147.    1 A--------------<        do j = 1, lx * lx
  148.    1 A 3------------<           do i = 1, lx
  149.    1 A 3                           tmp = 0.0_rp
  150.    1 A 3 4----------<              do k = 1, lx
  151.    1 A 3 4                            tmp = tmp + Dx(i,k) * u(k,j,1,e)
  152.    1 A 3 4---------->              end do
  153.    1 A 3                           wur(i,j,1) = tmp
  154.    1 A 3------------>           end do
  155.    1 A-------------->        end do
  156.    1
  157.  + 1 2--------------<        do k = 1, lx
  158.    1 2 A------------<           do j = 1, lx
  159.    1 2 A 4----------<              do i = 1, lx
  160.    1 2 A 4                            tmp = 0.0_rp
  161.    1 2 A 4 5--------<                 do l = 1, lx
  162.    1 2 A 4 5                             tmp = tmp + Dy(j,l) * u(i,l,k,e)
  163.    1 2 A 4 5-------->                 end do
  164.    1 2 A 4                            wus(i,j,k) = tmp
  165.    1 2 A 4---------->              end do
  166.    1 2 A------------>           end do
  167.    1 2-------------->        end do
  168.    1
  169.    1 A--------------<        do k = 1, lx
  170.    1 A 3------------<           do i = 1, lx*lx
  171.    1 A 3                           tmp = 0.0_rp
  172.    1 A 3 4----------<              do l = 1, lx
  173.    1 A 3 4                            tmp = tmp + Dz(k,l) * u(i,1,l,e)
  174.    1 A 3 4---------->              end do
  175.    1 A 3                           wut(i,1,k) = tmp
  176.    1 A 3------------>           end do
  177.    1 A-------------->        end do
```

and compare to e.g. the `lx = 8` specific case `ax_helm_lx8:`

```fortran
 1163.  + 1----------------<     do e = 1, n
 1164.  + 1 r4-------------<        do j = 1, lx * lx
 1165.    1 r4 V-----------<           do i = 1, lx
 1166.    1 r4 V                          wur(i,j,1) = Dx(i,1) * u(1,j,1,e) &
 1167.    1 r4 V                                     + Dx(i,2) * u(2,j,1,e) &
 1168.    1 r4 V                                     + Dx(i,3) * u(3,j,1,e) &
 1169.    1 r4 V                                     + Dx(i,4) * u(4,j,1,e) &
 1170.    1 r4 V                                     + Dx(i,5) * u(5,j,1,e) &
 1171.    1 r4 V                                     + Dx(i,6) * u(6,j,1,e) &
 1172.    1 r4 V                                     + Dx(i,7) * u(7,j,1,e) &
 1173.    1 r4 V                                     + Dx(i,8) * u(8,j,1,e)
 1174.    1 r4 V----------->           end do
 1175.    1 r4------------->        end do
 1176.    1
 1177.  + 1 f--------------<        do k = 1, lx
 1178.    1 f iVp----------<           do j = 1, lx
 1179.  + 1 f iVp ir4------<              do i = 1, lx
 1180.    1 f iVp ir4                        wus(i,j,k) = Dy(j,1) * u(i,1,k,e) &
 1181.    1 f iVp ir4                                   + Dy(j,2) * u(i,2,k,e) &
 1182.    1 f iVp ir4                                   + Dy(j,3) * u(i,3,k,e) &
 1183.    1 f iVp ir4                                   + Dy(j,4) * u(i,4,k,e) &
 1184.    1 f iVp ir4                                   + Dy(j,5) * u(i,5,k,e) &
 1185.    1 f iVp ir4                                   + Dy(j,6) * u(i,6,k,e) &
 1186.    1 f iVp ir4                                   + Dy(j,7) * u(i,7,k,e) &
 1187.    1 f iVp ir4                                   + Dy(j,8) * u(i,8,k,e)
 1188.    1 f iVp ir4------>              end do
 1189.    1 f iVp---------->           end do
 1190.    1 f-------------->        end do
 1191.    1
 1192.  + 1 f--------------<        do k = 1, lx
 1193.    1 f Vr2----------<           do i = 1, lx*lx
 1194.    1 f Vr2                         wut(i,1,k) = Dz(k,1) * u(i,1,1,e) &
 1195.    1 f Vr2                                    + Dz(k,2) * u(i,1,2,e) &
 1196.    1 f Vr2                                    + Dz(k,3) * u(i,1,3,e) &
 1197.    1 f Vr2                                    + Dz(k,4) * u(i,1,4,e) &
 1198.    1 f Vr2                                    + Dz(k,5) * u(i,1,5,e) &
 1199.    1 f Vr2                                    + Dz(k,6) * u(i,1,6,e) &
 1200.    1 f Vr2                                    + Dz(k,7) * u(i,1,7,e) &
 1201.    1 f Vr2                                    + Dz(k,8) * u(i,1,8,e)
 1202.    1 f Vr2---------->           end do
 1203.    1 f-------------->        end do
```

(A legend for the listing: `A - Pattern matched`, `i - interchanged`, `V - vectored`, `w - unwound` and `rX - unrolled X times`)

2024-06-26 07:32 UTC, Kamyarmvn commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Does this also apply to the mxm subroutine? Like the case in pu_conv_fst_3d.

2024-06-26 07:34 UTC, njansson commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
No this is only for the CPU and SX-Aurora backend, where we manually unroll everything for good performance. Currently we only have `mxm` calls in kernels related to the libxsmm backend, which I have to admit is seldom used nor well maintained.

2024-06-26 07:35 UTC, njansson commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
But one can still call `mxm` without libxsmm, but then one will fall down to a blast `dgemm` call

2024-06-26 07:37 UTC, Kamyarmvn commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Do you suggest the unroll version? I have that implementation as well.

2024-06-26 07:39 UTC, njansson commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
A related question. Since we talk about Nek5000, how different is the implementation in this PR from theirs? If there's significant overlap, we need to take care and not place it under Neko's license.

2024-06-26 07:40 UTC, njansson commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Yes, go for the unrolled version with `lx` as a parameter. That would give the best overall performance.

2024-06-26 07:42 UTC, Kamyarmvn commented on src/math/bcknd/cpu/set_convect_new.f90
> +    real(kind=rp), dimension(lx,lx,lx,n), intent(inout) :: cr, cs, ct
Thanks for the help! I will change the code.

2024-06-26 07:48 UTC, Kamyarmvn commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
The implementation is similar to NEK5000 (the important literature for this scheme is by Fischer who is also responsible for NEK5000). I can make some changes to the code and naming conventions but at its core I guess it will remain similar to NEK5000.

2024-06-26 08:00 UTC, Kamyarmvn commented on src/math/operators.f90
> +  subroutine set_convect_new(cr, cs, ct, cx, cy, cz, Xh, coef)
The similarity comes from the calculation of c.{\nabla u} in the Runge-Kutta scheme and the conv_fst_3d subroutine. For other parts, I don't think there is the structure is the same.

2024-07-04 14:59 UTC, Kamyarmvn reviewed
I fixed the issues regarding flint.
.depends is updated however I got errors. I hope it works this time.

2024-07-05 11:41 UTC, timfelle commented
> Regarding flint, I revised the codes but I still get error. They are completely similar to the previous codes such as opgrad but somehow I still get errors. Regarding the dependencies, I make sure to update the branch and check if there is conflict but I am still getting errors. I am not sure what I am missing here. It would be great if someone kindly help me with the issues I have at hand. I am sorry for the trouble.

Yes, that makes sense. opgrad and other similar codes are written in the style of Nek5000, not in the style of Neko. We have decided to start upgrading the old codes, by enforcing the style guide defined at: https://neko.cfd/docs/develop/da/db6/code-style.html on all new code.

One of the challenges here is that we cannot enforce this on a line by line basis. So any file with changes must adhere to the style guide.

The output from the linter (also included in the expandable section bellow) should be read as:

```
Linting failed for 
	path/to/file.f90

description-of-the-error
+---------+--------+------+-------------------------------------------------------------------------------+
| line_no | column | span |                                      line                                     |
+---------+--------+------+-------------------------------------------------------------------------------+
|    xx   |   yy   |  z   |                                      print of the failed line                 |
```

What i can see from this is:
- Missing spaces after punctuation, often triggered reported at a `,` without a space after it.
	A note here is that we allow single letter indices to not have the space. (i,j,k) would be allowed, otherwise a space must be added.
- Spaces around sepparators. Here the `::` must be sorrounded by spaces, unless it is for type allocation, `allocate(something_t::variable)` would be allowed.
- Lines must not be longer than 80 characters, so please break long lines with `&`.
- Logical operators (`.le.`, `.eq.`,...) and assignment operators (`=`) must be sorrounded by spaces.
- We do not allow trailing whitespace, so please remove it from `examples/TS_channel/TS_channel.f90` lines 146 and 237
- The one with `one-space-before-comment` is because of all the `!`. We do check that if it ends a string, then we allow one without the space in front. However appending more after each other is not ignored.

<details>
<summary>Hints from the linter</summary>

```
Files that failed linting:
	examples/TS_channel/TS_channel.f90 src/math/bcknd/cpu/opr_cpu.f90 src/math/bcknd/cpu/set_convect_rst.f90 src/math/bcknd/sx/sx_set_convect_rst.f90
--------------------------------------------------------------------------------
Linting failed for 
	examples/TS_channel/TS_channel.f90

/home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:65: UserWarning: Deprecated use of "fortran-syntax" , use the more generic "syntax" qualifier
  warnings.warn("Deprecated use of \"fortran-syntax\" , use the more generic \"syntax\" qualifier")
/home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:67: UserWarning: Rule file with no extension field default to fortran, prefer explicitely specifying one
  warnings.warn("Rule file with no extension field default to fortran, prefer explicitely specifying one")
/home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:70: UserWarning: Deprecated use of "blocks" in syntax, use instead "namespace_blocks" and "context_blocks"
  warnings.warn("Deprecated use of \"blocks\" in syntax, use instead \"namespace_blocks\" and \"context_blocks\"")
/home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:103: UserWarning: "var-declaration" is not defined in the rules
  warnings.warn("\"var-declaration\" is not defined in the rules")

missing-spaces-after-punctuation
+---------+--------+------+-------------------------------------------------------------------------------+
| line_no | column | span |                                      line                                     |
+---------+--------+------+-------------------------------------------------------------------------------+
|    34   |   39   |  3   |                                      ur_2D,ui_2D,vr_2D,vi_2D, &               |
|    51   |   38   |  3   |                 real(kind=rp) :: TS2D_GLC(num_rows,num_columns-1)             |
|    52   |   38   |  3   |                 real(kind=rp) :: TS3D_GLC(num_rows,num_columns-1)             |
|    57   |   38   |  3   |                 real(kind=rp) :: TS2D_GLL(num_ygll,num_columns-1)             |
|    58   |   38   |  3   |                 real(kind=rp) :: TS3D_GLL(num_ygll,num_columns-1)             |
|    98   |   42   |  3   |                   if (.not. in_array(u%dof%y(i,1,1,1),y_GLL)) then            |
|   106   |   60   |  3   |               TS2D_GLL(j,i) = GLC_GLL_interp(TS2D_GLC(:,i),y_GLC,y_GLL(j))    |
|   107   |   60   |  3   |               TS3D_GLL(j,i) = GLC_GLL_interp(TS3D_GLC(:,i),y_GLC,y_GLL(j))    |
|   112   |   45   |  3   |                 ur_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,1))         |
|   113   |   45   |  3   |                 ui_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,2))         |
|   114   |   45   |  3   |                 vr_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,3))         |
|   115   |   45   |  3   |                 vi_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,4))         |
|   116   |   45   |  3   |                 ur_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,1))         |
|   117   |   45   |  3   |                 ui_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,2))         |
|   118   |   45   |  3   |                 vr_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,3))         |
|   119   |   45   |  3   |                 vi_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,4))         |
|   120   |   45   |  3   |                 wr_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,5))         |
|   121   |   45   |  3   |                 wi_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,6))         |
|   123   |   41   |  3   |                                       ur_2D,ui_2D,vr_2D,vi_2D, &              |
|   124   |   53   |  3   |                                  ur_3D,ui_3D,vr_3D,vi_3D,wr_3D,wi_3D)         |
|   132   |   21   |  3   |                    function in_array(y,y_list) result(is_in)                  |
|   150   |   36   |  3   |         function pick_pt(y_target,y_source,Pt_source) result(Pt_target)       |
|   175   |   51   |  3   |                           ur_3D,ui_3D,vr_3D,vi_3D,wr_3D,wi_3D) result(uvw)    |
|   204   |   33   |  3   |                         u_mode_2D = cmplx(ur_2D,ui_2D,rp)                     |
|   205   |   33   |  3   |                         v_mode_2D = cmplx(vr_2D,vi_2D,rp)                     |
|   207   |   55   |  3   |              u_pert_TS_2D = TS_amp_2D*real(u_mode_2D*spa_osci_2D,rp)          |
|   208   |   55   |  3   |              v_pert_TS_2D = TS_amp_2D*real(v_mode_2D*spa_osci_2D,rp)          |
|   212   |   33   |  3   |                         u_mode_3D = cmplx(ur_3D,ui_3D,rp)                     |
|   213   |   33   |  3   |                         v_mode_3D = cmplx(vr_3D,vi_3D,rp)                     |
|   214   |   33   |  3   |                         w_mode_3D = cmplx(wr_3D,wi_3D,rp)                     |
|   216   |   57   |  3   |             u_pert_TS_3D = TS_amp_3D*real(u_mode_3D*spa_osci_3D_p,rp)         |
|   217   |   72   |  3   |      u_pert_TS_3D = u_pert_TS_3D + TS_amp_3D*real(u_mode_3D*spa_osci_3D_n,rp) |
|   218   |   57   |  3   |             v_pert_TS_3D = TS_amp_3D*real(v_mode_3D*spa_osci_3D_p,rp)         |
|   219   |   72   |  3   |      v_pert_TS_3D = v_pert_TS_3D + TS_amp_3D*real(v_mode_3D*spa_osci_3D_n,rp) |
|   220   |   57   |  3   |             w_pert_TS_3D = TS_amp_3D*real(w_mode_3D*spa_osci_3D_p,rp)         |
|   221   |   73   |  3   |     w_pert_TS_3D = w_pert_TS_3D + TS_amp_3D*real(-w_mode_3D*spa_osci [...]

2024-07-05 12:41 UTC, Kamyarmvn commented
> > Regarding flint, I revised the codes but I still get error. They are completely similar to the previous codes such as opgrad but somehow I still get errors. Regarding the dependencies, I make sure to update the branch and check if there is conflict but I am still getting errors. I am not sure what I am missing here. It would be great if someone kindly help me with the issues I have at hand. I am sorry for the trouble.
> 
> Yes, that makes sense. opgrad and other similar codes are written in the style of Nek5000, not in the style of Neko. We have decided to start upgrading the old codes, by enforcing the style guide defined at: https://neko.cfd/docs/develop/da/db6/code-style.html on all new code.
> 
> One of the challenges here is that we cannot enforce this on a line by line basis. So any file with changes must adhere to the style guide.
> 
> The output from the linter (also included in the expandable section bellow) should be read as:
> 
> ```
> Linting failed for 
> 	path/to/file.f90
> 
> description-of-the-error
> +---------+--------+------+-------------------------------------------------------------------------------+
> | line_no | column | span |                                      line                                     |
> +---------+--------+------+-------------------------------------------------------------------------------+
> |    xx   |   yy   |  z   |                                      print of the failed line                 |
> ```
> 
> What i can see from this is:
> 
>     * Missing spaces after punctuation, often triggered reported at a `,` without a space after it.
>       A note here is that we allow single letter indices to not have the space. (i,j,k) would be allowed, otherwise a space must be added.
> 
>     * Spaces around sepparators. Here the `::` must be sorrounded by spaces, unless it is for type allocation, `allocate(something_t::variable)` would be allowed.
> 
>     * Lines must not be longer than 80 characters, so please break long lines with `&`.
> 
>     * Logical operators (`.le.`, `.eq.`,...) and assignment operators (`=`) must be sorrounded by spaces.
> 
>     * We do not allow trailing whitespace, so please remove it from `examples/TS_channel/TS_channel.f90` lines 146 and 237
> 
>     * The one with `one-space-before-comment` is because of all the `!`. We do check that if it ends a string, then we allow one without the space in front. However appending more after each other is not ignored.
> 
> 
> Hints from the linter
> 
> ```
> Files that failed linting:
> 	examples/TS_channel/TS_channel.f90 src/math/bcknd/cpu/opr_cpu.f90 src/math/bcknd/cpu/set_convect_rst.f90 src/math/bcknd/sx/sx_set_convect_rst.f90
> --------------------------------------------------------------------------------
> Linting failed for 
> 	examples/TS_channel/TS_channel.f90
> 
> /home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:65: UserWarning: Deprecated use of "fortran-syntax" , use the more generic "syntax" qualifier
>   warnings.warn("Deprecated use of \"fortran-syntax\" , use the more generic \"syntax\" qualifier")
> /home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:67: UserWarning: Rule file with no extension field default to fortran, prefer explicitely specifying one
>   warnings.warn("Rule file with no extension field default to fortran, prefer explicitely specifying one")
> /home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:70: UserWarning: Deprecated use of "blocks" in syntax, use instead "namespace_blocks" and "context_blocks"
>   warnings.warn("Deprecated use of \"blocks\" in syntax, use instead \"namespace_blocks\" and \"context_blocks\"")
> /home/runner/.local/lib/python3.8/site-packages/flinter/rules.py:103: UserWarning: "var-declaration" is not defined in the rules
>   warnings.warn("\"var-declaration\" is not defined in the rules")
> 
> missing-spaces-after-punctuation
> +---------+--------+------+-------------------------------------------------------------------------------+
> | line_no | column | span |                                      line                                     |
> +---------+--------+------+-------------------------------------------------------------------------------+
> |    34   |   39   |  3   |                                      ur_2D,ui_2D,vr_2D,vi_2D, &               |
> |    51   |   38   |  3   |                 real(kind=rp) :: TS2D_GLC(num_rows,num_columns-1)             |
> |    52   |   38   |  3   |                 real(kind=rp) :: TS3D_GLC(num_rows,num_columns-1)             |
> |    57   |   38   |  3   |                 real(kind=rp) :: TS2D_GLL(num_ygll,num_columns-1)             |
> |    58   |   38   |  3   |                 real(kind=rp) :: TS3D_GLL(num_ygll,num_columns-1)             |
> |    98   |   42   |  3   |                   if (.not. in_array(u%dof%y(i,1,1,1),y_GLL)) then            |
> |   106   |   60   |  3   |               TS2D_GLL(j,i) = GLC_GLL_interp(TS2D_GLC(:,i),y_GLC,y_GLL(j))    |
> |   107   |   60   |  3   |               TS3D_GLL(j,i) = GLC_GLL_interp(TS3D_GLC(:,i),y_GLC,y_GLL(j))    |
> |   112   |   45   |  3   |                 ur_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,1))         |
> |   113   |   45   |  3   |                 ui_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,2))         |
> |   114   |   45   |  3   |                 vr_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,3))         |
> |   115   |   45   |  3   |                 vi_2D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS2D_GLL(:,4))         |
> |   116   |   45   |  3   |                 ur_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,1))         |
> |   117   |   45   |  3   |                 ui_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,2))         |
> |   118   |   45   |  3   |                 vr_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,3))         |
> |   119   |   45   |  3   |                 vi_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,4))         |
> |   120   |   45   |  3   |                 wr_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,5))         |
> |   121   |   45   |  3   |                 wi_3D = pick_pt(u%dof%y(i,1,1,1),y_GLL,TS3D_GLL(:,6))         |
> |   123   |   41   |  3   |                                       ur_2D,ui_2D,vr_2D,vi_2D, &              |
> |   124   |   53   |  3   |                                  ur_3D,ui_3D,vr_3D,vi_3D,wr_3D,wi_3D)         |
> |   132   |   21   |  3   |                    function in_array(y,y_list) result(is_in)                  |
> |   150   |   36   |  3   |         function pick_pt(y_target,y_source,Pt_source) result(Pt_target)       |
> |   175   |   51   |  3   |                           ur_3D,ui_3D,vr_3D,vi_3D,wr_3D,wi_3D) result(uvw)    |
> |   204   |   33   |  3   |                         u_mode_2D = cmplx(ur_2D,ui_2D,rp)                     |
> |   205   |   33   |  3   |                         v_mode_2D = cmplx(vr_2D,vi_2D,rp)                     |
> |   207   |   55   |  3   |              u_pert_TS_2D = TS_amp_2D*real(u_mode_2D*spa_osci_2D,rp)          |
> |   208   |   55   |  3   |              v_pert_TS_2D = TS_amp_2D*real(v_mode_2D*spa_osci_2D,rp)          |
> |   212   |   33   |  3   |                         u_mode_3D = cmplx(ur_3D,ui_3D,rp)                     |
> |   213   |   33   |  3   |                         v_mode_3D = cmplx(vr_3D,vi_3D,rp)                     |
> |   214   |   33   |  3   |                         w_mode_3D = cmplx(wr_3D,wi_3D,rp)                     |
> |   216   |   57   |  3   |             u_pert_TS_3D = TS_amp_3D*real(u_mode_3D*spa_osci_3D_p,rp)         |
> |   217   |   72   |  3   |      u_pert_TS_3D = u_pert_TS_3D + TS_amp_3D*real(u_mode_3D*spa_osci_3D_n,rp) |
> |   218   |   57   |  3   |             v_pert_TS_3D = TS_amp_3D*real(v_mode_3D*spa_osci_3D_p,rp)         |
> |   219   |   72   |  3   |      v_pert_TS_3D = v_pert_TS_3D + TS_amp_3D*real(v_mode_3D*spa_osci_3D_n,rp) |
> |   220   |   [...]

2024-07-06 03:21 UTC, Shiyu-Sandy-Du commented
For your first point of flint failure regarding codes from others, my suggestion is to merge the latest develop branch into your own branch.

As for the second point of .depend file, you could use makedepf90 tool to generate the dependency file. Please see [neko contributing instructions](https://neko.cfd/docs/develop/d1/d5a/contributing.html)

2024-07-06 10:18 UTC, Kamyarmvn commented
> For your first point of flint failure regarding codes from others, my suggestion is to merge the latest develop branch into your own branch.
> 
> As for the second point of .depend file, you could use makedepf90 tool to generate the dependency file. Please see [neko contributing instructions](https://neko.cfd/docs/develop/d1/d5a/contributing.html)

Thank you for the help. I make sure that my branch is updated before pushing the changes. I will take a closer look to see if I can find a solution.

2024-07-10 09:37 UTC, timofeymukha commented
@timfelle Here is a fun corner case

```
missing-spaces-around-=
+---------+--------+------+------------------------------------------------------------+
| line_no | column | span |                            line                            |
+---------+--------+------+------------------------------------------------------------+
|   252   |   32   |  2   |                 if (bc_label(1:2) .eq. 'd=') then          |
|   276   |   32   |  2   |                 if (bc_label(1:2) .eq. 'n=') then          |
```

2024-08-02 14:15 UTC, Kamyarmvn commented
I just accidentally closed this PR. Would it be possible to open it again?

2024-08-02 22:52 UTC, njansson commented
> I just accidentally closed this PR. Would it be possible to open it again? 
> 
> 

You should be able to reopen it since it is from your repo

2024-08-12 07:55 UTC, Kamyarmvn commented
I opened the pull request again.

2024-08-12 08:15 UTC, timfelle commented
Note a bug in the linter rules, should be fixed by PR #1422

```

Linting failed for 
	src/common/bcknd/sx/rhs_maker_sx.f90

issing-space-before-parenthesis
+---------+--------+------+-----------------------------------------------+
| line_no | column | span |                      line                     |
+---------+--------+------+-----------------------------------------------+
|   239   |   38   |  3   |      real(kind=rp), intent(inout) :: phis(n)  |
|   243   |   27   |  3   |        bfs(i) = bfs(i) + phis(i) * (rho / dt) |
+---------+--------+------+-----------------------------------------------+
```

2024-08-18 09:55 UTC, Kamyarmvn commented
I changed variable names so that there is no change in this particular case from linter.

2024-08-20 17:11 UTC, Kamyarmvn commented
I am sorry for all the problems. It would be great if someone could help me with the flint. I get different errors from flinter on my local machine than the ones on github. For example, for rhs_maker_sx, on my local machine, I get the "Lines too long" error although the lines are not over 80 characters at all. Here I get the "scope not specified" error (I didn't change this part of the code). I also get errors for fld_file.f90 which I haven't applied any changes to as far as I remember. For case.f90 I get "incorrect-spaces-before-separator"  and "incorrect-spaces-after-separator" and I don't get what is wrong here. If I remove spaces before and after "::", I still have the same error in my local machine.

2024-08-21 06:32 UTC, njansson commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
@timfelle, @timofeymukha  This and also `opr_cpu` illustrates some issues with the enforced only for modules. In these cases I don't think it make sense to list everything needed in the modules, since it is really the entire module e.g. ~16 routines for each backend.

Not sure how to fix it, since in general having enforced only is good for most cases

2024-08-21 07:03 UTC, timfelle commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
My kneejerk reaction would be to explore submodules

2024-08-21 07:12 UTC, timfelle commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
Take the subroutine `opr_cpu_dudxyz`.

Instead of defining it in `opr_cpu.f90`, you would only declare it as a `module subroutine`.
Then move the subroutine definition to `cpu_dudxyz.f90` and change `module cpu_dudxyz` to `submodule (opr_cpu) cpu_dudxyz`.

2024-08-21 07:25 UTC, njansson commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
But would that solve the issue with having only for each of the lx variants in each operator that has to be exposed with only

2024-08-21 07:36 UTC, timfelle commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
Yes because you would not need the `lx` variants in `opr_cpu.f90` since the definition of `opt_cpu_dudxyz` is then located in the submodule. `opt_cpu.f90` only need to declare that a module subroutine exists and which inputs it needs. Essentially the same as interfaces.

2024-08-21 07:41 UTC, timfelle commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
I have been playing a bit with submodules for a module of geometric operators.
Check PR #1433

2024-08-21 07:52 UTC, njansson commented on src/math/bcknd/sx/opr_sx.f90
> +   use mathops
Nice, that's promising. I need to read up a bit more on submodules

2024-08-21 12:15 UTC, Kamyarmvn commented on src/case.f90
I get flinter error for: if (pe_rank .ne. 0) allocate(character(len = integer_val) :: json_buffer). It seems that it requires an space between the separators (: :) which is wrong. Is there any way this can be solved?

2024-08-21 13:18 UTC, njansson commented on src/case.f90
Have you synced with a recent develop? There has been some fixes for the linter that addressed similar issues

2024-08-21 14:09 UTC, Kamyarmvn commented on src/case.f90
Yes, the branch is up to date. 
Also, should I use submodules for opr_cpu subroutines?

2024-08-27 09:44 UTC, Kamyarmvn commented
I tried using submodules and it was working but then it would trigger the flinter on the old modules and some of them required some work in order to pass the linting rules (too many local variables,..), therefore I used the current state.

2024-08-28 09:13 UTC, closed without merging