Update the hemi example to explciit bc setting
ExtremeFLOW/neko pull request #1314
Opened 2024-06-19 14:42 UTC by timofeymukha

- Adds boundary_types
- Remove the nmsh file
- Add the source re2
- Add a run.sh, which launches rea2nbin and then neko..

2024-06-19 14:52 UTC, njansson reviewed
Not sure it is the best way to remove the nmsh file. Especially since the script is not general enough such that it can run in all environments.

I would suggest that we leave the nmsh file, but also include the re2 and the script as an example on how the mesh is generated.

2024-06-20 08:07 UTC, timofeymukha commented
> Not sure it is the best way to remove the nmsh file. Especially since the script is not general enough such that it can run in all environments.
> 
> I would suggest that we leave the nmsh file, but also include the re2 and the script as an example on how the mesh is generated.

Yes, sounds good. I restored the nmsh

2024-06-20 09:01 UTC, njansson approved these changes
A suggestion would be to mention the raw re2 format in the readme, and refer users to the script for instructions on how to generate the neko mesh

2024-06-21 12:02 UTC, timfelle requested changes

2024-06-21 12:02 UTC, timfelle commented on examples/hemi/hemi.case
> +        "boundary_labels": ["sym", "w", "o", "v"],
```suggestion
        "boundary_labels": ["sym", "w", "v", "o"],
```
It would seem you swapped the flow direction.

2024-06-24 08:37 UTC, vbaconnet commented on examples/hemi/hemi.case
> +        "boundary_labels": ["sym", "w", "o", "v"],
```suggestion
        "boundary_types": ["sym", "w", "o", "v"],
```

This is what I get:
![image](https://github.com/ExtremeFLOW/neko/assets/62566252/5a2f8c4a-3b68-4a6a-b7d6-ec6e4f4536d4)

It looks okay to me, if we follow the indexing as output by `rea2nbin` no?

2024-06-24 09:30 UTC, timfelle commented on examples/hemi/hemi.case
> +        "boundary_labels": ["sym", "w", "o", "v"],
Well if you run the simulation on develop and on the PR the flow is reversed on
the PR. The labels might be right but the simulation is not.

2024-06-24 09:33 UTC, timfelle commented on examples/hemi/hemi.case
> +        "boundary_labels": ["sym", "w", "o", "v"],
But it seems the issue is fixed by your suggestion to change `boundary_labels`
to `boundary_types`

2024-06-24 09:37 UTC, timofeymukha commented on examples/hemi/hemi.case
> +        "boundary_labels": ["sym", "w", "o", "v"],
Ah yes, jeez. My bad, I just put the wrong keyword it seems.

2024-06-24 11:41 UTC, timfelle approved these changes

2024-06-24 11:41 UTC, merged