Fix/hip_device_count
ExtremeFLOW/neko pull request #1365
Opened 2024-07-16 07:33 UTC by timfelle

Should fix the device count interface for HIP.

We now have a sepparate function `hip_device_count` instead of the direct hip API binding.

Additionally we update to the latest develop branch.

2024-07-16 07:53 UTC, njansson commented
Sorry haven't had time to try it on lumi yet, however I have some doubt about the api binding. afaik it's not compatible with what the api provides, https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___device.html#ga8555d5c76d88c50ddbf54ae70b568394. The return values should be the error flag, and the number of devices is given by the argument (which shouldn't be passed as `value`, which was the issue in the previous implementation)

2024-07-16 08:00 UTC, timfelle commented
> Sorry haven't had time to try it on lumi yet, however I have some doubt about the api binding. afaik it's not compatible with what the api provides, [rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___device.html](https://rocm.docs.amd.com/projects/HIP/en/docs-6.0.0/doxygen/html/group___device.html#ga8555d5c76d88c50ddbf54ae70b568394). The return values should be the error flag, and the number of devices is given by the argument (which shouldn't be passed as `value`, which was the issue in the previous implementation)

I see... I accidentally ended up on the python documentation for hip instead of the c++ one...

2024-07-16 08:02 UTC, njansson commented
How about we add a `device_count` in `device.f90` such that we can query it from elsewhere in the code ?

2024-07-16 08:03 UTC, timfelle commented
> How about we add a `device_count` in `device.f90` such that we can query it from elsewhere in the code ?

That was the ultimate idea, yes. However I wanted to fix the lumi runs first and then make a dedicated PR where the other device types are also tied together.

2024-07-18 06:04 UTC, MartinKarp requested changes
Tiptop! Sorry for being a bit late on the review. I tested it on LUMI on GPU and the TGV case runs just fine. However, I managed to get spurious crashes for the turb_channel. When I reran however I did not crash. I don't know if this is a problem, but ikely not related to this. Only thing is changing to mpi rank I think rather than node.

2024-07-18 06:28 UTC, merged