Initial condition from fld or chkp
ExtremeFLOW/neko pull request #1366
Opened 2024-07-16 11:00 UTC by vbaconnet

Adds some functionalities outlined in #1283 for using fields as an initial condition.

Basically allows to initialize the simulation from `fld` or `chkp` files with the keyword `case.<fluid/scalar>.initial_condition.type = field`.

- For fld files so far there is no interpolation at all, i.e. we can only apply a field from the exact same mesh. 
- For chkp the already existing interpolations (mesh to mesh and from one polynomial order to another) are usable. 
- I am opening this as draft for others to add the missing functionalities if they so want, see the list below for the missing functionalities :)

# Todo

So far this needs to be tested with:

- [ ] AMD GPUs
- [ ] Nvidia GPUs
- [x] CPUs 

Functionalities
- [x] Read from chkp with or without interpolation
- [x] Read from fld without interpolation
- [ ] Read from fld with interpolation (different polynomial order)
- [ ] Read from fld with interpolation (mesh to mesh)
- [ ] Read from fld with 2D extrusion

# Usage

## `chkp`

We read the entire chkp file but only apply `u,v,w,p` and/or `s`. 

```json
"initial_condition": {
    "type": "field",
    "file_name": "fluid00001.chkp",
}
```

Any interpolation that `chkp` does when reading the file can also be done here, so essentially one can use a chkp file with mesh to mesh interpolation or just interpolation from different polynomial order (the latter doesn't need any additional keywords):

```json
"initial_condition": {
    "type": "field",
    "file_name": "fluid00001.chkp",
    "previous_mesh": "mesh.nmsh",
    "tolerance": 1e-6
}
```

## `fld`

Here I see two different use cases:

The first one would be where one has a series of `field0.fld` files and we select the index of the file we want to sample.

```json
"initial_condition": {
    "type": "field",
    "file_name": "field0.fld" or "field0.nek5000",
    "sample_index": 5 <--- this will read field0.f00005
}
```

Without specifying `sample_index` we read the last fld file in the series by default, provided that a `field0.nek5000` file exists, if not it will default to reading `field0.f00000`.

The second use case is if one only has a single field file for example `myfield0.f00100`, then one can directly use that file name and the sample_index will be retrieved from the extension `f00100`:

```json
"initial_condition": {
    "type": "field",
    "file_name": "myfield0.f00100"
}
```

For fld files there is no interpolation yet but I guess this provides an initial framework.

# Other changes

I added some logging for the initial condition so it becomes cleaner when using the `fld` reader that outputs some messages, that gives something like:

```text
   ---Fluid initial condition----  
   Type: field
   File name: results/field0.fld
   Reading meta file for fld series
   Name: field0
   Start counter    :       0
   Number of samples:      17
   Reading fld file results/field0.f00000
   Reading fld file results/field0.f00016
  
   ---Scalar initial condition---  
   Type: field
   File name: results/field0.fld
   Sample index: 00005
   Reading meta file for fld series
   Name: field0
   Start counter    :       0
   Number of samples:      17
   Reading fld file results/field0.f00005
```

But it will also output all the values provided if one uses the other initial condition types like `blasius`, `uniform`, `point_zone` etc.

```text
   ---Fluid initial condition----  
   Type: blasius
   delta       :   0.001000
   Approximation: sin
   Value: [  1.000000,  0.000000,  0.000000]
```

2024-07-16 11:02 UTC, vbaconnet commented on src/fluid/flow_ic.f90
> +    call fld_data%init
Should this init be `init(u%msh%nelv, u%msh%offset_el)`?

2024-07-16 11:14 UTC, vbaconnet commented on src/fluid/flow_ic.f90
> +    call copy(p%x, fld_data%p%x, p%dof%size())
Do we need to copy the pressure too? Is that what one would want from this feature?

2024-07-16 11:16 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Could we also init with `chkp_data%init(s,s,s,s)`? Or is it dangerous?

2024-07-23 07:35 UTC, adperezm commented
Great work!

A comment before reading the code:
I think it is very good also that one can specify directly the file name (avoiding .nek5000) files. In that sense, it could also be good that one gives that option for the file with the mesh, rather than just the index.

I think I see your reasoning, however, since you would restart in a folder that already has an up to date .nek5000 and all that. But it is good to have options.

2024-07-23 07:49 UTC, vbaconnet commented
> it could also be good that one gives that option for the file with the mesh, rather than just the index.

Actually yes it would make sense to be able to do it via a file too. Also I am now wondering if it even makes sense to have the option to give the index?

2024-07-23 07:59 UTC, adperezm reviewed
I did not check the ic files since I am not familiar with them, but everything is very nice! just some minor comments.

2024-07-23 07:59 UTC, adperezm commented on src/common/global_interpolation.F90
> +     real(kind=rp) :: tol = 5d-13
I do not know how relevant, but one could run into trouble if trying to restart from an fld file that is in single precision. I suppose that we do not need to change the defaults here, but rather give a warning to the user when they try to do that.

2024-07-23 07:59 UTC, adperezm commented on src/sem/dofmap.f90
Nice, I think this sort of init is very good to have for post processing scripts.

2024-07-23 07:59 UTC, adperezm commented on src/io/fld_file_data.f90
> +         call neko_error("something weird happening")
Excellent name :P.

I can imagine a user frustration if they get that error message haha. Maybe something more descriptive.

2024-07-23 08:44 UTC, vbaconnet commented on src/common/global_interpolation.F90
> +     real(kind=rp) :: tol = 5d-13
You mean the change from `e` to `d` or the fact that the tolerance could be too low for single precision?

I was running into single precision issues on LUMI, and it made me wonder if perhaps it would be good that we always output the first field file with the mesh in double precision, and the rest is up to the user?

2024-07-23 09:04 UTC, adperezm commented on src/common/global_interpolation.F90
> +     real(kind=rp) :: tol = 5d-13
I meant that the tolerance might be too low. In your .nmsh you have double, but then the fld will have single, so there will be a lot of rubbish after some digits.

I think that since the initialization from fld is a very specific thing (I would hope and assume that people use the chkp which are always in double) the files can be left as they are. But someone else can comment on you second point, it does not matter for me.

One thing about writing the first file in double and then the rest in single is that I do not know how visit and the sort would behave.

2024-07-23 09:05 UTC, adperezm commented on src/io/fld_file_data.f90
> +         call neko_error("something weird happening")
Haha yeah, I thought so :)

2024-07-23 09:10 UTC, vbaconnet commented on src/common/global_interpolation.F90
> +     real(kind=rp) :: tol = 5d-13
> I think that since the initialization from fld is a very specific thing the files can be left as they are ( (I would assume that the default use would be the chkp which are always in double). But someone else can comment on you second point, it does not matter for me.

I think this is definitely worth mentioning in the documentation, and adding a warning if the fld file is in single precision.

> One thing about writing the first file in double and then the rest in single is that I do not know how visit and the sort would behave.

Oh that is true, I have no idea either.

2024-07-23 09:19 UTC, Shiyu-Sandy-Du commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
I don't think it would be dangerous anyway since in `chkp_t%init()`, all arguments are declared to be `intent(in)`

2024-07-23 09:35 UTC, Shiyu-Sandy-Du commented on src/io/fld_file_data.f90
> +       center_z = 0d0
Will these double precision assignment pass the PR test for single precision compiler?

2024-07-23 10:50 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Yes, that is true. But then `chkp_t` has pointers to u,v,w,p in `checkpoint::chkp_init` and the reader seems to write over them in `chkp_file::chkp_file_read`:

```.f90
    call this%read_field(fh, byte_offset, u%x, nel)
! ...
    call this%read_field(fh, byte_offset, v%x, nel)
! ...
    call this%read_field(fh, byte_offset, w%x, nel)
! ...
    call this%read_field(fh, byte_offset, p%x, nel)
! ...
    if (read_scalar) then
       call this%read_field(fh, byte_offset, s%x, nel)
    end if
```

So I wonder if this means that a call to `chkp_file%read(chkp_data)` will overwrite `u,v,w,p` and `s`, potentially messing things up.

2024-07-23 11:06 UTC, adperezm commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
I think this is a good place where maybe @MartinKarp knows from the top of his head.

The other alternative is to of course track at which point the data is given to the u,v,w,p fields that are part of the fluid scheme.

A quick look (which I guess you have seen) tells that the u%x that appears in those read_file() calls are part of the field_data type, so I guess they do not directly affect the fields in the fluid scheme. But maybe they do downstream..

2024-07-23 11:10 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Actually now that I am testing just initializing the scalar from a checkpoint I see that it's not reading the scalar properly anymore, but `u` instead. Even with `init(s,s,s,s)`, kind of weird

2024-07-23 11:58 UTC, vbaconnet commented on src/io/fld_file_data.f90
> +       center_z = 0d0
The same lines were merged previously in `chkp_file` with the mesh to mesh interpolation so I'm expecting it to work

2024-07-23 12:02 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Ok so the issue is that we don't read the `ulag, vlag, wlag` fields even though they are in the file, so when it is time to read `scalar` we instead read `ulag`.

2024-07-23 12:49 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
I pushed the first option so you can see what it looks like

2024-07-23 13:29 UTC, timofeymukha commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
>Ok so the issue is that we don't read the ulag, vlag, wlag fields even though they are in the file, so when it is time to read scalar we instead read ulag. 

Sigh, this is exactly the type of crap HDF5 will fix.

2024-07-23 13:38 UTC, adperezm commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Well, having data in a file and not accessing it can happen with everything. That's more on us

2024-07-23 13:50 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
> Is there something fundamentally different in what you are doing here?

Yes, I do not initialize any lag arrays in the `chkp_t` object before reading the chkp file, because I do not have access to those from `flow_ic` or `scalar_ic`.

2024-07-23 13:57 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
For a normal restart you add the lag arrays in [fluid_pnpn](https://github.com/ExtremeFLOW/neko/blob/411e4c2a2f1fa8b121d00c4f94be29dd378b0b00/src/fluid/fluid_pnpn.f90#L315):
```.f90
call this%chkp%add_lag(this%ulag, this%vlag, this%wlag)
```

but those are in `fluid`, which is not visible from `scalar_ic`

2024-07-23 15:08 UTC, MartinKarp requested changes
Good work! The only thing I would like to raise is whether we should support set ic from chkp. For the fld file I think it is great, but why would one not restart from the chkp? 

Is there some interpolation we do when setting it as ic we don't do when doing the restart?

I would personally skip support for chkp, but now you have done a lot of work on it so.

Sorry for the late comment, but Im on vacation until the 11th.

2024-07-23 15:09 UTC, MartinKarp commented on src/io/fld_file_data.f90
> +       center_z = 0d0
these are scalars so they are correctly casted by the compiler.

2024-07-23 15:12 UTC, MartinKarp commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Is the ic from chkp working now? Otherwise, as I wrote in my review I would perhaps skip it. I am also not entirely sure when one wants to set the ic from a checkpoint.

2024-07-23 15:14 UTC, vbaconnet commented on src/common/global_interpolation.F90
> +  subroutine global_interpolation_init(this, dof, tol, Xh, msh)
It was in case we passed down a "stripped-down" `dofmap` that only had x,y,z coordinates. But as you said it makes more sense to just remove dofmap from the init directly,

2024-07-23 15:17 UTC, vbaconnet commented
> why would one not restart from the chkp?

I guess it was just to have that option. In case the restart somehow does not work for any reason one can still use the fields for a first order restart. Thinking about some simulation component that does not restart properly for example. But in practice as you say this is probably quite rare.

2024-07-23 15:28 UTC, vbaconnet commented on src/scalar/scalar_ic.f90
> +    call chkp_data%init(u,v,w,p)
Yes it's working. Just have to hardcode the size of lag arrays so...

2024-09-13 09:59 UTC, vbaconnet commented
I think this is pretty much done :)

2024-09-18 07:53 UTC, timofeymukha reviewed
Very nice! 

I am a bit conflicted on whether we need the logic for figuring out where stuff is instead of just forcing the user to point to concrete filenames. But I guess now that you added it, let's keep it :-).

2024-09-18 07:53 UTC, timofeymukha commented on doc/pages/user-guide/case-file.md
> +   to `true` even if the field file matches with the current simulation.
Maybe we can just point to the doc for fluid here.

2024-09-18 07:53 UTC, timofeymukha commented on src/common/global_interpolation.F90
> +         dof%msh%gdim, dof%msh%nelv, dof%Xh, tol = tol)
Does this actually send the whole x y z arrays and not just a small slice?

2024-09-18 08:55 UTC, vbaconnet commented on src/common/global_interpolation.F90
> +         dof%msh%gdim, dof%msh%nelv, dof%Xh, tol = tol)
It sends the whole array! it's a trick I got from Martin :) or rather from what was done in the fld_file read/write routines! https://github.com/ExtremeFLOW/neko/blob/2969cdbc1fe039511bc7f4e6c003070e0a5b9cb2/src/io/fld_file.f90#L185-L189

2024-09-18 09:00 UTC, vbaconnet commented
> I am a bit conflicted on whether we need the logic for figuring out where stuff is instead of just forcing the user to point to concrete filenames. But I guess now that you added it, let's keep it :-).

I mean I don't mind removing it if it makes the usage less confusing :) Whatever is best for the user, also at this point it is easier to remove things than add more functionality, especially since the logic in `flow_ic` and `scalar_ic` is not the easiest to follow (from my experience of coming back to it after the summer vacations).

2024-09-18 09:05 UTC, timofeymukha commented on src/common/global_interpolation.F90
> +         dof%msh%gdim, dof%msh%nelv, dof%Xh, tol = tol)
Black magic. Add a comment maybe, for sure this will surprise people.

2024-09-18 09:06 UTC, vbaconnet commented on src/common/global_interpolation.F90
> +         dof%msh%gdim, dof%msh%nelv, dof%Xh, tol = tol)
hahaha sure

2024-09-19 07:14 UTC, timofeymukha commented on src/common/global_interpolation.F90
> +         dof%msh%gdim, dof%msh%nelv, dof%Xh, tol = tol)
Yeah just a note is fine!

2024-09-19 07:15 UTC, timofeymukha approved these changes

2024-09-19 07:32 UTC, timfelle commented on src/fluid/flow_ic.f90
> +       call neko_log%message(log_buf)
Maybe this should be inside the set_flow_ic_blasius? It's great with some info
on the initial condition though.

2024-09-19 07:34 UTC, timfelle commented on src/fluid/flow_ic.f90
> +       end if
Same here, I think it would make sense if checks for validity is done inside the
`set_flow_ic_fld` and not in the factory.

2024-09-19 07:54 UTC, timfelle commented on src/simulation_components/probes.F90
>      if (.not. found) then
Maybe just remove the if statement below. `json_get` does the check for us.

2024-09-19 07:55 UTC, timfelle commented on src/case.f90
> +    call neko_log%message("Type: " // trim(string_val))
Maybe let each type message who they are themselves.

2024-09-19 07:56 UTC, timfelle approved these changes
All in all, looks good. My comments are more suggestions and "food for thought"

2024-09-24 10:14 UTC, vbaconnet commented on src/case.f90
> +    call neko_log%message("Type: " // trim(string_val))
Do you mean something like:
```.f90
if (trim(type) .eq. 'uniform') then
   call neko_log%message("Type: uniform")
else if (trim(type) .eq. 'blasius') then
   call neko_log%message("Type: blasius")
else if (trim(type) .eq. 'point_zone') then
   call neko_log%message("Type: point zone")
else if (trim(type) .eq. 'field') then
   call neko_log%message("Type: field")
else
   call neko_error('Invalid initial condition')
end if
```

or in their respective `set_flow_ic_*`? 

The reason I did it this way initially was to avoid calling it in both `set_flow_ic_int` and `set_flow_ic_usr`.

2024-09-24 10:55 UTC, timfelle commented on src/case.f90
> +    call neko_log%message("Type: " // trim(string_val))
I would say it should be done at least in the set_flow_ic_* and not in `case.f90`.

Lets assume we build a case with two different fluids. Now we need to move the print statement. If we place it inside the ic factory we don't have to worry about it.

2024-10-04 11:56 UTC, MartinKarp approved these changes

2024-10-04 11:56 UTC, merged