Fix for 'sym' and 'on' bc
ExtremeFLOW/neko pull request #1438
Opened 2024-08-26 19:12 UTC by MartinKarp

Perhaps not optimal, maybe one should change the the init to something like mark components? 

Can take that in another PR though so we have this working. 

I have tried to check if there are more similar bugs, but couldn't find any.

Let's continue to be vigilant for similar things!

2024-08-26 22:23 UTC, timofeymukha commented
I didn't quite understand, why can one not init base here? One should probably at least point this%coeff to coef manually then, right?

Regarding renaming init, can we wait with that a bit? I need to sync my bc pr with the latest develop once I am back and probably start issuing some PRs with cherrypicks from it. I want to think a bit about how to deal with these composite bcs..

2024-08-27 06:01 UTC, adperezm commented
On this. I think we have talked before, but why do we oppose to call the case file <casefile>.json?

Then you get stuff like this directly if a comma is missing:
![image](https://github.com/user-attachments/assets/fb05fbf1-fc1a-4573-9bb2-24c757fec98e)

Just wondering. A colleague apparently spent hours trying to debug this sort of error. This reformulation of the message would help for sure though.

2024-08-27 08:40 UTC, MartinKarp commented
Yes lets wait. The reason is here

https://github.com/ExtremeFLOW/neko/blob/93cb557022456295d8963d2dfdece2bda69c0228/src/bc/bc.f90#L201C1-L220C34

2024-08-28 12:03 UTC, timofeymukha commented
But dont we need to run this code form the constructor somewhere for the object to be valid?

````
    this%dof => coef%dof
    this%coef => coef
    this%Xh => this%dof%Xh
    this%msh => this%dof%msh
````

2024-08-28 14:53 UTC, MartinKarp commented
It is done before we add the facets

2024-08-28 15:47 UTC, timofeymukha commented
> It is done before we add the facets into marked_facets.
> 
> Procedure right now is
> 
> ```
> init_base
> mark facets with some operation
> finalize
> init(sym,on)
> ```
> 
> This is not very nice of course, but it is what we have currently. So we cannot do init_base after add facets. Here it is for 'sym'.
> 
> https://github.com/ExtremeFLOW/neko/blob/a213e423c3fd962fdeabfc3572a11f91c538c850/src/fluid/fluid_scheme.f90#L417

Ok, thanks for the clarification. I am hoping this will be solved by having deferred init eventually. I will have to keep in mind of this.

2024-08-28 15:47 UTC, timofeymukha approved these changes

2024-08-28 20:00 UTC, njansson commented
> > It is done before we add the facets into marked_facets.
> 
> > 
> 
> > Procedure right now is
> 
> > 
> 
> > ```
> 
> > init_base
> 
> > mark facets with some operation
> 
> > finalize
> 
> > init(sym,on)
> 
> > ```
> 
> > 
> 
> > This is not very nice of course, but it is what we have currently. So we cannot do init_base after add facets. Here it is for 'sym'.
> 
> > 
> 
> > https://github.com/ExtremeFLOW/neko/blob/a213e423c3fd962fdeabfc3572a11f91c538c850/src/fluid/fluid_scheme.f90#L417
> 
> 
> 
> Ok, thanks for the clarification. I am hoping this will be solved by having deferred init eventually. I will have to keep in mind of this.

But free should be fine to call or?

2024-08-28 20:04 UTC, MartinKarp commented
The issue is that free_base makes this%marked_facet empty. So one will never mark the different components of the bc when calling the init that's specific for sym and on

2024-08-29 07:23 UTC, njansson commented on src/bc/non_normal.f90
>      call this%bc_x%init_base(this%coef)
If we can't call free due to free_base, we should at least do some housekeeping to ensure that at least our object is clean 
```suggestion
    call this%bc_x%free()
    call this%bc_y%free()
    call this%bc_z%free()
    
    call this%bc_x%init_base(this%coef)
```

2024-08-29 07:23 UTC, njansson commented on src/bc/symmetry.f90
>      call this%bc_x%init_base(this%coef)
```suggestion
    call this%bc_x%free()
    call this%bc_y%free()
    call this%bc_z%free()
    
    call this%bc_x%init_base(this%coef)
```

2024-08-30 05:01 UTC, timfelle commented
> The issue is that free_base makes this%marked_facet empty. So one will never mark the different components of the bc when calling the init that's specific for sym and on

Should marking the facets not be a part of the initialization? Modifying parts of an object before initialization is usualy not a good approach

2024-08-30 07:54 UTC, timofeymukha commented
> > The issue is that free_base makes this%marked_facet empty. So one will never mark the different components of the bc when calling the init that's specific for sym and on
> 
> Should marking the facets not be a part of the initialization? Modifying parts of an object before initialization is usualy not a good approach

In principle, yes, but the issue is that we have to allow for marking the facets to be a step by step process. E.g. we start by marking one boundary, then add some more facets etc. This is the reason currently we have an init, then marking of the facets, and then a finalize, which finishes up the construction of the object. In #1264 I make use of the fact that usually the facets are just one zone, so a bc factory inits, marks, and finalizes based on the type of bc and the zone index.

2024-09-03 06:21 UTC, timfelle requested changes

2024-09-03 06:21 UTC, timfelle commented on src/bc/symmetry.f90
> +
```suggestion

```

2024-09-03 06:21 UTC, timfelle commented on src/bc/non_normal.f90
> +
```suggestion

```

2024-09-03 09:51 UTC, MartinKarp commented
Perhaps this should also be added to the latest release?

2024-09-04 09:50 UTC, njansson commented
> Perhaps this should also be added to the latest release?

Sounds good, let me bake a bug fix release

2024-09-04 14:48 UTC, njansson approved these changes

2024-09-04 18:08 UTC, merged