Fluid statistics as simcomp and 1D/2D stats
ExtremeFLOW/neko pull request #1494
Opened 2024-09-19 20:38 UTC by MartinKarp

Makes fluid_stats a simcomp and makes it possible to average in 2 or 1 homogeneous directions and significantly compress the output stats files.

Still a bit work in progress, I want to add the option to only output the first x raw statistics or 2nd order or similar.

Builds on #1493 and replaces #1334 

Slightly different functionality than previously as one now outputs a "empty" stats file as soon as sampling begins. Makes it easier to keep track of when one starts to sample the statistics as one now has a file output at that time.

Also updated the documentation a bit, I also want to go through that a bit more.

2024-09-19 20:45 UTC, MartinKarp commented
I might have pulled in force_torque here as well, but I guess that will be merged before so I hope that's ok.

2024-09-20 14:05 UTC, ronithstanly reviewed
Looks good. Just found a couple of typos in the comments.

2024-09-23 11:18 UTC, ronithstanly commented on doc/pages/user-guide/statistics-guide.md
> +For 1D statistics a CSV file is outputted. The first column is the time at which the statistics are collected, the second column the spatial coordinate, and the rest of the data is stored in the orde
It is good to add somewhere in the documentation what the first entry in the csv (in case of 2 homogenous directions for averaging) and the first fld file (in case of only 1 homogenous direction for averaging) corresponds to and that it differs from the real statistics which will be included in the later entries

2024-09-23 13:08 UTC, MartinKarp commented on doc/pages/user-guide/statistics-guide.md
> +For 1D statistics a CSV file is outputted. The first column is the time at which the statistics are collected, the second column the spatial coordinate, and the rest of the data is stored in the orde
But does it differ? It does output the average from the specified start_time to the current time. Current time and output time is the same the weight will simply be 0.

2024-09-23 13:33 UTC, ronithstanly commented on doc/pages/user-guide/statistics-guide.md
> +For 1D statistics a CSV file is outputted. The first column is the time at which the statistics are collected, the second column the spatial coordinate, and the rest of the data is stored in the orde
Why I mentioned this is because when I loaded the first fld stat file that came out of averaging, I forgot that to see the real average fields I should start looking from the second file instead of looking at the very first file that is outputted.

2024-09-23 13:55 UTC, MartinKarp commented on doc/pages/user-guide/statistics-guide.md
> +For 1D statistics a CSV file is outputted. The first column is the time at which the statistics are collected, the second column the spatial coordinate, and the rest of the data is stored in the orde
Right, let's add something

2024-09-25 05:41 UTC, timfelle commented on doc/pages/user-guide/statistics-guide.md
> +Statistics are enable in the the case file as a simcomp with the added argument avg_direction, set_of_stats, and start_time:
```suggestion
Statistics are enable in the the case file as a simcomp with the added argument `avg_direction`, `set_of_stats`, and `start_time`:
```

2024-09-25 15:01 UTC, Shiyu-Sandy-Du requested changes

2024-09-26 21:57 UTC, timofeymukha reviewed
I've started going through the files. Very happy to see some base types getting slimmer. I issues a doc and style pr, mostly for fluid_stats, which is what I went through so far.

Question, can we directly use grad instead of opgrad and kill the make_strong_grad routine?

2024-09-26 21:57 UTC, timofeymukha commented on src/fluid/fluid_stats.f90
>       type(field_t) :: stats_u !< Not reasonable to allocate 20 something fields
These work arrays can probably be taken from the registry.

2024-09-26 21:57 UTC, timofeymukha commented on src/fluid/fluid_stats.f90
>      class(fluid_stats_t) :: this
Is this routine going to be deprecated to Python?

2024-09-26 21:58 UTC, timofeymukha commented on src/fluid/fluid_stats.f90
>       type(field_t) :: stats_u !< Not reasonable to allocate 20 something fields
This is regarding the stats_ fields. I realize you don't touch this in the PR though. So can be skipped.

2024-09-26 22:20 UTC, timofeymukha commented on src/simulation_components/fluid_stats_simcomp.f90
> +
How does this timing fit with the profiling added by @njansson ? Can that be used instead? I feel like outputting this at every timestep is perhaps superflous.

2024-09-26 22:21 UTC, timofeymukha commented on src/simulation_components/fluid_stats_simcomp.f90
> +    type(field_t), intent(inout) :: u, v, w, p !>Should really be intent in I think
But it cannot be?

2024-09-26 22:22 UTC, timofeymukha commented on examples/turb_channel/turb_channel.case
> +      "compute_value": 50,
So we can sample based on simulation time as well, like @Mr-2c wanted?

2024-09-26 22:29 UTC, njansson commented on src/simulation_components/fluid_stats_simcomp.f90
> +
I think it's good to have both, the one can always extract data from the log if something extra is needed.

So here I would suggest to add an additional profiler region such that it can also end up in both NVTX traces as well as the runtime stats

2024-09-26 22:34 UTC, timofeymukha commented on src/simulation_components/fluid_stats_simcomp.f90
> +  end subroutine fluid_stats_simcomp_free
Should we call free on the stats object?

2024-09-26 22:37 UTC, timofeymukha commented on src/io/fluid_stats_output.f90
> +               end if
Are we sure this is a good idea? I think it will be much less error prone to just always store the 3 velocity components first and let the user figure out which ones are relevant later in Python.

2024-09-26 22:46 UTC, timofeymukha commented
OK, I am done reviewing now :-). It seems Niclas merged my style PR, there is a new small one opened for another file. I did not expect anyone to be active now, but ofc there is the time difference. So, it seems @MartinKarp will wake up to a slightly updated branch. Hopefully I did not mess anything up.

2024-09-27 07:27 UTC, MartinKarp commented on src/fluid/fluid_stats.f90
>      class(fluid_stats_t) :: this
Yes, I was thinking one can add warnings when pynektools becomes public.

2024-09-27 07:29 UTC, MartinKarp commented on src/simulation_components/fluid_stats_simcomp.f90
> +    type(field_t), intent(inout) :: u, v, w, p !>Should really be intent in I think
Because we never modify these fields, but only use them, but I guess there are some routines that I use that have inout.

2024-09-27 07:29 UTC, MartinKarp commented on examples/turb_channel/turb_channel.case
> +      "compute_value": 50,
Yup

2024-09-27 07:30 UTC, MartinKarp commented on src/io/fluid_stats_output.f90
> +               end if
Otherwise visualizing the field becomes extremely confusing.

2024-09-27 07:30 UTC, MartinKarp commented on src/simulation_components/fluid_stats_simcomp.f90
> +  end subroutine fluid_stats_simcomp_free
Good point

2024-09-27 12:04 UTC, timofeymukha commented on src/simulation_components/fluid_stats_simcomp.f90
> +    type(field_t), intent(inout) :: u, v, w, p !>Should really be intent in I think
Yeah, we have in general been a bit too sloppy with this in the code base

2024-09-27 12:05 UTC, timofeymukha commented on examples/turb_channel/turb_channel.case
> +      "compute_value": 50,
Great!

2024-09-27 12:06 UTC, timofeymukha commented on src/io/fluid_stats_output.f90
> +               end if
How so? Perhaps I am missing something.

2024-09-27 12:36 UTC, MartinKarp commented on src/io/fluid_stats_output.f90
> +               end if
It depends what people expect I guess. What is nice with this is that when one plots "x+velocity" it will be the x velocity in the new coordinate axes. But for post processing perhaps it would be best to just keep the original axis as far as possible. For averaging in z (which I guess it the most common), it will not make any difference.

2024-09-27 12:52 UTC, timofeymukha commented on src/io/fluid_stats_output.f90
> +               end if
In the end, this is just about the index in the output, right? If I open the .fld, under case

                  output_2d%u%x(i) = u
                  output_2d%v%x(i) = w
                  output_2d%w%x(i) = v

Will the array called v in the field list in Paraview actually hold w? That, I think, we should really avoid. Or are they all just saved as scalars, like it was with kth toolbox?

I think having to figure out this logic based on the plane the data is in most situations going to be an extra hoop to jump. I mean, surely, one knows what component one wants to plot? You will still have to do it for all the other statistics anyway, e.g. you are not swapping vv for ww.

2024-09-27 13:02 UTC, MartinKarp commented on src/io/fluid_stats_output.f90
> +               end if
Pushed a change.

2024-09-27 13:15 UTC, timofeymukha approved these changes

2024-10-01 13:44 UTC, vbaconnet commented on examples/turb_channel/turb_channel.case
> +      "avg_direction": "xz",
Getting a segfault when changing the `avg_direction: "z"` and `start_time: 0.0`, could someone else test it to see if it's just me? :)

```
Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f66cd4218c2 in ???
#1  0x7f66cd420a55 in ???
#2  0x7f66cd25b04f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x563e5d2d2600 in __fld_file_MOD_fld_file_write
	at io/fld_file.f90:396
#4  0x563e5d1b3c90 in __file_MOD_file_write
	at io/file.f90:150
#5  0x563e5d2e4acf in __fluid_stats_output_MOD_fluid_stats_output_sample
	at io/fluid_stats_output.f90:158
#6  0x563e5d1b52b5 in __sampler_MOD_sampler_sample
	at common/sampler.f90:259
#7  0x563e5d149223 in __simulation_MOD_neko_solve
	at /scratch/baconnet/software/neko/src/simulation.f90:93
#8  0x563e5d11f78c in usrneko
	at /scratch/baconnet/software/neko/examples/turb_channel/usr_driver.f90:8
#9  0x563e5d11eaae in main
	at /scratch/baconnet/software/neko/examples/turb_channel/usr_driver.f90:2
```

2024-10-02 09:19 UTC, vbaconnet commented on examples/turb_channel/turb_channel.case
> +      "avg_direction": "xz",
Fixed with commit [81a5d78](https://github.com/ExtremeFLOW/neko/pull/1494/commits/81a5d7897cbe1f14770dec42d1f0ff8fdf5b8545)

2024-10-03 13:25 UTC, Shiyu-Sandy-Du approved these changes

2024-10-03 15:04 UTC, timfelle commented on src/field/mean_field.f90
> +    real(kind=rp), intent(in) :: k
```suggestion
    real(kind=rp), intent(in) :: k
```

2024-10-03 15:04 UTC, timfelle commented on src/fluid/fluid_stats.f90
> +
```suggestion
  private

```

2024-10-03 15:07 UTC, timfelle approved these changes

2024-10-04 07:27 UTC, vbaconnet approved these changes
Tested it on a few cases and it is super nice!

2024-10-04 08:09 UTC, merged