Boundary condition overhaul
ExtremeFLOW/neko pull request #1650
Opened 2024-12-19 22:21 UTC by timofeymukha

# Boundary condition overhaul

## Introduction
This PR is probably the first in a series, aiming to have a better and more transparent implementation of boundary conditions as well as a better experience for the user.
The PR is still in *don't merge* due to a few outstanding issues.

- [ ] Fixing all the examples. We need to remove the built-in boundaries for RBC, lid, and pipe examples.
- [ ] The pressure residual for `hsmg` does not match current develop, when strong pressure boundary conditions are present. For example, in `hemi`. The solver still converges well, but there is something off. I would really love some help diagnosing that, I spent a few days and failed :(. @martinkarp you are perhaps my biggest hope...
- [ ] Implementing the `output_boundary` functionality.
- [ ] Minor things like docstring improvements.
- [ ] There is some instrumentation with `write` and field dumps to help debug point 2. That should be removed.
- [ ] Add documentation for the new JSON once we settle on the naming.

That being said, the PR is sadly really big, and in essense it is ready for review.
These are the main focus points of the PR:
- The user-side changes in JSON, with `boundary_types` being ditched.
- Interface changes in `bc_t`, forcing and `init` and `finalize` for all descendents, as well as some other changes to distinguish between strong and weak boundary conditions.
- Removing all boundary condition type components from `scalar_scheme_t` and `fluid_scheme_t` and instead having only `bc_list_t` components, that are populated by factories, based on the case file.

There are other things, which will be covered below, but I would say those three points are really the core.

## User-side changes

### JSON-file boundary condition definitions
The PR removes the label-based definition of boundary conditions coupled with JSON objects that provide the configuration. For example, a `v` label + and `inflow_condition` object. Instead, a `boundary_conditions` array is introduced, where each object corresponds to one boundary zone, and all the configuration of the boundary is done in that object. Here is `hemi`

```json
        "boundary_conditions": [
        {
            "type": "symmetry",
            "zone_index": 1
        },
        {
            "type": "no_slip",
            "zone_index": 2
        },
        {
            "type": "outflow",
            "zone_index": 3
        },
        {
            "type": "blasius_profile",
            "zone_index": 4,
            "approximation": "sin",
            "delta": 0.6,
            "freestream_velocity": [1.0, 0.0, 0.0]
        }
        ],
```

So, I had to make up a name for each of the boundaries. **This is something we should approve together**. Here is a table with all the boundary conditions for the fluid.

| Boundary Condition         | Description            |
|----------------------------|------------------------|
| symmetry                   | symmetry               |
| velocity_value             | A Dirichlet condition for velocity                       |
| no_slip                    | A no-slip wall. Didn't want to use "wall" because e.g. wall models are also at walls, etc.                       |
| outflow                    | The "o" boundary                       |
| normal_outflow             | The "on" boundary                       |
| outflow+dong               | The "o+dong"                       |
| normal_outflow+dong        | The "on+dong"                       |
| shear_stress               | The "sh"                       |
| user_velocity              | The `field_dirichlet_vector_t` user-defined bc for velocity                       |
| user_pressure              | The `field_dirichlet_t` user-defined bc for pressure                       |
| user_velocity_pointwise    | The old pointwise user-defined bc for velocity                       |
| wall_model                 | The "wm" boundary                       |

So, all of these are up for discussion. Just a few comments from my side: I was swaying between using "mathy" names like e.g. "velocity_dirichlet" and more "physical" ones, like "velocity_value". I went for the latter, because some of the bcs for the fluid are too complex to concicely define in a mathy way, which is also reflected in Nek5000's and ours way of naming the bc labels.

As seen below, for the scalar I went for "dirichlet" and "neumann" instead, since the physical meaning changes depending on what the scalar represents. However, maybe it is more consitent to go with something like "value" and "flux". Opinions welcome!

| Boundary Condition         | Description            |
|----------------------------|------------------------|
| dirichlet                  | A "d" bounary               |
| neumann             | An "n" boundary             |

All the boundary condition require a `zone_index` keyword to determine the index of the zone in the list of labeled zones. **Built-in zones are no longer supported**. The other keywords are pretty much unchanged, see e.g. the Blasius configuration for hemi--it just moved from its own object into the `boundary_conditions` item.

### The `field_dirichlet_t` user interface

Now no longer accepts a solver name, and the second argument is a `field_dirichlet_t` instead of `bc_list`. The namse of the dummy fields one changes matches the unerlying unknown. So, by default for velocity it is `u`, `v`, `w`, and for the scalar it is `s`. So, the user should distinguish the solver based on the field name.
Please see that updated `cyl_bl.f90`.

As seen above, I split the condition for pressure and velocity in the JSON. This is reflected in the code. **So currently you cannot change both pressure and velocity in one go**, you will never get a field list containing both of them. **If this is really bad, it should be possible to fix**.

@vbaconnet 

## Developer-side changes

### The changes in `bc_t`

#### Type construction
One of the big issues we had was the lack of deferred procedures for `init` and `finalize`. These are now added, which removes a lot of delicate handling of constuction etc, that we currently have in the code. For all types, include those with nested bcs, one should be able to `init`, mark the boundary, and `finalize`.

@martinkarp Could you please check that I didn't skew up some ordering in `symmetry_t` and `non_normal_t`? I remember that recent PR where you fixed some issues... I moved the whole procedure of finding the normal etc to `finalize`, and I think things should be ok.

The deferred constructor handles parsing the JSON. Most types also have an `init_from_components`, which avoids using JSON, when not needed.

#### Distinction between weak and strong boundary conditions

In order not to have huge `select type` statements in the `_scheme` types, I needed to be able to distinguis between strong and weak bcs, which are applied at different stages of the `_step()` routines. So, a `logical :: strong` component is added to `bc_t`. 

There is an issue however: the mixed conditions like `shear_stress`. They have both a strong and a weak component.
By convention, I currently mark them as `weak`. But it was still unclear on how to run `apply_scalar` / `apply_vector` on them. These conditions currently contain nested bcs, which are responsible for handling the weak and strong parts. For example, the `shear_stress_t` has a `symmetry_t` for no-penetration and `neumann_t` for setting the stress.

One option would be to put these nested bcs directly into the `bc_list`s in the `*_scheme`s. This is kind of what is done now. But I really wanted to have at most one `bc_t` for each boundary in the list. So, the solution I ended up with was adding a `logical :: strong` dummy argument to the `apply_scalar` / `apply_vector` routines. This way, the caller can signal which part of a mixed bc--weak or strong--should be applied. For example, in `fluid_pnpn_t`

```fortran
      ! Add Neumann bc contributions to the RHS
      call this [...]

2024-12-20 07:14 UTC, timfelle reviewed
Brilliant work. It is a really needed update at this point.

A  note for the whole strong vs weak thing.
Why not signify `weak` with a variable as well instead of infering that `not strong` means weak?
So you would have a variable, not signifying "is the bc strong or weak" but two each signifying "does this bc modify the strong and weak forms".

In regards to the list, I think we could have two generics of `bc_list`, `apply_stong` and `apply_weak` to make it completely clear at a glance when what is called, instead of someone just writing ` call bc_list%apply_vector(f_x, f_y, f_z, n, t, tstep, .false.)` and then we need to remember what did the logical signify, was it strong or weak? 

A note on inputs for apply.
How about getting rid of `get_device_ptr` from the bc_list?
We have everything nicely organised in the `field_t` and we are essentially always operating on that anyway. And, implicitly calling device code here, when we attempt to do so explicitly most other places feel a bit off.
This was actually the plan with the PR you asked me to wait with, to introduce the interface and slowly go through and replacing the calls before removing the old interface. But i guess we could consider just doing it here instead.

2024-12-20 08:26 UTC, MartinKarp commented
Yeah, really great Timofey! I will start checking the hsmg and mixed bcs part :)

2024-12-20 08:44 UTC, MartinKarp reviewed
Just some first few comments.

2024-12-20 08:44 UTC, MartinKarp commented on src/bc/bc.f90
> -    if(trim(bc_key) .eq. 'o' .or. trim(bc_key) .eq. 'on' &
This logic is currently needed for the fast-diagnaolization method in hsmg. The best solution for this would be to proabably pass down strong and weak bcs to the hsmg, schwarz, fdm combo directly to avoid having this flag in the mesh directly. Currently I realize this solution is also a bit hardcoded for only the fluid solve.

I can have a look at it, but I guess the timeline would not be right now.

2024-12-20 08:44 UTC, MartinKarp commented on examples/cylinder/cylinder.case
> +            "zone_index": 5
Would it be easy to make it possible to mark several zonesin one line?

2024-12-20 09:17 UTC, timofeymukha commented
> Yeah, really great Timofey! I will start checking the hsmg and mixed bcs part :) It is only hsmg that differs and the solver works correctly with jacobi?

Thank you! Yes, as far as I could tell the jacobi always gave the same residuals.

2024-12-20 11:00 UTC, timofeymukha commented on examples/cylinder/cylinder.case
> +            "zone_index": 5
I think it would. Essentially, the factory would loop over the indices and mark them.

2024-12-20 11:04 UTC, timofeymukha commented on src/bc/bc.f90
> -    if(trim(bc_key) .eq. 'o' .or. trim(bc_key) .eq. 'on' &
Oh, ok! I guess I can add this in the setup_bc_ for the fluid. So the distinction here is basically a strong pressure bc gets a 1 and all the rest gets a 2, right?

2025-01-06 07:18 UTC, timfelle commented on src/fluid/fluid_pnpn_bc_fctry.f90
> +    end if
Since the if block is this large, we might be better off with a 'select case'.

```suggestion
    select case (trim(type))
      case ("outflow", "normal_outflow")
       allocate(zero_dirichlet_t::object)
      case ("outflow+dong", "normal_outflow+dong")
       allocate(dong_outflow_t::object)
      case ("user_pressure")
       allocate(field_dirichlet_t::object)
       select type(obj => object)
         type is(field_dirichlet_t)
          obj%update => user%user_dirichlet_update
          call json%add("field_name", scheme%p%name)
       end select
      case default
       do i = 1, size(FLUID_PNPN_KNOWN_BCS)
          if (trim(type) .eq. trim(FLUID_PNPN_KNOWN_BCS(i))) return
       end do
       call neko_type_error("fluid_pnpn boundary conditions", type, &
            FLUID_PNPN_KNOWN_BCS)
    end select
```

2025-01-06 07:18 UTC, timfelle commented on src/fluid/fluid_pnpn_bc_fctry.f90
> +    end if
Same goes here, the 'select case' block is easier to read, especially since we
only trim once.

```suggestion
    select case (trim(type))
      case ("symmetry")
       allocate(symmetry_t::object)
      case ("velocity_value")
       allocate(inflow_t::object)
      case ("no_slip")
       allocate(zero_dirichlet_t::object)
      case ("normal_outflow", "normal_outflow+dong")
       allocate(non_normal_t::object)
      case ("blasius_profile")
       allocate(blasius_t::object)
      case ("shear_stress")
       allocate(shear_stress_t::object)
      case ("wall_model")
       allocate(wall_model_bc_t::object)
       ! Kind of hack, but maybe OK? The thing is, we need the nu for
       ! initing the wall model, and forcing the user duplicate that there
       ! would be a nightmare.
       call json%add("nu", scheme%mu / scheme%rho)
      case ("user_velocity")
       allocate(field_dirichlet_vector_t::object)
       select type(obj => object)
         type is(field_dirichlet_vector_t)
          obj%update => user%user_dirichlet_update
       end select
      case ("user_velocity_pointwise")
       allocate(usr_inflow_t::object)
       select type(obj => object)
         type is(usr_inflow_t)
          call obj%set_eval(user%fluid_user_if)
       end select
      case default
       do i = 1, size(FLUID_PNPN_KNOWN_BCS)
          if (trim(type) .eq. trim(FLUID_PNPN_KNOWN_BCS(i))) return
       end do
       call neko_type_error("fluid_pnpn boundary conditions", type, &
            FLUID_PNPN_KNOWN_BCS)
    end select
```

2025-01-06 07:18 UTC, timfelle commented on src/fluid/fluid_pnpn_bc_fctry.f90
> +    if (type .ne. "normal_outflow" .and. type .ne. "normal_outflow+dong") then
Missing some trimming.

```suggestion
    if (trim(type) .ne. "normal_outflow" .and. &
         trim(type) .ne. "normal_outflow+dong") then
```

2025-01-06 07:48 UTC, timfelle commented on src/fluid/fluid_pnpn.f90
> +     procedure, pass(this) :: pnpn_setup_bcs => fluid_pnpn_setup_bcs
How about lifting the bc setup to a deferred operator on the scheme itself?
Would all schemes not need to know how to deal with boundary conditions?

2025-01-13 09:14 UTC, timfelle commented on src/fluid/fluid_pnpn.f90
> +                write(*,*) "MARKING SHEAR_STRESS IN VELOCITY BLISTS"
Could we make these write statements part of the log. Possibly with the debug
level?

2025-01-13 10:03 UTC, timfelle commented on src/fluid/fluid_scheme.f90
>        call this%bdry%init(this%dm_Xh, 'bdry')
Maybe there is no need to have this in a separate subroutine. Probably could be
with the other IO options.

2025-01-17 16:41 UTC, timofeymukha commented
Dear all, an update from today.

- Each boundary can now take several zones, so zone_index is renamed to zone_indices, which is an array.
- I have implemented the checks on zone_indices, that we discussed, as @Mr-2c suggested.
- I have updated all the example case files.
- I have 100% residual agreement on all the examples except
  - immersed_bunny
  - turb_pipe (this is really a surprise)

  This has to be investigated further.

- I removed most of the extra debug output.


Sadly, documentation and the output_boudary field handling I could not fit, so it is shifted to next week.

2025-01-23 14:27 UTC, timofeymukha commented
Removing "don't merge"!!

Added documentation, updated examples, and redon the functionality for `output_boundary`. The numbering is a little bit changed in the latter: periodic bcs are "marked" with 0 (by doing nothing), and outflow had to be lumped with normal_outflow because it is impossible to distinguish them from the instantiated types at the moment.

I have addressed almost all of your comments. A few things from @timfelle are missing, which I am postponing to next PRs.
- Potentially adding a "weak" attribute to bc_t to have mixed bcs marked as both strong and weak.
- Debug-level log output in bc setup.
- Make the setup_bc defferred in scalar_scheme (done in the fluid_scheme).

2025-01-24 09:06 UTC, timfelle approved these changes

2025-01-24 09:06 UTC, timfelle commented on src/krylov/pc_hsmg.f90
Why this extra empty line?

2025-01-24 09:06 UTC, timfelle commented on src/multigrid/phmg.f90
> +                  bc_j%marked_facet)
No need to break this line anymore.

```suggestion
             call this%phmg_hrchy%lvl(i)%bc%mark_facets(bc_j%marked_facet)
```

2025-01-24 09:06 UTC, timfelle commented on src/scalar/scalar_pnpn.f90
> +  use comm
Missing `only`

2025-01-24 09:06 UTC, timfelle commented on src/scalar/scalar_pnpn.f90
> +    end if
This can be done by adding the `NEKO_LOG_DEBUG` to the `message` commands
instead. No need to manually do the if statement

2025-01-24 09:06 UTC, timfelle commented on src/case.f90
> +            '.', back = .true.) - 1))//'_lb.nmsh'
```suggestion
            '.', back = .true.) - 1)) // '_lb.nmsh'
```

2025-01-24 10:18 UTC, MartinKarp requested changes
I think the field_update should be made sure to be called on all ranks, and preferrably not called too many times per time step, but otherwise I think it looks really great. I guess I will have a look at the update function later as well, but I think we should try to emulate the current functionality for now.

2025-01-24 11:40 UTC, timofeymukha commented on src/fluid/fluid_pnpn.f90
> +    write(log_buf, '(A)') '  periodic                        = 0'
There is not such thing as a zone without a bc anymore, you have to assign all zones a bc, or the solver will crash with an appropriate error. Periodic is the only exception.

But still perhaps I can grab from the mesh as you say.

2025-01-24 11:43 UTC, timofeymukha commented on src/scalar/scalar_pnpn.f90
> +  use comm
I think `comm` is one of those exceptions we have.

2025-01-24 11:46 UTC, timofeymukha commented on src/bc/symmetry.f90
> +    real(kind=rp), parameter :: TOL = 1d-3
I add a TODO

2025-01-24 11:47 UTC, timofeymukha commented on src/bc/bc.f90
>    use device
`device` and `comm` are exceptions, right?

2025-01-24 11:51 UTC, timofeymukha commented on src/bc/symmetry.f90
>      real(kind=rp), parameter :: TOL = 1d-3
TOL is used!

2025-01-24 11:54 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
Right! So, I just leave if(strong_), which is consistent across ranks.

2025-01-24 11:56 UTC, timfelle commented on src/scalar/scalar_pnpn.f90
> +  use comm
Yes `comm` was an exception to it. I have just never been able to reproduce any issues with it.

2025-01-24 11:57 UTC, timfelle commented on src/bc/bc.f90
>    use device
I don't think `device` was an exception no.

2025-01-24 12:04 UTC, timfelle commented on src/bc/symmetry.f90
> +    real(kind=rp), parameter :: TOL = 1d-3
BTW, this tolerance is not used. The other one is. And please specify the precision `1.0e-3_rp`

2025-01-24 12:05 UTC, timfelle commented on src/bc/symmetry.f90
> +      sx = 0d0
```suggestion
      sx = 0.0_rp
```

2025-01-24 12:14 UTC, timfelle commented on src/bc/blasius.f90
> +     procedure, pass(this) :: init_from_components => &
Sure, I just checked our coding guidelines. There it also states `init_from_components` should be an initializer and we should have a generic `init` which chooses the json or attributes. Let's go back and fix this across other parts of the code in a new PR.

2025-01-24 12:47 UTC, timfelle commented on src/bc/symmetry.f90
> +    class(symmetry_t), intent(inout), target :: this
my understanding is that if you do a `=>` to something, it must be a target. But we don't in this function. Question is whether it also is required if any of the subroutines downstream does the pointer assignment @njansson?

2025-01-24 14:20 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
I think 2 is really a very tiny corner case. I imagine that if s on the boundary depends on u on the boundary (which is already a pretty unusual thing, or?), it is the value at i+1 of u that you want typically, that is, to be synced in time.

Regarding 1, is the problem with some rank not calling the update function that if one putts some MPI-syncing code in it, it will get stuck?
I am not a strong proponent of that if statement for the bc_list, probably better to just consistently do things for zero-sized bcs. On the other hand, I think it would be very nice if the update can be inside the bc code like right now, unless we really cannot avoid splitting it, as we had before.

2025-01-24 14:24 UTC, timofeymukha commented on src/bc/bc.f90
>    use dofmap, only : dofmap_t
@timfelle I think I am getting one of those strage errors now: c_associated is in the `use`,  but `nvfortran` is complaining.

2025-01-24 14:35 UTC, timfelle commented on src/bc/bc.f90
>    use dofmap, only : dofmap_t
`c_associated` is not part of `device`. It is part of the `iso_c_binding`. So add 
`use iso_c_binding, only: c_associated`

2025-01-24 14:37 UTC, timfelle commented on src/bc/bc.f90
>    use dofmap, only : dofmap_t
This is exactly the kind of implicit inclusion we can avoid by always using only, everywhere.

2025-01-24 14:43 UTC, MartinKarp commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
Yeah lets not think about 2 for now as I dont think it is in the scope of the PR really and I am not sure exactly what one wants.

I think another issue with allowing calls to bcs of length 0 might be similar to when we call device subroutines with length 0 and we get segfaults. If that doesnt happen we can just remove the check and do like we do here. The I think we can be happy.

In the end what I want to support is doing things like I did in the example for interpolation: https://github.com/ExtremeFLOW/neko/blob/2bb71482a3cf2392c80f9a12ac0f8ca24d8dac27/examples/interpolation/recycling.f90

If that is all good I am a happy camper

2025-01-24 15:07 UTC, timofeymukha commented on src/bc/bc.f90
>    use dofmap, only : dofmap_t
Oooh, ok. Yes, I totally agree. As much `only` as bad compilers allow!

2025-01-24 15:18 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
OK. Removing the statement on the CPU seems to work. I guess we need to check on a GPU somewhere.

2025-01-24 15:30 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
I pushed a version with the `if` commented out. I guess it needs to be tested on a reasonably big case so that one has multiple ranks with the GPU. @MartinKarp can you make such a test run? I don't really have good access to a machine right now, although I could perhaps try to get onto Dardel.

2025-01-27 07:59 UTC, MartinKarp commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
https://stackoverflow.com/questions/19022725/running-zero-blocks-in-cuda

This is more or less the issue we have. I have made some functios where we check the size, but in most places we will get an error if we run device kernels of size 0.

My feeling for now is to make each bc in apply device check the size and act correctly.

2025-01-27 08:08 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
OK, so just not launch anything and return if the size is 0 for device_apply routines?

2025-01-27 08:14 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
Hmm, but for the field_dirichlet we cannot do that, right? Basically due to original reason why you added the comment. There could be both a kernel launch and some MPI communication in the user routine, and for the sake of the latter, we always have to launch the `update`, right? So I guess it will be up to the user to only launch kernels if the size is > 0?

2025-01-27 08:18 UTC, timofeymukha commented on src/bc/field_dirichlet.f90
> +    if (strong_ .and. this%msk(0) .gt. 0) then
A reasonable solution is then maybe to add and `ignore_empty` argument to `bc_list.append`, defaulting to `.true.`, so everything is retained as is for most of the bcs. And for the `field_dirichlet` and `field_dirichlet_vector` we force-add it, and then the user code should be careful with kernel launches (which we will add to the already extensive documentation).

2025-01-28 07:58 UTC, timfelle commented on src/bc/bc.f90
> +       type(json_file), intent(inout) ::json
```suggestion
       type(json_file), intent(inout) :: json
```

2025-01-28 08:08 UTC, timofeymukha commented
As an update after the discussion with @MartinKarp (see also dialog above).
- The bc_list will add bcs with 0 mask size. So all ranks have the same bcs.
- In device_apply_* routines, kernels are only launched id this%mask > 0, because otherwise the kernel may crash.
- In the field_dirichlet*, the `update` will be called even with 0 mask in case the user added MPI calls. But the masked copy kernel will not be launched if the mask is 0.

2025-01-28 09:06 UTC, MartinKarp approved these changes

2025-01-28 09:07 UTC, timofeymukha commented
@njansson Merge? :-)

2025-01-28 19:28 UTC, njansson approved these changes

2025-01-28 19:29 UTC, njansson commented
> @njansson Merge? :-)

Go! 🍶

2025-01-29 06:24 UTC, timofeymukha commented on src/bc/wall_model_bc.f90
> +       type(json_file) params_
Will address!

2025-01-29 06:54 UTC, timfelle approved these changes

2025-01-29 07:15 UTC, merged