Feature/field registry
ExtremeFLOW/neko pull request #614
Opened 2022-09-20 10:26 UTC by timofeymukha

This PR will be use to track the developments as per issue #612
I currently have a crude skeleton, which appears to work in the sense that I can run the tgv example.

2022-09-20 10:30 UTC, timofeymukha commented
`  2   src/field/field_registry.f90                       10.00      32`
Top score from the linter? :-)

2022-09-20 11:15 UTC, njansson commented
Isn't this PR missing an updated `Makefile.am` ?

2022-09-21 11:15 UTC, njansson requested changes

2022-09-21 11:15 UTC, njansson commented on src/fluid/fluid_method.f90
> +   this%p => neko_field_registry%get_field('p')
Minor formatting things
```suggestion
    call neko_field_registry%add_field(this%dm_Xh, 'u')
    call neko_field_registry%add_field(this%dm_Xh, 'v')
    call neko_field_registry%add_field(this%dm_Xh, 'w')
    call neko_field_registry%add_field(this%dm_Xh, 'p')
    this%u => neko_field_registry%get_field('u')
    this%v => neko_field_registry%get_field('v')
    this%w => neko_field_registry%get_field('w')
    this%p => neko_field_registry%get_field('p')
```

2022-09-21 11:15 UTC, njansson commented on src/fluid/fluid_method.f90
> +   this%w => neko_field_registry%get_field('w')
Minor formatting things
```suggestion
    call neko_field_registry%add_field(this%dm_Xh, 'u')
    call neko_field_registry%add_field(this%dm_Xh, 'v')
    call neko_field_registry%add_field(this%dm_Xh, 'w')
    this%u => neko_field_registry%get_field('u')
    this%v => neko_field_registry%get_field('v')
    this%w => neko_field_registry%get_field('w')
```

2022-09-21 11:15 UTC, njansson commented on src/fluid/fluid_method.f90
> +     type(field_t), pointer :: p         !< Pressure
Do we need to nullify these? Or I guess we will never try to free them from `fluid_method`

2022-09-21 11:41 UTC, njansson approved these changes

2022-09-21 12:00 UTC, merged