Extending advection interface to scalars
ExtremeFLOW/neko pull request #622
Opened 2022-09-27 09:28 UTC by timofeymukha

This will track the progress on scalars. Currently extending various interfaces to support scalars.
This first commit extends advection, I would appreciate if @njansson or @MartinKarp took a look at some point.

Immediate next steps:
- sources
- makeabd/bdf

2022-09-28 07:58 UTC, timofeymukha commented
Don't merge!!

2022-09-29 13:05 UTC, timofeymukha commented
CPU checks pass, need to fix the device stuff.

2022-10-03 08:21 UTC, njansson commented
For the `abbdf` routines, now we have fluid and scalar under `fluid/`, wouldn't it be more clear if one had the fluid parts (as now) under `fluid/` and a similar one (but for scalar fields) under `scalar/`?

2022-10-04 11:31 UTC, timofeymukha commented
> For the `abbdf` routines, now we have fluid and scalar under `fluid/`, wouldn't it be more clear if one had the fluid parts (as now) under `fluid/` and a similar one (but for scalar fields) under `scalar/`?

@njansson , my idea was to instead rename the classes, I'm currently using `rhs_maker` for the module name but haven't renamed the files yet.

2022-10-04 12:00 UTC, njansson commented
> > For the `abbdf` routines, now we have fluid and scalar under `fluid/`, wouldn't it be more clear if one had the fluid parts (as now) under `fluid/` and a similar one (but for scalar fields) under `scalar/`?
> 
> @njansson , my idea was to instead rename the classes, I'm currently using `rhs_maker` for the module name but haven't renamed the files yet.

That's excellent, but somehow not sure about having the scalar `res_maker` in a folder called `fluid`. But that might just be me

2022-10-04 12:04 UTC, timofeymukha commented
> > > For the `abbdf` routines, now we have fluid and scalar under `fluid/`, wouldn't it be more clear if one had the fluid parts (as now) under `fluid/` and a similar one (but for scalar fields) under `scalar/`?
> > 
> > 
> > @njansson , my idea was to instead rename the classes, I'm currently using `rhs_maker` for the module name but haven't renamed the files yet.
> 
> That's excellent, but somehow not sure about having the scalar `res_maker` in a folder called `fluid`. But that might just be me

Yes, the res_maker should be moved, you are right.

2022-10-07 13:45 UTC, njansson requested changes

2022-10-07 13:45 UTC, njansson commented on src/case.f90
> +    write(*,*) "FLUID INIT"
```suggestion
```

2022-10-07 13:45 UTC, njansson commented on src/common/bcknd/device/opencl/rhs_maker.c
> +  CL_CHECK(clSetKernelArg(kernel, 19, sizeof(int), n));
```suggestion
  CL_CHECK(clSetKernelArg(kernel, 0, sizeof(cl_mem), (void *) &s_lag));
  CL_CHECK(clSetKernelArg(kernel, 1, sizeof(cl_mem), (void *) &s_laglag));
  CL_CHECK(clSetKernelArg(kernel, 2, sizeof(cl_mem), (void *) &fs));
  CL_CHECK(clSetKernelArg(kernel, 3, sizeof(cl_mem), (void *) &s));
  CL_CHECK(clSetKernelArg(kernel, 4, sizeof(cl_mem), (void *) &B));
  CL_CHECK(clSetKernelArg(kernel, 5, sizeof(real), rho));
  CL_CHECK(clSetKernelArg(kernel, 6, sizeof(real), dt));
  CL_CHECK(clSetKernelArg(kernel, 7, sizeof(real), bd2));
  CL_CHECK(clSetKernelArg(kernel, 8, sizeof(real), bd3));
  CL_CHECK(clSetKernelArg(kernel, 9, sizeof(real), bd4));
  CL_CHECK(clSetKernelArg(kernel, 10, sizeof(int), nbd));
  CL_CHECK(clSetKernelArg(kernel, 11, sizeof(int), n));
```

Must match the number of arguments in the kernel, otherwise it will cause a runtime error during JIT+run

2022-10-07 13:45 UTC, njansson commented on src/common/bcknd/device/opencl/rhs_maker.c
> +  CL_CHECK(clSetKernelArg(kernel, 13, sizeof(int), n));
```suggestion
  CL_CHECK(clSetKernelArg(kernel, 0, sizeof(cl_mem), (void *) &fs_lag));
  CL_CHECK(clSetKernelArg(kernel, 1, sizeof(cl_mem), (void *) &fs_laglag));
  CL_CHECK(clSetKernelArg(kernel, 2, sizeof(cl_mem), (void *) &fs));
  CL_CHECK(clSetKernelArg(kernel, 3, sizeof(real), rho));
  CL_CHECK(clSetKernelArg(kernel, 4, sizeof(real), ext1));
  CL_CHECK(clSetKernelArg(kernel, 5, sizeof(real), ext2));
  CL_CHECK(clSetKernelArg(kernel, 6, sizeof(real), ext3));
  CL_CHECK(clSetKernelArg(kernel, 7, sizeof(int), n));
```
must match number of actual arguments

2022-10-07 13:45 UTC, njansson commented on src/common/pnpn_res_fctry.f90
> +!> Defines Pressure residual factory for the Pn-Pn formulation
Is it still valid as "Pressure" only?

2022-10-07 13:45 UTC, njansson commented on src/scalar/bcknd/sx/scalar_residual_sx.f90
> +!> Residuals in the Pn-Pn formulation (CPU version)
```suggestion
!> Residuals in the Pn-Pn formulation (SX version)
```

2022-10-07 14:13 UTC, timofeymukha commented on src/common/pnpn_res_fctry.f90
> +!> Defines Pressure residual factory for the Pn-Pn formulation
@njansson It always had both pressure and velocity residual factories there, so the answer is no I guess.  But this is not an update. This file should essentially have just been moved and not modified. The stuff for scalars have been moved to src/scalar as per our previous discussion on slack

2022-10-07 14:15 UTC, timofeymukha commented on src/common/pnpn_res_fctry.f90
> +!> Defines Pressure residual factory for the Pn-Pn formulation
@njansson And now that I think about it, it should not actually have been moved, it belongs in fluid. The thing is that I first added the scalar residual to the same file and moved it to common. But then, I separated the scalar stuff...

2022-10-07 14:16 UTC, njansson approved these changes

2022-10-07 14:18 UTC, njansson commented on src/common/pnpn_res_fctry.f90
> +!> Defines Pressure residual factory for the Pn-Pn formulation
@timofeymukha We can either move it back now or in another PR

2022-10-07 15:03 UTC, merged