3D Statistics - Draft
ExtremeFLOW/neko pull request #720
Opened 2022-11-11 14:16 UTC by MartinKarp

Here is a draft for the 3D statistics in Neko. 
It computes all 44 averaged quantities that are present in the Nek5000 toolbox.
It outputs the mean flow field i.e. <u>, <v>, <w>, <p> in the file mean_field.nek5000 and all other (40) stats in the stats.nek5000. The order should probably be documented so that we can postprocess the fields more easily.
The time interval over which one computes the averages is decided by the parameter stats_sample_time. We should maybe also add one for how often we sample (Now its every time step, but we can probably reduce it to every 10 or so). 

I have not tested it completely yet so please dont merge. If you have the time, please try it out.

2022-11-11 15:00 UTC, njansson commented on src/simulation.f90
> +    if (C%params%output_chkp .or. t .lt. C%params%T_end) then
The intent is to let the sampler take cares of the logic so we can keep the time-stepping loop uncluttered

2022-11-11 15:00 UTC, njansson commented on src/case.f90
> +       call C%sample_means%add(C%f_stats_output)
See the comment in `simulation.f90` regarding several samplers

2022-11-11 15:02 UTC, njansson commented on src/fluid/fluid_stats.f90
> +! Copyright (c) 2021, The Neko Authors
```suggestion
! Copyright (c) 2022, The Neko Authors
```

2022-11-11 15:03 UTC, njansson commented on src/io/fluid_stats_output.f90
> +! Copyright (c) 2021-2022, The Neko Authors
```suggestion
! Copyright (c) 2022, The Neko Authors
```
Or did we add this before?

2022-11-11 15:04 UTC, njansson commented on src/io/mean_flow_output.f90
> +       call device_memcpy(this%mf%w%mf%x, this%mf%w%mf%x_d,  this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
```suggestion
       call device_memcpy(this%mf%p%mf%x, this%mf%p%mf%x_d, this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
       call device_memcpy(this%mf%u%mf%x, this%mf%u%mf%x_d,  this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
       call device_memcpy(this%mf%v%mf%x, this%mf%v%mf%x_d,  this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
       call device_memcpy(this%mf%w%mf%x, this%mf%w%mf%x_d,  this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
```

2022-11-11 15:05 UTC, njansson commented on src/case.f90
> +     type(sampler_t) :: sample_means
See comment in `simulation.f90` about multiple samplers.

2022-11-11 15:06 UTC, njansson commented on src/field/field.f90
> +    procedure, pass(f) :: free => field_free
Why do we change to type bound procedures here, as far as I can see they are not used throughout the code-base

2022-11-11 15:08 UTC, njansson commented
Would be great if also @adampep or @pschlatt1 also have look if this covers the necessary statistics. I've only reviewed the code structure etc.

2022-11-12 11:15 UTC, timofeymukha commented
Hello, here are some comments.

* I don't like the tight integration between the statistics and `fluid_method`. It seems like only `init` is called there, and I would perhaps just move that outside, maybe directly to `simulation`. Later, I am hoping we can fit this into #722 , which is one of the reasons I started that discussion now.
* There is a fundamental issue with having a preset number of fields. This is a good start for us now, so that our group can do the standard simulations we are used to and get the needed statistics, but.
  - For 99% of people out there, anything beyond 2nd order statistics is rarely needed. I would say even stuff like <p'v'> is a rare beast.
  - On the other hand, these 44 fields will not cover everything. For example, I compute <t'v'> right now for ABLs, where t is temperature. This is the reason why everyone has their own little version of the statistics code now in our group for Nek :-). So there needs to eventually be a mechanism to easily add a field to statistics. 
Something like this in psuedo-json in the par file
```
statisitcs
{
    fields = ["t", "tv"] # will grab from registry by name, "tv" should be computed in usercheck
    orders = [2, 1] # will compute mean and mean of square for t and only mean for tu.
}
```
* I think there is definitely room for a "prepackaged" set of values like here, because putting everything in manually is tedious. A question here is whether to just compute all the raw statistics or e.g. directly the k budget. We currently do it one way for 2d stats and the other for 3d in Nek :-). Perhaps @pschlatt1 and @adampep could comment on this.

2022-11-21 15:06 UTC, MartinKarp commented on src/simulation.f90
> +    if (C%params%output_chkp .or. t .lt. C%params%T_end) then
Yes, but I also want to make sure to sample when the simulation ends, otherwise it is possible to lose a lot of data.

2022-11-21 15:09 UTC, MartinKarp commented on src/simulation.f90
> +       call C%sample_means%sample(t)
I think this will be rather difficult as the conditions to sample can be very different between different fields, I think it makes sense to kind of group things in each sampler, with similar conditions for nowe, but maybe thats me.

2022-11-21 15:09 UTC, MartinKarp commented on src/field/field.f90
> +    procedure, pass(f) :: free => field_free
I think we should ahve type bound procedures for every class for init and so on. I just feel that would make things more consistent.

2022-11-21 15:13 UTC, MartinKarp commented
Yeah, we can move the init. The framework structure seems like a good idea, but would each simulationobject or so also handle all things related to it such as io and so on?

Yeah, we should have a simple way to add statistics. Right now this requires quite some work for it to work. Here I mostly wanted to just output everything so that the dqata from the simulations on LUMI are dumped to file.

2022-11-21 16:49 UTC, timofeymukha commented
> Yeah, we can move the init. The framework structure seems like a good idea, but would each simulationobject or so also handle all things related to it such as io and so on?
> 
> Yeah, we should have a simple way to add statistics. Right now this requires quite some work for it to work. Here I mostly wanted to just output everything so that the dqata from the simulations on LUMI are dumped to file.

Difficult to say about IO, since there is so may factors, like formats and file-sizes. But generally I would say each component should be quite independent and use the registry as the communication point.

2022-11-21 22:29 UTC, njansson commented on src/field/field.f90
> +    procedure, pass(f) :: free => field_free
Yes, that's a good point, but we should make sure that init is overloaded for both external and internal dof such that we don't break e.g. `examples/poisson`

2023-01-31 19:14 UTC, timofeymukha commented
@MartinKarp could you please add a short module documentation to src/io/fld_file_data.f90?

2023-01-31 19:19 UTC, MartinKarp commented
Yeah, will do. I am aiming to have this branch "finished" by the end of the week.

2023-02-06 13:27 UTC, MartinKarp commented
I have now added two postprocessing tools. 

`average_fields` which takes a series of fluid snapshots and computes the temporal average of the fields stored in the files.

The other is `postprocess_fluid_stats` which takes three files as input: the mesh, a fluid file with the temporal average of the flowfield and a file with the temporal averages outputted by the fluid_stats module. 

Currently, we only post-process and output the reynolds stresses and the gradients of the mean flow field, but as we collect many other moments during the simulation the postprocessing can be easily extended to other statistical quantities that are used in the original KTH stats toolbox.

2023-04-26 14:21 UTC, MartinKarp commented
Hi all!
I have updated the PR a bit, particularly regarding how we sample/write/output fields of interest. There are a two things that need to be fixed before merging though.

- [ ] Testing, both on GPU and CPU and on some different systems.
- [ ] Where should field_list_t be? I have left it in field_t as I quite like that the functionality needed to create an array of pointers to fields is included when loading the field module

There are probably many other issues, but please have a look and say what you think.

2023-04-27 07:04 UTC, njansson commented on src/field/mean_field.f90
> +    this%mf => neko_field_registry%get_field(name)
Is there a reason for using the registry here? Do we need access to this field outside of a case?

2023-04-27 07:05 UTC, njansson commented on src/field/mean_field.f90
> +    end if
```suggestion
    this%mf = 0.0_rp  
```

2023-04-27 07:07 UTC, njansson commented on src/fluid/fluid_method.f90
> +  use fluid_stats
Related to @timofeymukha  earlier comment, should we really have statistics as part of the fluid scheme?

2023-04-27 07:11 UTC, njansson commented on src/field/field.f90
> +    procedure :: field_init_external_dof, field_init_internal_dof
This depends on what the decision will be on #794, thus not sure we should introduce these changes now in this pr.

2023-04-27 08:34 UTC, MartinKarp commented on src/field/field.f90
> +    procedure :: field_init_external_dof, field_init_internal_dof
It does not remove the previous functionality, so in my mind I think it is. Otherwise I can change it back and change the inits in fluid_stats.

2023-04-27 08:36 UTC, MartinKarp commented on src/fluid/fluid_method.f90
> +  use fluid_stats
I think for these pre-set values that correspond to the KTH toolbox it is ok as they are tightly coupled to the fluid method. When we add userstats I think it makes sense to have them in simulation/case instead.

2023-04-27 08:39 UTC, MartinKarp commented on src/field/mean_field.f90
> +    this%mf => neko_field_registry%get_field(name)
Yes, I think I use the field_registry quite extensively to obtain the mean field values and such. It might also be convenient when we start adding user-defined stats to make sure that the mean fields can be accessed in the registry.

2023-04-27 09:25 UTC, MartinKarp commented on src/field/mean_field.f90
> +    this%mf => neko_field_registry%get_field(name)
After thinking about it a bit I am more divided whether it is correct to add to the registry.

2023-04-27 09:42 UTC, MartinKarp commented on src/field/mean_field.f90
> +    this%mf => neko_field_registry%get_field(name)
I am fixing this

2023-04-28 15:57 UTC, njansson commented on src/common/sampler.f90
> +    call neko_log%message('---Adding write output---')
neko_log%section is the way to go

2023-04-28 15:59 UTC, njansson commented on src/case.f90
> +       call neko_warning('nsamples parameter is legacy, please use X_write_par and X_write_control instead')
TODO, we should also add this to the deprecated doxygen page

2023-05-02 08:15 UTC, MartinKarp commented on src/common/sampler.f90
> +    call neko_log%message('---Adding write output---')
I will test, but as the outputs are added at different "levels" it made things look kind of weird before.

2023-05-02 08:19 UTC, njansson commented on src/common/sampler.f90
> +    call neko_log%message('---Adding write output---')
🍻 Don't forget to call `neko_log%end_section()` otherwise the indention will look very strange.

If it still doesn't look "nice", we can add an optional "no indent" argument to section (such that we get the same `------` banner size everywhere.

2023-05-02 08:21 UTC, MartinKarp commented on src/case.f90
> +       call neko_warning('nsamples parameter is legacy, please use X_write_par and X_write_control instead')
Now or later?

2023-05-02 08:23 UTC, njansson commented on src/common/sampler.f90
> +    call neko_log%section('---Adding write output---')
```suggestion
    call neko_log%section('Adding write output')
```

THe `---` stuff is added automagically by the sampler

2023-05-04 07:11 UTC, njansson commented on src/case.f90
> +       call neko_warning('nsamples parameter is legacy, please use X_write_par and X_write_control instead')
Would be nice now, such that we don't forget it

2023-05-04 09:08 UTC, njansson requested changes

2023-05-04 09:08 UTC, njansson commented on src/common/parameters.f90
> +     real(kind=rp) :: fluid_write_par   !< Parameter for writes of fld fields
```suggestion
     real(kind=rp) :: fluid_write_par   !< Time interval for writes of fld fields
```
Isn't this a more correct description? Also for a release, we should not forget to update the doxygen page

2023-05-04 09:08 UTC, njansson commented on src/common/parameters.f90
> +     logical :: write_at_end !< Whether sampler should force output at end of simulation
Same as above, we should not forget to add this to the oxygen page

2023-05-04 09:08 UTC, njansson commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
Is it correct that we should not support stopping a simulation after a given time period?

2023-05-04 09:14 UTC, MartinKarp commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
How do you mean? If the simulation stops after 25 t units it will finish then, and by default write a checkpoint and everything in the sampler. And same if we set at joblimit.

2023-05-04 09:15 UTC, njansson commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
I mean if we set a job limit, or a signal is received to halt. But I guess that breaks sampling of stats, thus should not be supported?

2023-05-04 09:17 UTC, MartinKarp commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
That should work the same. If we send a signal we will dump everything to file, assmuing write_at_end is true. So no data will be lost

2023-05-04 09:22 UTC, njansson commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
Unless `write_at_end = .true.` then the job limit check will not be checked as far as I understands it?

2023-05-04 09:24 UTC, MartinKarp commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
The the sampler will output it since ifforce will be true

2023-05-04 09:28 UTC, njansson commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
Sure, but it will not catch signal or joblimit things since that's is not in the sampler. Maybe it's ok to accept data loss if one is using job limit

2023-05-04 09:33 UTC, MartinKarp commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
I think so? Since ifforce is true, and we leave the time step loop it will output whatever is in the sampler, reegardless if it a signal, joblimit or the run simply finishes

2023-05-04 09:41 UTC, njansson commented on src/simulation.f90
> +    if (.not. (C%params%write_at_end) .and. t .lt. C%params%T_end) then
Ok then data loss it is since signal or job limit is not handled by the sampler. fair enough

2023-05-12 14:01 UTC, njansson requested changes

2023-05-12 14:01 UTC, njansson commented on src/io/mean_flow_output.f90
> +       call device_memcpy(this%mf%w%mf%x, this%mf%w%mf%x_d,  this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
```suggestion
       call device_memcpy(this%mf%p%mf%x, this%mf%p%mf%x_d, this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
       call device_memcpy(this%mf%u%mf%x, this%mf%u%mf%x_d, this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
       call device_memcpy(this%mf%v%mf%x, this%mf%v%mf%x_d, this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
       call device_memcpy(this%mf%w%mf%x, this%mf%w%mf%x_d, this%mf%p%mf%dof%size(), DEVICE_TO_HOST)
```

2023-05-12 14:01 UTC, njansson commented on src/simulation.f90
> +    call C%s%sample(t,tstep)
```suggestion
    call C%s%sample(t, tstep)
```

2023-05-12 14:05 UTC, njansson commented on src/simulation.f90
> +       call C%s%sample(t,tstep)
```suggestion
       call C%s%sample(t, tstep)
```

2023-05-12 14:06 UTC, njansson approved these changes

2023-05-12 14:14 UTC, njansson approved these changes

2023-05-12 14:50 UTC, timofeymukha approved these changes

2023-05-12 15:42 UTC, merged