Larger mesh support
ExtremeFLOW/neko pull request #726
Opened 2022-11-23 09:40 UTC by MartinKarp

This fixes issues with generating nmsh files for meshes with more than 8 or 9 Million elements.

2022-11-23 19:54 UTC, njansson requested changes

2022-11-23 19:54 UTC, njansson commented on src/io/nmsh_file.f90
> +  integer :: max_write_nel = 8000000
```suggestion
  integer, parameter :: max_write_nel = 8000000 
```

2022-11-23 19:54 UTC, njansson commented on src/io/re2_file.f90
> +    write(*,*) 'reading curved data'
Can't we do this with neko_log

2022-11-24 10:57 UTC, MartinKarp commented on src/io/re2_file.f90
> +    write(*,*) 'reading curved data'
We use write everywhere else in re2

2022-11-24 10:57 UTC, MartinKarp commented on src/io/re2_file.f90
> +    write(*,*) 'reading curved data'
Maybe they should all be changed

2022-11-24 13:04 UTC, njansson commented on src/io/re2_file.f90
> +    write(*,*) 'reading curved data'
Ok, should probably change, but in a different pr of course

2022-11-24 13:04 UTC, njansson approved these changes

2022-11-24 13:05 UTC, merged