Dealiased scalar preview
ExtremeFLOW/neko pull request #821
Opened 2023-04-07 08:34 UTC by timofeymukha

* This is a preview of a dealiased scalar implementation. Only CPU.
* Want to get green light on that this looks correct.
* Will be part of several enhancements (mostly docs) to code involved in advection.

2023-04-07 09:22 UTC, timofeymukha commented
(Intel is right to complain here)

2023-05-02 19:28 UTC, timofeymukha commented
There we go.

2023-05-02 19:50 UTC, njansson requested changes

2023-05-02 19:50 UTC, njansson commented on tests/Makefile.am
> +	ext_bdf_scheme/test_bdf.pf
```suggestion
        fast3d/test_fd_weights_full.pf\
        fast3d/test_setup_intp.pf\
	ext_bdf_scheme/test_bdf.pf
```

2023-05-02 19:51 UTC, njansson approved these changes

2023-05-02 20:20 UTC, merged