Scalar user bc
ExtremeFLOW/neko pull request #865
Opened 2023-05-24 11:50 UTC by MartinKarp

Enables user boundary conditions for the scalar. We should look over the structure of the BCs as we have discussed, but that would be rather intrusive.

User bcs for the scalar is enabled by default for all zones that are not labeled, meaning that one gets a warning if one runs with scalar enabled on a mesh with hardcoded bcs in the mesh without setting the scalar user bc.

I will add an example RBC case in another PR to show the usage.

I have not tested on HIP and OpenCL.

2023-05-24 12:34 UTC, timofeymukha commented on examples/rayleigh-benard/rayleigh.case
>  nsamples = 50
```suggestion
```

2023-05-24 12:34 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +  !! Probably passing the whole field, params, coef, etcetc would be good
Add @param documentation for each parameter

2023-05-24 12:34 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +  !! Just imitating inflow for now, but we should look this over
Add @param documentation for each parameter

2023-05-24 12:34 UTC, timofeymukha commented on src/scalar/scalar_scheme.f90
> +  !> Initialize a user defined scalar bc
Add @param documentation for usr_eval

2023-05-24 12:34 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +  !> Assign user provided eval function
Add @param documentation for user_scalar_bc

2023-05-24 12:34 UTC, timofeymukha commented on examples/rayleigh-benard/rayleigh.case
>  nsamples = 50
Should become irrelevant since fluid_write_control is set

2023-05-24 12:42 UTC, njansson requested changes

2023-05-24 12:42 UTC, njansson commented on src/bc/bcknd/device/hip/inhom_dirichlet_kernel.h
> +}
```suggestion

/**
 * Device kernel for scalar apply for an inhomogeneous Dirichlet condition
 */
template< typename T >
__global__ void inhom_dirichlet_apply_scalar_kernel(const int * __restrict__ msk,
					    T * __restrict__ x,
					    const T * __restrict__ bla_x,
					    const int m) {

  const int idx = blockIdx.x * blockDim.x + threadIdx.x;
  const int str = blockDim.x * gridDim.x;

  for (int i = idx; i < m; i += str) {
    const int k = msk[i + 1] - 1;
    x[k] = bla_x[i];
  }
}
```

2023-05-24 12:42 UTC, njansson commented on src/scalar/scalar_pnpn.f90
> +    end if
```suggestion

    ! Check for user bcs
    if (this%user_bc%msk(0) .gt. 0) then
       call this%bc_res%mark_facets(this%user_bc%marked_facet)
    end if
```

2023-05-24 14:29 UTC, njansson approved these changes

2023-05-25 07:41 UTC, timofeymukha requested changes

2023-05-25 07:41 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +     !! JUst imitating inflow for now, but we should update this
```suggestion
     !! Just imitating inflow for now, but we should update this
```

2023-05-25 07:41 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +     !! @param u The x componenet of the velocity in this point
```suggestion
     !! @param s The scalar's value in this point
```

2023-05-25 07:41 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +     !! @param v The y componenet of the velocity in this point
```suggestion
```

2023-05-25 07:41 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +     !! @param w The w componenet of the velocity in this point
```suggestion
```

2023-05-25 07:41 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +  !! Just imitating inflow for now, but we should look this over
Still missing?

2023-05-25 12:38 UTC, timofeymukha commented on src/bc/usr_inflow.f90
> +  !! Applies boundary conditions in eval_scalar_bc on x
```suggestion
  !! Applies boundary conditions in eval_scalar_bc on x
  !! @param x The array of values to apply.
  !! @param n The size of x.
```

2023-05-25 13:08 UTC, timofeymukha approved these changes

2023-05-25 13:08 UTC, merged