Run-time selectable sources
ExtremeFLOW/neko pull request #962
Opened 2023-09-07 12:26 UTC by timofeymukha

This PR introduces run-time-selectable sources for the fluid (for now), controlled by the JSON, much like the simcomps right now. Currently, "don't merge", because I want to run the pipe example on the GPU using the new source configuration as a final test. 

## Breaking user changes
* In the case file there is now a possibility to use a `source_terms` array of JSON objects, configured much like the simcomps, e.g. with a `type` keyword.
* Currently 3 types are available: "constant", "user_vector", and "user_pointwise".
* The "constant" source requires an array of reals for the value for each component (3 for fluid, and later 1 for scalar, which is not hooked in now).

## Code design

* The json-driven component is designed just like the simcomps (base class `source_term_t`), there is a deferred constructor, `init`, which takes the json and some other stuff.  Inside the concrete source type, there is a constructor from type components that is called by the json constructor after it has parsed all the necessary stuff from the json. This way we can, in principle, init the source without json if needed. *The user-file source is not part of these classes*, more on that later.
* The sources get a `field_list`, which should contain the fields for the RHS for the given problem. So for a fluid 3 fields, and for scalar 1, meaning that we should be able to use the same types for both. The sources then directly *add* their contributions directly to these fields. I did this to avoid any copying here. 
* Inside `fluid_scheme` there are now 3 components for the RHS: `f_x`, `f_y`, `f_z` and an array for the sources. In the `step`, there is a loop through the sources, each of them adding there contribution to the RHS.
* The interface for the PnPn residual subroutines has been changed from accepting one `f_Xh` raw array to the 3 fields`f_x`, `f_y`, `f_z`. This is actually more consistent with how we pass `u`, `v`, `w` as 3 fields.
* As I said before, the user term is handled separately since one has to store procedure pointers and pass them to init which is unnecessary for the normal source terms. I re-appropriated the `source_t` class into `fluid_user_source_term_t`, which now only handles the user source term for the fluid. It is still initialized in `case.f90` as before and not in `fluid_scheme`. I think in the future, we should pass the user type to the `fluid_scheme` constructor, so that the type can take care of its own init.
* Since the user sources and the ordinary ones sit in the same JSON, the part in `fluid_scheme`, which inits the ordinary sources exchanges a user term to a constant zero-valued term on the fly. This is a hack... but it saves the pain of messing with allocated arrays. This can be improved in the future.
* In `fluid_scheme`, there is a component for the user term. In the `step` loop the user term is evaluated first, before the above-mentioned loop through the ordinary source terms.

2023-09-07 12:57 UTC, njansson commented
> Some reframe template is probably off..

Seems to be related to parsing the json into `real=sp`, restarting usually works.

2023-09-08 06:52 UTC, njansson reviewed
Nice! Some comments, mostly structure related to allow for future optimisations

2023-09-08 06:52 UTC, njansson commented on examples/cyl_boundary_layer/cyl_bl_user.case
> -        },
If I read things correctly, "noforce" will be the default do nothing approach, and instead of today, by dummy zeroing vectors?

2023-09-08 06:52 UTC, njansson commented on src/fluid/fluid_pnpn.f90
>           msh => this%msh, prs_res => this%prs_res, &
```suggestion
         p_res => this%p_res, Ax => this%Ax, Xh => this%Xh, &
         c_Xh => this%c_Xh, dm_Xh => this%dm_Xh, gs_Xh => this%gs_Xh, &
         ulag => this%ulag, vlag => this%vlag, wlag => this%wlag, &
         msh => this%msh, prs_res => this%prs_res, &
         user_source_term => this%user_source_term
```

Some minor formatting to keep within col 80

2023-09-08 06:52 UTC, njansson commented on src/fluid/fluid_pnpn.f90
> +      end if
How about encapsulating this into an own module, to keep the step loop rather clean? Then we can also make some opt. that the current setup will prevent, e.g. combined copy loops, merged kernels etc.

2023-09-08 06:52 UTC, njansson commented on src/source_terms/const_source_term.f90
> +    end if
Would suggest to (in the future) break out the compute into separate backend folders, such that we can avoid e.g. launching `n_fields` kernels, or having `n_fields` calls to `cadd` which a compiler could fuse if given more information

2023-09-08 07:07 UTC, timofeymukha commented on examples/cyl_boundary_layer/cyl_bl_user.case
> -        },
Correct, this object has no effect anymore. If there is no "source_term**s**" at all in the JSON, then the user force term defaults to being zero-valued as previously via "noforce". What is a bit concerning maybe is that the `source_term_t` array in fluid then remains unallocated, which is a bit unsatisfactory. Maybe one should add a single dummy zero-valued source term? But that's some extra operations for nothing. Or maybe we can make the array private to keep away people from touching it.

2023-09-08 07:24 UTC, timofeymukha commented on src/fluid/fluid_pnpn.f90
> +      end if
Yes good. We can have a thin `fluid_source_term_t` type having the `fluid_user_source_term_t` and the `source_term_t` array as components, and having the above code in a `compute` method. We can put the init logic there as well eventually. Our main types are becoming a bit too large to navigate conveniently, imho, `fluid_scheme_t` being one of them.

2023-09-08 08:02 UTC, timofeymukha commented on src/source_terms/const_source_term.f90
> +    end if
Yes, good point!

2023-09-09 14:07 UTC, timofeymukha commented on src/fluid/fluid_pnpn.f90
> +      end if
Now branched out.

2023-09-09 14:08 UTC, timofeymukha commented on src/source_terms/const_source_term.f90
> +    end if
Now split, but I basically have the same loops in the kernels, so not sure if it helps much.

2023-09-20 10:47 UTC, timofeymukha commented
The pipe example works on Dardel-GPU, so I am removing "don't merge"! We should check if something weird crept in during the merge with develop today.

2023-09-20 10:52 UTC, njansson approved these changes
Nice!

One minor observation, so we're going to `x,y,z` instead of `u,v,w`?

2023-09-20 10:59 UTC, timofeymukha commented
> Nice!
> 
> One minor observation, so we're going to `x,y,z` instead of `u,v,w`?

In `fluid_user_source_term_t` we retain `u, v, w`.
Do you mean `f_x, f_y, f_z` in `fluid_scheme_t`?

2023-09-20 11:01 UTC, njansson commented
> > Nice!
> > One minor observation, so we're going to `x,y,z` instead of `u,v,w`?
> 
> In `fluid_user_source_term_t` we retain `u, v, w`. Do you mean `f_x, f_y, f_z` in `fluid_scheme_t`?

True, yes this referred to `f_x` and friends. But we leave it as is now.

2023-09-20 11:05 UTC, timofeymukha commented
> > > Nice!
> > > One minor observation, so we're going to `x,y,z` instead of `u,v,w`?
> > 
> > 
> > In `fluid_user_source_term_t` we retain `u, v, w`. Do you mean `f_x, f_y, f_z` in `fluid_scheme_t`?
> 
> True, yes this referred to `f_x` and friends. But we leave it as is now.

OK. I don't have a strong opinion here, since this is in fluid, f_u etc would make sense as well.

2023-09-20 20:55 UTC, MartinKarp reviewed
Looks good, Im mostly wondering whether we want this split between user and other source terms. Maybethis would be rather intrusive, but my first thought was that it would be quite nice.

2023-09-20 20:55 UTC, MartinKarp commented on examples/rayleigh-benard-cylinder-probes/rayleigh.case
> +                "type": "user_vector"
Would it be an idea to do the same for `user_check`in simulation components as well? (And perhaps even for writing the output?). This would also address what #961 . Not immediately related, but I quite like this way of adding the user functions.

2023-09-20 20:55 UTC, MartinKarp commented on examples/rayleigh-benard-cylinder-probes/rayleigh.case
> +                "type": "user_vector"
Same applies for the other examples as well.

2023-09-20 20:55 UTC, MartinKarp commented on examples/turbpipe/pipe.f90
>      real(kind=rp), intent(in) :: t
Would it be an idea to update the .f90 to also use Re_B and Re_tau from the json_file? Or is this hard to incorporate? I see we use a constant forcing now, but I guess it would help to illustrate the power of our new case parameters to use Re_B and Re_tau here? Otherwise it might also be an idea to remove this part

2023-09-20 20:55 UTC, MartinKarp commented on examples/turbpipe/pipe_source.case
> +                "values": [0, 0, 0.0092274831]
I see, this is the computed value from Re_tau=180 and Re_B=5300 I guess. This is maybe more elegant. I don't feel strongly one way or the other.

2023-09-20 20:55 UTC, MartinKarp commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
Maybe this runs into circular dependencies, or doesn't align with how we want the code to be, but would it be possible to let the user_source_term be a special case of json_source_terms, similarly to `constant`? I don't immediately see why we want this split between the two.

2023-09-25 11:58 UTC, timofeymukha commented on examples/turbpipe/pipe.f90
>      real(kind=rp), intent(in) :: t
Yeah, actually the whole point is that we don't need the forcing function anymore since we use the built-in constant source term. So we should remove it from the f90.

2023-09-25 11:59 UTC, timofeymukha commented on examples/turbpipe/pipe_source.case
> +                "values": [0, 0, 0.0092274831]
Yeah, the idea was to use this as a demo for the constant source term. I added the formula to compute this value to the readme.

2023-09-25 12:08 UTC, timofeymukha commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
The different software-wise is that the "ordinary" source terms just operate by overloading the `compute` TBP, whereas the user term instead requires two procedure pointers, for `eval` and the `eval_pw`. So the constructor signatures are different, etc. But in principle merging these would be good. Maybe one can have the `compute` as a procedure pointer as well, and then the decendents implement their own compute and a assign the pointer in the constructor? I should give this some thought.

2023-09-25 12:11 UTC, timofeymukha commented on examples/rayleigh-benard-cylinder-probes/rayleigh.case
> +                "type": "user_vector"
I guess the principle question is whether we want to assign meaning to the order of the stuff we have in these types of arrays.

2023-09-25 13:25 UTC, timofeymukha commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
Ok, the issue with the procedure pointer approach is that we cannot do as proposed here
https://fortranwiki.org/fortran/show/Polymorphism+for+procedure+pointers+inside+derived+types

So, if I have a procedure in the base class
````fortran
 type, abstract, public:: source_term_t
     !> The fields to be updated with the source term values
     type(field_list_t) :: fields
     !> Coefficients for the SEM.
     type(coef_t), pointer :: coef => null()
     !> 
     procedure(source_term_compute), pass(this), pointer  :: eval => null()
````
with 
```fortran
  abstract interface
     subroutine source_term_compute(this, t, tstep)  
       import source_term_t, rp
       class(source_term_t), intent(inout) :: this
       real(kind=rp), intent(in) :: t
       integer, intent(in) :: tstep
     end subroutine
  end interface
```
Then in the derived type, `this`, still has to be `class(source_term_t)`, and not the derived type. So then, the sbroutine eval points to loses access to the components of the derived type, which is not acceptable.

I will think a bit more :-)

2023-09-26 11:19 UTC, adperezm commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
This looks quite nice!

2023-09-26 11:25 UTC, njansson commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
> Ok, the issue with the procedure pointer approach is that we cannot do as proposed here https://fortranwiki.org/fortran/show/Polymorphism+for+procedure+pointers+inside+derived+types
> 
> So, if I have a procedure pointer in the base class
> 
> ```fortran
>  type, abstract, public:: source_term_t
>      !> The fields to be updated with the source term values
>      type(field_list_t) :: fields
>      !> Coefficients for the SEM.
>      type(coef_t), pointer :: coef => null()
>      !> 
>      procedure(source_term_compute), pass(this), pointer  :: eval => null()
> ```
> 
> with
> 
> ```fortran
>   abstract interface
>      subroutine source_term_compute(this, t, tstep)  
>        import source_term_t, rp
>        class(source_term_t), intent(inout) :: this
>        real(kind=rp), intent(in) :: t
>        integer, intent(in) :: tstep
>      end subroutine
>   end interface
> ```
> 
> Then in the derived type, `this`, still has to be `class(source_term_t)`, and not the derived type. So then, the sbroutine eval points to loses access to the components of the derived type, which is not acceptable.
> 
> I will think a bit more :-)

It should still be possible to have the derived type since `source_term_t` is the base type. But it would then need a `select` block inside `eval` to access the derived type specific data, or maybe I'm missing something?

2023-09-26 11:28 UTC, njansson commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
This is for example how the `hash` function in `htable.f90` is implemented, base type as a class in the interface,
https://github.com/ExtremeFLOW/neko/blob/b5ae32b5626d96af3bfb42594abc9ddcc2e0ce7c/src/adt/htable.f90#L67-75
 and `select` block inside each specialisation, for example
 https://github.com/ExtremeFLOW/neko/blob/b5ae32b5626d96af3bfb42594abc9ddcc2e0ce7c/src/adt/htable.f90#L1226-1261

2023-09-26 18:11 UTC, njansson commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
> As preliminary work, I will add `user_t` the `fluid_scheme_t` constructors, so that it can initialize the user source term itself instead of `case_t` having to shove it in after `fluid_scheme_t%init` has already been run.

But we should not forget that `user_t` is not only `fluid` related, it can be rather generic.

2023-09-27 07:00 UTC, timofeymukha commented on src/fluid/fluid_source_term.f90
> +    call this%user_source_term%init(f_x%dof)
Indeed, the same thing happens e.g. with scalar now, with case setting the source.

2023-09-27 09:40 UTC, timofeymukha commented
Alright, nice CI is happy. So, ready for "re-review" I guess. Thanks for the nudge towards merging the user term into the `source_term_t` heirarchy, it was a good decision. There is only one way in which the user terms is special, and that is that it should be initialized directly from components using it's own consturctor and not through the `source_term_factory`, which uses the deferred constructor from JSON. The reason is that I don't want to mess with all the user-defined source procedures inside the factory and have them as part of the shared init interface. If you think it would be better to completely unify things, we can dot that. 

Things are also much cleaner now in the case.f90 since it does need to deal with the user source term.

2023-09-27 10:56 UTC, njansson reviewed
Not sure if I follow, so fluid related source terms are handled by the fluid scheme, but scalar ones are still done with an if block in the case file?

2023-09-27 11:00 UTC, timofeymukha commented
> Not sure if I follow, so fluid related source terms are handled by the fluid scheme, but scalar ones are still done with an if block in the case file?

Correct, because this PR does not touch scalar sources at all.

2023-09-27 11:40 UTC, MartinKarp reviewed
I think it looks good, great job Tim!

2023-09-27 11:40 UTC, MartinKarp commented on src/fluid/fluid_source_term.f90
> +       write(*,*) "HI"
```suggestion
```

2023-09-27 11:40 UTC, MartinKarp commented on src/fluid/fluid_source_term.f90
> +          end if
Looks good! One can then add variables used in the user source directly in the json file?

2023-09-27 11:42 UTC, timofeymukha commented on src/fluid/fluid_source_term.f90
> +       write(*,*) "HI"
Classic :-)

2023-09-27 12:16 UTC, MartinKarp commented on src/fluid/fluid_source_term.f90
> +          end if
Yeah, I guess, but it is still not an argument to user_srouce right?

2023-09-27 12:36 UTC, timofeymukha commented on src/fluid/fluid_source_term.f90
> +          end if
That's true, unlike some other user functions, the user source interface does not include `params`.

2023-09-27 12:41 UTC, timofeymukha commented on src/fluid/fluid_source_term.f90
> +          end if
But access could be arranged pretty easily, for example by adding the json params as a component in `fluid_user_source_term`. I think we are a still a bit wobbly about what the user subroutines have access to :-)

2023-09-29 08:17 UTC, njansson requested changes

2023-09-29 08:17 UTC, njansson commented on src/fluid/fluid_scheme.f90
> -
I guess it's impossible to validate now when we have a default "do nothing approach" or?

2023-09-29 08:28 UTC, MartinKarp approved these changes

2023-09-29 08:31 UTC, njansson commented on src/fluid/fluid_scheme.f90
> -
It's Friday, we leave this for later 🍻

2023-09-29 08:31 UTC, njansson approved these changes

2023-09-29 08:31 UTC, merged