Feature/data stream adios2
ExtremeFLOW/neko pull request #979
Opened 2023-09-20 21:49 UTC by adperezm

For excellerat we promised in situ modal decompositions.

In the past weeks I worked on the code that calculates that but now I need neko to pass the data.

Here I have all the code that I would need.

A particular change is that the communicator is split to allow for multiple processes multiple data execution.

The reason it currently says not merge is the following:

- The module data_streamer works fine when I have it in the user file and "import" neko, however when I put it in src, it is having trouble finding the adios2 functions. Do you know how I can fix this? since they are not in a module I can't just import them (Or I do not know how).
- I want to have a preprocessor flag like #ifdef HAVE_ADIOS2, to be able to compile neko without having adios2. But I can't seem to find the correct one. I tried just like with HAVE_GSLIB but it does not work. Is there a particular place where this should be added?

Is it possible to get some pointers on these two topics? After this, my Excellerat contribution will be done.

After introducing this code, we will be able to communicate code in hybrid mode with any executable that has a proper reader. And we will also to use lossless compression if one wants.

NOTE:
1. At this stage, I will not add this to "file" or something like this. I know this will be a possibility at some point, to put in the case file, that one wants "adios" file type or something. But this is out of the scope at the moment.
2. I am aware that there are conflicts. those will be fixed soon.

2023-09-20 21:52 UTC, adperezm commented
As an additional note, the example will be removed in the final version of this pull request. Also the modified comm file will be removed.

2023-09-21 08:01 UTC, adperezm commented
Do I need to create a module that binds the c++ adios2 routines as is done here? https://github.com/ExtremeFLOW/neko/blob/develop/src/math/bcknd/device/device_math.F90 ? I would still need to find a way to use the IFHAVE_ADIOS2, however. Which I do not seem to be able to use

2023-09-21 08:41 UTC, adperezm commented
> Nice! I think the io/data_streamer.F90 file is not in the PR though, or?

You were right. I do not know what is happening with me

2023-09-21 08:54 UTC, njansson commented
> Do I need to create a module that binds the c++ adios2 routines as is done here? https://github.com/ExtremeFLOW/neko/blob/develop/src/math/bcknd/device/device_math.F90 ? I would still need to find a way to use the IFHAVE_ADIOS2, however. Which I do not seem to be able to use

Yes, for calling the routines in a portable an interface is needed (also, the C++ part that is called, must be inside an `extern "C"` block, but seems to already be the case)

Regarding the preprocess flag `HAVE_ADIOS2`, one needs to add a definition in the `m4/ax_adios.m4` macro similar to what is done for gslib https://github.com/ExtremeFLOW/neko/blob/b5ae32b5626d96af3bfb42594abc9ddcc2e0ce7c/m4/ax_gslib.m4#L36-L41

2023-09-21 08:59 UTC, adperezm commented
> > Do I need to create a module that binds the c++ adios2 routines as is done here? https://github.com/ExtremeFLOW/neko/blob/develop/src/math/bcknd/device/device_math.F90 ? I would still need to find a way to use the IFHAVE_ADIOS2, however. Which I do not seem to be able to use
> 
> Yes, for calling the routines in a portable an interface is needed (also, the C++ part that is called, must be inside an `extern "C"` block, but seems to already be the case)
> 
> Regarding the preprocess flag `HAVE_ADIOS2`, one needs to add a definition in the `m4/ax_adios.m4` macro similar to what is done for gslib
> 
> https://github.com/ExtremeFLOW/neko/blob/b5ae32b5626d96af3bfb42594abc9ddcc2e0ce7c/m4/ax_gslib.m4#L36-L41
> 
> However, **without** the `LIBS` part since C++ libraries we need to handle in a different way

Thank you! I had been comparing ax_<> files but missed that

2023-09-21 09:06 UTC, njansson commented on src/comm/comm.F90
This file be regenerated for each configure, thus it should not be in the repository.

2023-09-21 09:06 UTC, njansson commented on src/comm/comm.F90.in
> +    call MPI_Comm_split(MPI_COMM_WORLD,0, global_rank,NEKO_COMM,ierr)
Not sure if I understand this part.

In the original code we clone `MPI_COMM_WORLD`, but the changes will split `MPI_COMM_WORLD` based on colors, but since all ranks provide the same colors, wouldn't this end up being the same thing?

`MPI_Comm_split` can be a rather costly at scale (depending on the MPI implementation) so I would rather avoid it if possible

2023-09-21 09:30 UTC, adperezm commented on src/comm/comm.F90
Yeah, I realized that and will remove it in subsequent push.

2023-09-21 09:31 UTC, adperezm commented on src/comm/comm.F90.in
> +    call MPI_Comm_split(MPI_COMM_WORLD,0, global_rank,NEKO_COMM,ierr)
Yeah, so this does not affect Neko. The other color will be from the data processor. which would be running in another executable at the same time and would take care of the data asyncrhonously.

If this is not done, then I do not know how to do asynchronous execution.

2023-09-21 11:06 UTC, njansson commented on src/comm/comm.F90.in
> +    call MPI_Comm_split(MPI_COMM_WORLD,0, global_rank,NEKO_COMM,ierr)
Thanks, think I understand it now. I also read up a bit on the ADIOS2 documentation as well, and it seems like it can't be avoided.

This will have some implications on the device backend, but a good reason to clean up the sloppy usage of MPI comms there.

2023-09-23 12:39 UTC, adperezm commented
Hi! Thanks to the help from everyone I think we are in a good stage to merge to develop. I have removed the "do not merge" tag

2023-09-24 10:50 UTC, timofeymukha commented
Hi Adalberto! Glancing at the data_streamer file here are a few things:
* Indentation inside the type is not spot on.
* There is no docstring for the type. For this type I think it would be good to be quite thorough, e.g. say what is the intention, what is streamed and how, etc. It's obvious to you of course, but I, for example, have a very vague idea :-). Some details should maybe go to the docstring of the `stream` subroutine.
* @params docstrings for the parameters are missing.
* There is some strange mix with whitespace between arguments in procedure calls. Some have no space at all, some have  even more than one :-). I would, say just have one space after the comma for each argument.
* Some lines are long, like 181. Make sure you have max 80 cols and just use & for line continuation.
Thanks a lot!

2023-09-24 15:12 UTC, adperezm commented
> Hi Adalberto! Glancing at the data_streamer file here are a few things:
> 
> * Indentation inside the type is not spot on.
> * There is no docstring for the type. For this type I think it would be good to be quite thorough, e.g. say what is the intention, what is streamed and how, etc. It's obvious to you of course, but I, for example, have a very vague idea :-). Some details should maybe go to the docstring of the `stream` subroutine.
> * @params docstrings for the parameters are missing.
> * There is some strange mix with whitespace between arguments in procedure calls. Some have no space at all, some have  even more than one :-). I would, say just have one space after the comma for each argument.
> * Some lines are long, like 181. Make sure you have max 80 cols and just use & for line continuation.
>   Thanks a lot!

I think I added these now. Thanks!

2023-09-24 15:34 UTC, timofeymukha commented
Great! Question about the config.xml, could it perhaps be renamed to something like `adios2_config.xml` so that it is clear what the purpose is without having to look inside the file?

2023-09-25 10:35 UTC, timofeymukha approved these changes

2023-09-27 12:16 UTC, adperezm commented
When you have time please let me know if there is something I should correct here.

2023-09-28 20:01 UTC, njansson commented
Please don't merge this until we have made comm split optional, and ensured the new communicator is propagated correctly down to the device backends.

I'll have a look at this in the coming days.

2023-09-28 20:03 UTC, njansson requested changes

2023-09-28 20:03 UTC, njansson commented on src/comm/comm.F90.in
> +    call MPI_Comm_split(MPI_COMM_WORLD,0, global_rank,NEKO_COMM,ierr)
Still a bit unsure if we want to have split as the default unless needed.

@njansson will have a look how we can make this optional based on the Neko configuration.

2023-09-29 07:41 UTC, njansson approved these changes

2023-09-29 07:51 UTC, merged