Feature user dirichlet bcs
ExtremeFLOW/neko pull request #985
Opened 2023-09-28 20:55 UTC by MartinKarp

Draft for user Dirichlet bcs (issue #983) that will work better on the device and enable more freedom for the user. My ambition is that the functionality needed from @vbaconnet , @ronithstanly , and @adperezm  should be covered in addition to open up opportunities for even more advanced features (say we add geometric shapes and so on). 

I have tested it with the cyl_bl case and it seems to work at first glance. I added a case file `cyl_bl_user_bc_test.case` that should be removed/changed before this is merged. This new case illustrates how this functionality can be used together with an updated `cyl_bl.f90`. This is a rather rough draft that I would appreciate help from @vbaconnet and @adperezm to make into a finished product. There are a few points that needs to be fixed.

- [ ] What arguments do we want to pass to user_dirichlet_update? I think we might need coef and perhaps other things too. 
- [ ]  We should implement a field_dirichlet_vector that can be added to the bcl ist for velocity and make the application of BCs for the different velocity components in one go.
- [ ] We need to check whether the zones marked with dirichlet bs for parts of the velocity component should be added to the sym and pressure surfaces in fluid_pnpn. This needs to be tested extensively.
- [ ] When we have settled these points we also need to test it further.
- [ ] Extend the GPU support for HIIP/OpenCL too.
- [ ] The bc labels are currently very minimalistic `du,dv,...` perhaps this should be more verbose. This would also mean that we extend the length of each bc_label by more than 20 characters.
- [ ] Add the same functionality to the scalar and add it to the bc list in case.f90.
- [ ] split_string needs to be cleaned, it is not pretty.

I expect there to be a few bugs, but I think it gives a good indication of which parts of the framework we need to look at to create a good solution for BCs. 

The changes proposed in this PR should be completely optional in that it does not impact any case that does not make use of these new features.

2023-10-04 11:31 UTC, adperezm commented
I will start checking this next week (or by the end of this one).  Just an update

2023-10-05 14:34 UTC, vbaconnet commented
Starting to look at gather scatter for shared points whose owning elements have different boundary conditions, as done in Nek5000 ([here](https://kth-nek5000.github.io/KTH_Framework/plan4_8f.html#aedd42d0105ac2c4eac995ac75c027a4a) and [here](https://kth-nek5000.github.io/KTH_Framework/dssum_8f.html#ab0865b005738b43cd2bcc73e7bac86f7)).

2023-10-13 09:34 UTC, vbaconnet commented
Just a thought I had while playing around with one of my cases: Since the dirichlet user bc will be used to set boundary conditions (not only, but mostly), would it make sense to expose BC masks to the user? 

At the moment, if one wants to set a non-uniform boundary condition, I think the only way is to loop over each `labeled_zones(i)`'s `facet_el` and select the GLL points based on the facet index, etc. Thoughts?

2023-10-25 13:41 UTC, MartinKarp commented on src/fluid/fluid_scheme.f90
> +    !call this%gs_Xh%op(this%u, GS_OP_MAX)
I think this is necessary as we accommodate shared points along bc interfaces. Also I think the parts that are commented here are probably the simplest way to ensure that the dirichlet is actually set on both sides of the element interface.

2023-10-25 13:41 UTC, MartinKarp commented on src/fluid/fluid_scheme.f90
> +    !call this%gs_Xh%op(this%p, GS_OP_MIN)
Same here, something to ensure that the correct bc is applied on both sides o the element is necessary.

2023-10-25 13:41 UTC, MartinKarp commented on src/fluid/fluid_pnpn.f90
> +
Here is where I think we need to expand the finalize for the boundary conditions because of the interface between different elements issue. 

This could be done by something like this
``` fortran90
call this%bc_dw%finalize()
temp_array = 1.0
call this%bc_dw%apply(temp_array) !sets some values to 0
call gs%op(temp_array,GS_OP_MIN) !might change values on element boundaries.
new_mask = get_index(temp_array .ne. 1.0) !Check what values are affaected
call bc_dw%update_bc_mask(new_mask) !Update to new (correct) mask that takes care of element interfaces.
```
Something like that I think. An alternative would be to pass down gs when finalizing the bc and do something similar. However, we really need to make sure that we can have that the bc changes between element and not only in unique points. 

For some background and to illustrate the problem I am talking about I have the small picture below. When we create the mask in a bc for BC2 this will be applied on the face between p1 and p2, but p1 will also have the condition BC1. If these are mixed Neumann/Dirichlet we have an issue as p1 might then have two values. The mask for the Dirichlet condition must as such be carried out on both sides of the interface and this can be checked with a gs%op when setting up the mask. The issue does not exist for BC2 and BC3 since p3 is unique and only exists on one element. This case is the most common and this is why this bug has not been addressed until now.

Element 1 Element 2
   BC1-------BC2
px -----  p1 ------ p3
| interior | interior |   BC3
| interior | interior | 
px ----- p2 ------- p4

2023-10-25 13:41 UTC, MartinKarp commented
Added some comments on how I think these things can be resolved.

2024-02-05 09:20 UTC, vbaconnet commented on src/fluid/fluid_scheme.f90
> +    !call this%gs_Xh%op(this%u, GS_OP_MAX)
This will be taken care of in another PR

2024-02-05 09:20 UTC, vbaconnet commented on src/fluid/fluid_scheme.f90
> +    !call this%gs_Xh%op(this%p, GS_OP_MIN)
This will be taken care of in another PR.

2024-02-05 09:20 UTC, vbaconnet commented on src/fluid/fluid_pnpn.f90
> +
This will be taken care of in another PR

2024-02-25 11:42 UTC, timofeymukha requested changes

2024-02-25 11:42 UTC, timofeymukha commented on src/scalar/scalar_pnpn.f90
> +    call bc_list_add(this%bclst_ds, this%bc_ds)
Perhaps confused, but do you need `bc_ds` at all? Can't you mark the `d_s` zones in the already existing `bc_res`?

2024-02-25 11:42 UTC, timofeymukha commented on src/fluid/fluid_pnpn.f90
>       type(non_normal_t) :: bc_vel_res_non_normal   !< Dirichlet condition vel. res.
Both here and in the scalar, the naming du, dv, dw, ds will cause confusion, because we also use that to refere to $\Delta u$ etc, i.e. the increment. But here the d refers to dirichlet, or?

2024-02-25 11:42 UTC, timofeymukha commented on src/simulation.f90
> +
I am wondering if we can "decentralize" and avoid putting the bc stuff into the case. What if scalar and fluid call this routine themselves. The user is passed to scalar and fluid constructors, so they could store a procedure pointer. Then, inside the user code one would make an "if" based on the field names to decide what to do, I guess.

The reason I want this is because if e.g. the scalar becomes a simcomp, then it's the simcomp that has access to the case but not vice versa,so the relationship between these types has to be inversed in the code.

2024-03-06 12:52 UTC, timofeymukha commented on src/scalar/scalar_pnpn.f90
> +    call bc_list_add(this%bclst_ds, this%bc_ds)
Yeah, I didn't get it either at first. The idea is that this forces 0 for the change in the solution, wherever we prescribe some dirichlet condition.

2024-03-06 12:58 UTC, vbaconnet commented on src/fluid/fluid_pnpn.f90
>       type(non_normal_t) :: bc_vel_res_non_normal   !< Dirichlet condition vel. res.
Yes I believe d refers to dirichlet. Perhaps another name is needed indeed :)

2024-03-06 14:24 UTC, MartinKarp reviewed
Might not be entirely correct, but I think maybe we could merge a lot of the stuff for u,v,w individually since we have the vel_dir condition now instead

2024-03-06 14:24 UTC, MartinKarp commented on src/fluid/fluid_scheme.f90
> +    call this%bc_field_v%init(this%dm_Xh)
is the one for v,w necessary anymore? If we check for d_vel, we can just init bc_field_v and bc_field_w directly

2024-03-06 14:24 UTC, MartinKarp commented on src/fluid/fluid_scheme.f90
> +       call this%bc_field_w%apply_scalar_dev(this%w%x_d, t, tstep)
Yes, but tbh I guess there should simply be something like field_list instead of vector/scalar or what do you think?

2024-03-06 14:24 UTC, MartinKarp commented on src/fluid/fluid_scheme.f90
> +       call this%bc_field_w%apply_scalar_dev(this%w%x_d, t, tstep)
I think now thoough as we moved away from individual du, dv, dw, this oculd be done pretty easily

2024-03-18 15:09 UTC, vbaconnet commented
Maybe an update on this, after discussions with Martin it seems that separating the field dirichlet into individual "u,v,w" components offered a bit more possibilities, so I reverted back to that. Will adress the other points now.

2024-03-18 15:19 UTC, vbaconnet commented on src/fluid/fluid_scheme.f90
> +    call this%bc_field_v%init(this%dm_Xh)
Moved back to uvw individual components so I guess this is not applicable anymore right?

2024-03-19 11:42 UTC, njansson commented on src/math/bcknd/device/device_math.F90
> +#endif
@njansson  add an OpenCL kernel

2024-03-20 08:07 UTC, njansson requested changes

2024-03-20 08:07 UTC, njansson commented on src/bc/field_dirichlet.f90
> +     subroutine field_dirichlet_update(dirichlet_field_list, dirichlet_bc_list, coef, t, tstep)
```suggestion
  !> Abstract interface defining a dirichlet condition on a list of fields.
  !! @param field_bc_list List of fields that are used to extract values for field_dirichlet.
  !! @param dirichlet_bc_list List of BCs containing field_dirichlet_t BCs only.
  !! @param coef Coef object.
  !! @param t Current time.
  !! @param tstep Current time step.
  abstract interface
     subroutine field_dirichlet_update(dirichlet_field_list, dirichlet_bc_list, coef, t, tstep)
```

2024-03-20 08:07 UTC, njansson commented on src/fluid/fluid_scheme.f90
> +     !type(field_dirichlet_t) :: bc_field_w   !< Dirichlet pressure condition
remove?

2024-03-20 08:39 UTC, njansson commented on src/math/bcknd/device/device_math.F90
> +#endif
added

2024-03-25 14:55 UTC, timofeymukha commented on src/simulation.f90
> +
@vbaconnet As far as I can see things are still in `case`, right? Was that too difficult to change?

2024-03-25 14:59 UTC, vbaconnet commented on src/simulation.f90
> +
Thinking about this right now, haven't had time to do much lately :( But I am having trouble understanding what you mean with this, would `fluid` and `scalar` each have a procedure pointer to `user_dirichlet_update`?

2024-03-25 15:07 UTC, timofeymukha commented on src/simulation.f90
> +
No problem, just asking. Yes, that was what I was thinking. They would store a pointer to this routine and call it in `step` at an appropriate location. They would then pass their own field lists and masks. And then the user has to figure out what to do depending on what is passed, probably based on the names of the fields.

2024-03-27 13:39 UTC, vbaconnet commented on src/simulation.f90
> +
Sorry didn't answer this, I just pushed something that should implement what you described :)

2024-03-27 13:45 UTC, vbaconnet commented on src/fluid/fluid_pnpn.f90
>      call this%bc_sym_surface%finalize()
Not sure if resolved but everything I have ran so far with these BCs have been working as expected. So a priori I would say yes? :)

2024-03-27 13:48 UTC, vbaconnet commented on examples/cyl_boundary_layer/cyl_bl_user_bc_test.case
> +{
Updated, however I don't know what to do with this example. It showcases how to use the field BCs, but that's pretty much it. Perhaps we can keep it to have an example of usage somewhere but in the future perhaps it should have its own example?

2024-03-27 13:49 UTC, vbaconnet commented on src/bc/field_dirichlet.f90
> +       character(len=*), intent(in) :: which_solver
The choice of the naming here was kind of arbitrary...

2024-03-27 14:19 UTC, timofeymukha commented
Amazing work. Is there something we need to update in the user-file documentation?

2024-03-27 15:44 UTC, vbaconnet commented
> Amazing work. Is there something we need to update in the user-file documentation?

Yes I forgot to mention that, I will add a small section in the user file doc about this! Then it should be ready (finally!) for final revisions from everyone :)

2024-03-28 08:05 UTC, vbaconnet commented on src/simulation.f90
> +
marking this as resolved!

2024-03-28 09:55 UTC, vbaconnet commented
Pushing some documentation but is not finished yet.

2024-04-03 17:02 UTC, vbaconnet commented
Okay I think this is the best I can do for now :) I think this version is ready for final reviews. Documentation is finished but can be rewritten at will for clarifications or improvements. 

The user interface could probably be improved in the way the fields and bcs are handled but that would require a lot more time that I unfortunately don't have :(

2024-04-03 18:38 UTC, njansson approved these changes
Great stuff!

I would suggest that we merge it now, and cleanup the interface later

2024-04-03 18:38 UTC, njansson commented on src/fluid/fluid_pnpn.f90
> +    end if
```suggestion
      if (NEKO_BCKND_DEVICE .eq. 1) then
         call this%bc_field_dirichlet_u%apply_scalar_dev(u_res%x_d, t, tstep)
         call this%bc_field_dirichlet_v%apply_scalar_dev(v_res%x_d, t, tstep)
         call this%bc_field_dirichlet_w%apply_scalar_dev(w_res%x_d, t, tstep)
      else 
         call this%bc_field_dirichlet_u%apply_scalar(u_res%x, this%dm_Xh%size(), t, tstep)
         call this%bc_field_dirichlet_v%apply_scalar(v_res%x, this%dm_Xh%size(), t, tstep)
         call this%bc_field_dirichlet_w%apply_scalar(w_res%x, this%dm_Xh%size(), t, tstep)
      end if
```

2024-04-03 18:38 UTC, njansson commented on src/fluid/fluid_scheme.f90
> +    ! Setup field dirichlet bc for v-velocity
```suggestion
    ! Setup field dirichlet bc for u-velocity
```

2024-04-03 18:38 UTC, njansson commented on src/fluid/fluid_scheme.f90
> +    !integer :: integer_val
```suggestion
```

2024-04-04 11:33 UTC, MartinKarp reviewed
I also think this looks very good now, if @timofeymukha thinks its also ok I would suggest we merge. Maybe before #1215 ? Regardless I guess there will be a bunch of conflicts between them.

2024-04-04 11:50 UTC, njansson commented
> I also think this looks very good now, if @timofeymukha thinks its also ok I would suggest we merge. Maybe before #1215 ? Regardless I guess there will be a bunch of conflicts between them.

Great! Let's get it in an we deal with the cleanup later 🐈‍⬛

2024-04-04 13:04 UTC, timofeymukha commented
Guys I am a little overwhelmed atm, and I've reviewed this thoroughly at the last iteration, with all the stuff addressed it seems. So if two more pair of eyes thing this looks good -- please merge.

2024-04-04 13:09 UTC, MartinKarp commented
Its only I cannot approve, since I am the initial author of the PR.

2024-04-04 13:09 UTC, timofeymukha approved these changes

2024-04-04 13:09 UTC, merged